import type { LocalizedStrings } from '@anytools/ui';

const EN = {
  title: 'Readability Analyzer',
  description: 'Flesch Reading Ease, Flesch-Kincaid Grade Level, Gunning Fog. English text only.',
  text: 'Text',
  words: 'Words',
  sentences: 'Sentences',
  syllables: 'Syllables',
  fleschEase: 'Flesch Reading Ease',
  fkGrade: 'Flesch-Kincaid Grade',
  gunningFog: 'Gunning Fog',
  readingLevel: 'Reading level',
  enterText: 'Enter text.',
  level_universal: 'Universal',
  level_collegeGraduate: 'College graduate',
  level_college: 'College',
  level_grade10to12: '10th–12th grade',
  level_grade8to9: '8th–9th grade',
  level_grade7: '7th grade',
  level_grade6: '6th grade',
};

export const STRINGS: LocalizedStrings<typeof EN> = {
  en: EN,
  vi: {
    title: 'Phân tích độ dễ đọc',
    description:
      'Flesch Reading Ease, Flesch-Kincaid Grade Level, Gunning Fog. Chỉ dành cho văn bản tiếng Anh.',
    text: 'Văn bản',
    words: 'Số từ',
    sentences: 'Số câu',
    syllables: 'Số âm tiết',
    fleschEase: 'Flesch Reading Ease',
    fkGrade: 'Flesch-Kincaid Grade',
    gunningFog: 'Gunning Fog',
    readingLevel: 'Trình độ đọc',
    enterText: 'Nhập văn bản.',
    level_universal: 'Phổ thông',
    level_collegeGraduate: 'Tốt nghiệp đại học',
    level_college: 'Đại học',
    level_grade10to12: 'Lớp 10–12',
    level_grade8to9: 'Lớp 8–9',
    level_grade7: 'Lớp 7',
    level_grade6: 'Lớp 6',
  },
  es: {
    title: 'Analizador de legibilidad',
    description:
      'Flesch Reading Ease, Flesch-Kincaid Grade Level, Gunning Fog. Solo texto en inglés.',
    text: 'Texto',
    words: 'Palabras',
    sentences: 'Oraciones',
    syllables: 'Sílabas',
    fleschEase: 'Flesch Reading Ease',
    fkGrade: 'Flesch-Kincaid Grade',
    gunningFog: 'Gunning Fog',
    readingLevel: 'Nivel de lectura',
    enterText: 'Introduce texto.',
    level_universal: 'Universal',
    level_collegeGraduate: 'Graduado universitario',
    level_college: 'Universitario',
    level_grade10to12: '10.º–12.º grado',
    level_grade8to9: '8.º–9.º grado',
    level_grade7: '7.º grado',
    level_grade6: '6.º grado',
  },
  pt: {
    title: 'Analisador de legibilidade',
    description:
      'Flesch Reading Ease, Flesch-Kincaid Grade Level, Gunning Fog. Apenas texto em inglês.',
    text: 'Texto',
    words: 'Palavras',
    sentences: 'Frases',
    syllables: 'Sílabas',
    fleschEase: 'Flesch Reading Ease',
    fkGrade: 'Flesch-Kincaid Grade',
    gunningFog: 'Gunning Fog',
    readingLevel: 'Nível de leitura',
    enterText: 'Digite um texto.',
    level_universal: 'Universal',
    level_collegeGraduate: 'Pós-graduação',
    level_college: 'Ensino superior',
    level_grade10to12: '10.º–12.º ano',
    level_grade8to9: '8.º–9.º ano',
    level_grade7: '7.º ano',
    level_grade6: '6.º ano',
  },
};
