import type { LocalizedStrings } from '@anytools/ui';

const EN = {
  title: 'JSON Schema Validator',
  schemaLabel: 'JSON Schema',
  dataLabel: 'JSON data',
  schemaPlaceholder: '{ "type": "object", "properties": { "id": { "type": "integer" } } }',
  dataPlaceholder: '{ "id": 42 }',
  draftLabel: 'Draft',
  draft07: 'draft-07',
  draft2020: '2020-12',
  inferButton: 'Infer schema from data',
  inferFailed: 'Could not infer a schema — data must be valid JSON first.',
  valid: 'Valid — data matches the schema.',
  invalidCount: '{n} field failed validation.',
  invalidCountPlural: '{n} fields failed validation.',
  waiting: 'Paste a schema and data to validate…',
  paramsLabel: 'Details',
  error_invalidSchemaJson: 'Schema is not valid JSON: {detail}',
  error_invalidDataJson: 'Data is not valid JSON: {detail}',
  error_schemaCompileError: 'Schema is not valid JSON Schema: {detail}',
};

export const STRINGS: LocalizedStrings<typeof EN> = {
  en: EN,
  vi: {
    title: 'Kiểm tra JSON theo Schema',
    schemaLabel: 'JSON Schema',
    dataLabel: 'Dữ liệu JSON',
    schemaPlaceholder: '{ "type": "object", "properties": { "id": { "type": "integer" } } }',
    dataPlaceholder: '{ "id": 42 }',
    draftLabel: 'Phiên bản',
    draft07: 'draft-07',
    draft2020: '2020-12',
    inferButton: 'Suy ra schema từ dữ liệu',
    inferFailed: 'Không suy ra được schema — dữ liệu phải là JSON hợp lệ trước đã.',
    valid: 'Hợp lệ — dữ liệu khớp schema.',
    invalidCount: '{n} trường không hợp lệ.',
    invalidCountPlural: '{n} trường không hợp lệ.',
    waiting: 'Dán schema và dữ liệu để kiểm tra…',
    paramsLabel: 'Chi tiết',
    error_invalidSchemaJson: 'Schema không phải JSON hợp lệ: {detail}',
    error_invalidDataJson: 'Dữ liệu không phải JSON hợp lệ: {detail}',
    error_schemaCompileError: 'Schema không phải JSON Schema hợp lệ: {detail}',
  },
  es: {
    title: 'Validador de esquema JSON',
    schemaLabel: 'JSON Schema',
    dataLabel: 'Datos JSON',
    schemaPlaceholder: '{ "type": "object", "properties": { "id": { "type": "integer" } } }',
    dataPlaceholder: '{ "id": 42 }',
    draftLabel: 'Versión',
    draft07: 'draft-07',
    draft2020: '2020-12',
    inferButton: 'Inferir esquema desde los datos',
    inferFailed: 'No se pudo inferir un esquema — los datos deben ser JSON válido primero.',
    valid: 'Válido — los datos cumplen el esquema.',
    invalidCount: '{n} campo no pasó la validación.',
    invalidCountPlural: '{n} campos no pasaron la validación.',
    waiting: 'Pega un esquema y datos para validar…',
    paramsLabel: 'Detalles',
    error_invalidSchemaJson: 'El esquema no es JSON válido: {detail}',
    error_invalidDataJson: 'Los datos no son JSON válido: {detail}',
    error_schemaCompileError: 'El esquema no es un JSON Schema válido: {detail}',
  },
  pt: {
    title: 'Validador de esquema JSON',
    schemaLabel: 'JSON Schema',
    dataLabel: 'Dados JSON',
    schemaPlaceholder: '{ "type": "object", "properties": { "id": { "type": "integer" } } }',
    dataPlaceholder: '{ "id": 42 }',
    draftLabel: 'Versão',
    draft07: 'draft-07',
    draft2020: '2020-12',
    inferButton: 'Inferir esquema a partir dos dados',
    inferFailed: 'Não foi possível inferir um esquema — os dados precisam ser JSON válido antes.',
    valid: 'Válido — os dados correspondem ao esquema.',
    invalidCount: '{n} campo falhou na validação.',
    invalidCountPlural: '{n} campos falharam na validação.',
    waiting: 'Cole um esquema e dados para validar…',
    paramsLabel: 'Detalhes',
    error_invalidSchemaJson: 'O esquema não é JSON válido: {detail}',
    error_invalidDataJson: 'Os dados não são JSON válido: {detail}',
    error_schemaCompileError: 'O esquema não é um JSON Schema válido: {detail}',
  },
};
