import type { LocalizedStrings } from '@anytools/ui';

const EN = {
  title: 'Barcode Generator',
  symbology: 'Symbology',
  dataToEncode: 'Data to encode',
  // {n} is the module size in pixels.
  moduleSize: 'Module size: {n} px',
  quietZone: 'Quiet zone (margin)',
  printDigits: 'Print the digits under the bars',
  encoding: 'Encoding…',
  generate: 'Generate barcode',
  encodeFailed: 'This value could not be encoded.',
  // {value} is the value actually encoded (e.g. with the check digit appended).
  encodedAs: 'Encoded as {value}.',
  imageAlt: '{format} barcode encoding {value}',
  downloadPng: 'Download PNG',
  downloadSvg: 'Download SVG',
  // {qr} and {scanner} are replaced with links.
  crossLink:
    'Need a QR code? Use the {qr} — it has templates for Wi-Fi, vCard and email. To check a code you have made, the {scanner} reads it back.',
  qrLink: 'QR code generator',
  scannerLink: 'barcode scanner',
  // Per-symbology hints; the logic layer carries the English originals.
  hint_EAN13: '13 digits (or 12 — we add the check digit)',
  hint_EAN8: '8 digits (or 7 — we add the check digit)',
  hint_UPCA: '12 digits (or 11 — we add the check digit)',
  hint_ITF14: '14 digits (or 13 — we add the check digit)',
  hint_ITF: 'digits, an even number of them',
  hint_Code128: 'any ASCII text',
  hint_Code39: 'A–Z, 0–9, space and - . $ / + %',
  hint_DataMatrix: 'any text',
  hint_PDF417: 'any text',
  hint_Aztec: 'any text',
  error_enterData: 'Enter the data to encode.',
  error_digitsOnly: '{format} holds digits only — no letters or punctuation.',
  error_digitCount:
    '{format} needs {total} digits (or {body} and we work out the last one). You entered {entered}.',
  error_checkDigitWrong:
    'Check digit is wrong: {body} ends in {want}, not {got}. Scanners reject this code.',
  error_itfDigitsOnly: 'ITF holds digits only.',
  error_itfEvenCount:
    'ITF encodes digits in pairs, so it needs an even count. You entered {entered}.',
  error_code39Alphabet: 'Code 39 only carries A–Z, 0–9, space and - . $ / + % — nothing else.',
  error_code128Latin1:
    'Code 128 cannot encode "{char}". Use Data Matrix, PDF417 or Aztec for text outside Latin-1.',
  error_checkDigitDigitsOnly: 'Check digits are only defined for digit strings',
  error_unknownFormat: 'Unknown barcode format: {id}',
  note_checkDigitAdded: 'Check digit {check} added.',
  note_code39Uppercased: 'Code 39 has no lowercase; text was uppercased.',
};

export const STRINGS: LocalizedStrings<typeof EN> = {
  en: EN,
  vi: {
    title: 'Tạo mã vạch',
    symbology: 'Loại mã vạch',
    dataToEncode: 'Dữ liệu cần mã hóa',
    moduleSize: 'Cỡ mô-đun: {n} px',
    quietZone: 'Vùng trống (lề)',
    printDigits: 'In chữ số bên dưới vạch',
    encoding: 'Đang mã hóa…',
    generate: 'Tạo mã vạch',
    encodeFailed: 'Không thể mã hóa giá trị này.',
    encodedAs: 'Đã mã hóa thành {value}.',
    imageAlt: 'Mã vạch {format} mã hóa {value}',
    downloadPng: 'Tải PNG',
    downloadSvg: 'Tải SVG',
    crossLink:
      'Cần mã QR? Dùng {qr} — có sẵn mẫu cho Wi-Fi, vCard và email. Để kiểm tra mã bạn vừa tạo, {scanner} sẽ đọc lại nó.',
    qrLink: 'trình tạo mã QR',
    scannerLink: 'trình quét mã vạch',
    hint_EAN13: '13 chữ số (hoặc 12 — chúng tôi thêm số kiểm tra)',
    hint_EAN8: '8 chữ số (hoặc 7 — chúng tôi thêm số kiểm tra)',
    hint_UPCA: '12 chữ số (hoặc 11 — chúng tôi thêm số kiểm tra)',
    hint_ITF14: '14 chữ số (hoặc 13 — chúng tôi thêm số kiểm tra)',
    hint_ITF: 'chữ số, số lượng chẵn',
    hint_Code128: 'văn bản ASCII bất kỳ',
    hint_Code39: 'A–Z, 0–9, dấu cách và - . $ / + %',
    hint_DataMatrix: 'văn bản bất kỳ',
    hint_PDF417: 'văn bản bất kỳ',
    hint_Aztec: 'văn bản bất kỳ',
    error_enterData: 'Nhập dữ liệu cần mã hóa.',
    error_digitsOnly: '{format} chỉ chứa chữ số — không có chữ cái hay dấu câu.',
    error_digitCount:
      '{format} cần {total} chữ số (hoặc {body} và chúng tôi tính chữ số cuối). Bạn đã nhập {entered}.',
    error_checkDigitWrong:
      'Số kiểm tra sai: {body} phải kết thúc bằng {want}, không phải {got}. Máy quét sẽ từ chối mã này.',
    error_itfDigitsOnly: 'ITF chỉ chứa chữ số.',
    error_itfEvenCount: 'ITF mã hóa chữ số theo cặp nên cần số lượng chẵn. Bạn đã nhập {entered}.',
    error_code39Alphabet: 'Code 39 chỉ chứa A–Z, 0–9, khoảng trắng và - . $ / + % — không gì khác.',
    error_code128Latin1:
      'Code 128 không mã hóa được "{char}". Dùng Data Matrix, PDF417 hoặc Aztec cho văn bản ngoài Latin-1.',
    error_checkDigitDigitsOnly: 'Số kiểm tra chỉ được định nghĩa cho chuỗi chữ số',
    error_unknownFormat: 'Định dạng mã vạch không xác định: {id}',
    note_checkDigitAdded: 'Đã thêm số kiểm tra {check}.',
    note_code39Uppercased: 'Code 39 không có chữ thường; văn bản đã được viết hoa.',
  },
  es: {
    title: 'Generador de códigos de barras',
    symbology: 'Simbología',
    dataToEncode: 'Datos a codificar',
    moduleSize: 'Tamaño de módulo: {n} px',
    quietZone: 'Zona de silencio (margen)',
    printDigits: 'Imprimir los dígitos bajo las barras',
    encoding: 'Codificando…',
    generate: 'Generar código de barras',
    encodeFailed: 'No se pudo codificar este valor.',
    encodedAs: 'Codificado como {value}.',
    imageAlt: 'Código de barras {format} que codifica {value}',
    downloadPng: 'Descargar PNG',
    downloadSvg: 'Descargar SVG',
    crossLink:
      '¿Necesitas un código QR? Usa el {qr}: tiene plantillas para Wi-Fi, vCard y correo. Para comprobar un código que hayas creado, el {scanner} lo lee de vuelta.',
    qrLink: 'generador de códigos QR',
    scannerLink: 'escáner de códigos de barras',
    hint_EAN13: '13 dígitos (o 12 — añadimos el dígito de control)',
    hint_EAN8: '8 dígitos (o 7 — añadimos el dígito de control)',
    hint_UPCA: '12 dígitos (u 11 — añadimos el dígito de control)',
    hint_ITF14: '14 dígitos (o 13 — añadimos el dígito de control)',
    hint_ITF: 'dígitos, en cantidad par',
    hint_Code128: 'cualquier texto ASCII',
    hint_Code39: 'A–Z, 0–9, espacio y - . $ / + %',
    hint_DataMatrix: 'cualquier texto',
    hint_PDF417: 'cualquier texto',
    hint_Aztec: 'cualquier texto',
    error_enterData: 'Introduce los datos a codificar.',
    error_digitsOnly: '{format} solo admite dígitos: sin letras ni puntuación.',
    error_digitCount:
      '{format} necesita {total} dígitos (o {body} y calculamos el último). Introdujiste {entered}.',
    error_checkDigitWrong:
      'El dígito de control es incorrecto: {body} termina en {want}, no en {got}. Los escáneres rechazan este código.',
    error_itfDigitsOnly: 'ITF solo admite dígitos.',
    error_itfEvenCount:
      'ITF codifica los dígitos por pares, así que necesita una cantidad par. Introdujiste {entered}.',
    error_code39Alphabet: 'Code 39 solo admite A–Z, 0–9, espacio y - . $ / + %: nada más.',
    error_code128Latin1:
      'Code 128 no puede codificar "{char}". Usa Data Matrix, PDF417 o Aztec para texto fuera de Latin-1.',
    error_checkDigitDigitsOnly:
      'Los dígitos de control solo están definidos para cadenas de dígitos',
    error_unknownFormat: 'Formato de código de barras desconocido: {id}',
    note_checkDigitAdded: 'Dígito de control {check} añadido.',
    note_code39Uppercased: 'Code 39 no tiene minúsculas; el texto se pasó a mayúsculas.',
  },
  pt: {
    title: 'Gerador de código de barras',
    symbology: 'Simbologia',
    dataToEncode: 'Dados a codificar',
    moduleSize: 'Tamanho do módulo: {n} px',
    quietZone: 'Zona de silêncio (margem)',
    printDigits: 'Imprimir os dígitos abaixo das barras',
    encoding: 'Codificando…',
    generate: 'Gerar código de barras',
    encodeFailed: 'Não foi possível codificar este valor.',
    encodedAs: 'Codificado como {value}.',
    imageAlt: 'Código de barras {format} codificando {value}',
    downloadPng: 'Baixar PNG',
    downloadSvg: 'Baixar SVG',
    crossLink:
      'Precisa de um QR code? Use o {qr} — ele tem modelos para Wi-Fi, vCard e e-mail. Para conferir um código que você criou, o {scanner} faz a leitura de volta.',
    qrLink: 'gerador de QR code',
    scannerLink: 'leitor de código de barras',
    hint_EAN13: '13 dígitos (ou 12 — nós adicionamos o dígito verificador)',
    hint_EAN8: '8 dígitos (ou 7 — nós adicionamos o dígito verificador)',
    hint_UPCA: '12 dígitos (ou 11 — nós adicionamos o dígito verificador)',
    hint_ITF14: '14 dígitos (ou 13 — nós adicionamos o dígito verificador)',
    hint_ITF: 'dígitos, em quantidade par',
    hint_Code128: 'qualquer texto ASCII',
    hint_Code39: 'A–Z, 0–9, espaço e - . $ / + %',
    hint_DataMatrix: 'qualquer texto',
    hint_PDF417: 'qualquer texto',
    hint_Aztec: 'qualquer texto',
    error_enterData: 'Informe os dados a codificar.',
    error_digitsOnly: '{format} aceita apenas dígitos — sem letras nem pontuação.',
    error_digitCount:
      '{format} precisa de {total} dígitos (ou {body} e calculamos o último). Você digitou {entered}.',
    error_checkDigitWrong:
      'O dígito verificador está errado: {body} termina em {want}, não em {got}. Os leitores rejeitam este código.',
    error_itfDigitsOnly: 'ITF aceita apenas dígitos.',
    error_itfEvenCount:
      'ITF codifica os dígitos em pares, então precisa de uma quantidade par. Você digitou {entered}.',
    error_code39Alphabet: 'Code 39 aceita apenas A–Z, 0–9, espaço e - . $ / + % — nada mais.',
    error_code128Latin1:
      'Code 128 não consegue codificar "{char}". Use Data Matrix, PDF417 ou Aztec para texto fora do Latin-1.',
    error_checkDigitDigitsOnly: 'Dígitos verificadores só são definidos para cadeias de dígitos',
    error_unknownFormat: 'Formato de código de barras desconhecido: {id}',
    note_checkDigitAdded: 'Dígito verificador {check} adicionado.',
    note_code39Uppercased: 'Code 39 não tem minúsculas; o texto foi convertido para maiúsculas.',
  },
};
