import type { LocalizedStrings } from '@anytools/ui';

const EN = {
  title: 'Add Page Numbers to PDF',
  dropLabel: 'The PDF to number. Page count and page order are not changed.',
  couldNotReadPdf: 'Could not read PDF',
  failed: 'Could not add page numbers',
  pageCountOne: '{n} page.',
  pageCountMany: '{n} pages.',
  position: 'Position',
  pos_topLeft: 'Top left',
  pos_topCenter: 'Top centre',
  pos_topRight: 'Top right',
  pos_bottomLeft: 'Bottom left',
  pos_bottomCenter: 'Bottom centre',
  pos_bottomRight: 'Bottom right',
  format: 'Format',
  startAt: 'Start numbering at',
  pagesToNumber: 'Pages to number',
  // {n} is the page count of the loaded PDF.
  rangePlaceholderAll: 'all — or e.g. 2-{n}',
  rangePlaceholder: 'all — or e.g. 2-10, 14',
  fontSize: 'Font size',
  margin: 'Distance from the edge',
  fontNote:
    "Numbers are drawn in Helvetica, the font every PDF reader already has — nothing is embedded, so the file barely grows. Latin characters only: the built-in font cannot draw Vietnamese tone marks, CJK, Greek, Cyrillic or Arabic. Pages your scanner saved sideways are handled — the number follows the page's own rotation.",
  numbering: 'Numbering…',
  addNumbers: 'Add page numbers',
  previewFirst: 'Preview of the first label:',
  numberedOne: 'Numbered {n} of {total} page',
  numberedMany: 'Numbered {n} of {total} pages',
  labels: 'First label "{first}", last label "{last}".',
  download: 'Download numbered.pdf',
};

export const STRINGS: LocalizedStrings<typeof EN> = {
  en: EN,
  vi: {
    title: 'Đánh số trang PDF',
    dropLabel: 'PDF cần đánh số. Số trang và thứ tự trang không thay đổi.',
    couldNotReadPdf: 'Không đọc được PDF',
    failed: 'Không thể đánh số trang',
    pageCountOne: '{n} trang.',
    pageCountMany: '{n} trang.',
    position: 'Vị trí',
    pos_topLeft: 'Trên, bên trái',
    pos_topCenter: 'Trên, giữa',
    pos_topRight: 'Trên, bên phải',
    pos_bottomLeft: 'Dưới, bên trái',
    pos_bottomCenter: 'Dưới, giữa',
    pos_bottomRight: 'Dưới, bên phải',
    format: 'Định dạng',
    startAt: 'Bắt đầu đánh số từ',
    pagesToNumber: 'Các trang cần đánh số',
    rangePlaceholderAll: 'tất cả — hoặc vd. 2-{n}',
    rangePlaceholder: 'tất cả — hoặc vd. 2-10, 14',
    fontSize: 'Cỡ chữ',
    margin: 'Khoảng cách tới mép',
    fontNote:
      'Số trang được vẽ bằng Helvetica, phông có sẵn trong mọi trình đọc PDF — không nhúng gì thêm nên tệp gần như không lớn lên. Chỉ hỗ trợ ký tự Latin: phông tích hợp không vẽ được dấu tiếng Việt, CJK, Hy Lạp, Kirin hay Ả Rập. Trang bị máy quét lưu xoay ngang vẫn được xử lý — số trang đi theo hướng xoay của chính trang đó.',
    numbering: 'Đang đánh số…',
    addNumbers: 'Đánh số trang',
    previewFirst: 'Xem trước nhãn đầu tiên:',
    numberedOne: 'Đã đánh số {n}/{total} trang',
    numberedMany: 'Đã đánh số {n}/{total} trang',
    labels: 'Nhãn đầu "{first}", nhãn cuối "{last}".',
    download: 'Tải numbered.pdf',
  },
  es: {
    title: 'Añadir números de página al PDF',
    dropLabel: 'El PDF a numerar. Ni el número de páginas ni su orden cambian.',
    couldNotReadPdf: 'No se pudo leer el PDF',
    failed: 'No se pudieron añadir los números de página',
    pageCountOne: '{n} página.',
    pageCountMany: '{n} páginas.',
    position: 'Posición',
    pos_topLeft: 'Arriba a la izquierda',
    pos_topCenter: 'Arriba al centro',
    pos_topRight: 'Arriba a la derecha',
    pos_bottomLeft: 'Abajo a la izquierda',
    pos_bottomCenter: 'Abajo al centro',
    pos_bottomRight: 'Abajo a la derecha',
    format: 'Formato',
    startAt: 'Empezar a numerar en',
    pagesToNumber: 'Páginas a numerar',
    rangePlaceholderAll: 'todas — o p. ej. 2-{n}',
    rangePlaceholder: 'todas — o p. ej. 2-10, 14',
    fontSize: 'Tamaño de fuente',
    margin: 'Distancia al borde',
    fontNote:
      'Los números se dibujan en Helvetica, la fuente que ya tiene todo lector de PDF — no se incrusta nada, así que el archivo apenas crece. Solo caracteres latinos: la fuente integrada no puede dibujar tonos vietnamitas, CJK, griego, cirílico ni árabe. Las páginas que tu escáner guardó de lado se manejan — el número sigue la rotación de la propia página.',
    numbering: 'Numerando…',
    addNumbers: 'Añadir números de página',
    previewFirst: 'Vista previa de la primera etiqueta:',
    numberedOne: 'Numerada {n} de {total} página',
    numberedMany: 'Numeradas {n} de {total} páginas',
    labels: 'Primera etiqueta "{first}", última etiqueta "{last}".',
    download: 'Descargar numbered.pdf',
  },
  pt: {
    title: 'Adicionar números de página ao PDF',
    dropLabel: 'O PDF a numerar. A quantidade e a ordem das páginas não mudam.',
    couldNotReadPdf: 'Não foi possível ler o PDF',
    failed: 'Não foi possível adicionar os números de página',
    pageCountOne: '{n} página.',
    pageCountMany: '{n} páginas.',
    position: 'Posição',
    pos_topLeft: 'Superior esquerdo',
    pos_topCenter: 'Superior central',
    pos_topRight: 'Superior direito',
    pos_bottomLeft: 'Inferior esquerdo',
    pos_bottomCenter: 'Inferior central',
    pos_bottomRight: 'Inferior direito',
    format: 'Formato',
    startAt: 'Começar a numerar em',
    pagesToNumber: 'Páginas a numerar',
    rangePlaceholderAll: 'todas — ou ex. 2-{n}',
    rangePlaceholder: 'todas — ou ex. 2-10, 14',
    fontSize: 'Tamanho da fonte',
    margin: 'Distância da borda',
    fontNote:
      'Os números são desenhados em Helvetica, a fonte que todo leitor de PDF já tem — nada é incorporado, então o arquivo quase não cresce. Apenas caracteres latinos: a fonte embutida não desenha acentos tonais vietnamitas, CJK, grego, cirílico nem árabe. Páginas que o scanner salvou de lado são tratadas — o número segue a rotação da própria página.',
    numbering: 'Numerando…',
    addNumbers: 'Adicionar números de página',
    previewFirst: 'Prévia do primeiro rótulo:',
    numberedOne: 'Numerada {n} de {total} página',
    numberedMany: 'Numeradas {n} de {total} páginas',
    labels: 'Primeiro rótulo "{first}", último rótulo "{last}".',
    download: 'Baixar numbered.pdf',
  },
};
