import type { LocalizedStrings } from '@anytools/ui';

const EN = {
  title: 'BIP-39 Mnemonic Tool',
  warningBanner:
    'Do not use a phrase generated on any website — this one included — for a wallet that holds real funds. This tool is for learning and testing only; a browser tab is not a secure place to generate or handle a seed phrase that protects real money.',
  tabGenerate: 'Generate',
  tabValidate: 'Validate',
  tabConvert: 'Convert',
  tabSeed: 'Seed',
  wordCountLabel: 'Word count',
  generateButton: 'Generate phrase',
  generating: 'Generating…',
  generateFailed: 'Could not generate a phrase.',
  generatedPhraseLabel: 'Mnemonic phrase',
  validateLabel: 'Mnemonic phrase to check',
  validateButton: 'Check',
  validateFailed: 'Could not check this phrase.',
  validResult: 'Valid — checksum matches (English wordlist)',
  invalidResult: 'Invalid — not a real BIP-39 phrase, or the checksum does not match',
  mnemonicToEntropyTitle: 'Mnemonic → entropy',
  entropyToMnemonicTitle: 'Entropy → mnemonic',
  mnemonicInputLabel: 'Mnemonic phrase',
  entropyOutputLabel: 'Entropy (hex)',
  entropyInputLabel: 'Entropy (hex — 32/40/48/56/64 hex chars)',
  mnemonicOutputLabel: 'Mnemonic phrase',
  convertButton: 'Convert',
  convertFailed: 'Could not convert.',
  seedMnemonicLabel: 'Mnemonic phrase',
  seedPassphraseLabel: 'Passphrase (optional)',
  seedPassphraseHint:
    'BIP-39 calls this the "25th word" — a different passphrase with the same mnemonic derives a completely different seed.',
  seedButton: 'Derive seed',
  seedFailed: 'Could not derive a seed.',
  seedOutputLabel: 'Seed (hex, 64 bytes)',
  privacy:
    'Generated and checked entirely in your browser with crypto.getRandomValues — nothing is sent anywhere. English wordlist only.',
  error_invalidMnemonic: 'Invalid mnemonic: {detail}',
  error_invalidEntropyHex: 'Entropy must be an even-length hex string.',
  // {bytes} is the byte count the pasted hex string decoded to.
  error_invalidEntropyLength:
    'Entropy must be 16, 20, 24, 28 or 32 bytes (128–256 bits); got {bytes}.',
};

export const STRINGS: LocalizedStrings<typeof EN> = {
  en: EN,
  vi: {
    title: 'Công cụ cụm từ BIP-39',
    warningBanner:
      'Đừng dùng cụm từ sinh ra từ bất kỳ trang web nào — kể cả trang này — cho ví chứa tiền thật. Công cụ này chỉ để học và kiểm tra; tab trình duyệt không phải nơi an toàn để sinh hay xử lý seed phrase bảo vệ tiền thật.',
    tabGenerate: 'Sinh',
    tabValidate: 'Kiểm tra',
    tabConvert: 'Đổi',
    tabSeed: 'Seed',
    wordCountLabel: 'Số từ',
    generateButton: 'Sinh cụm từ',
    generating: 'Đang sinh…',
    generateFailed: 'Không sinh được cụm từ.',
    generatedPhraseLabel: 'Cụm từ',
    validateLabel: 'Cụm từ cần kiểm tra',
    validateButton: 'Kiểm tra',
    validateFailed: 'Không kiểm tra được cụm từ này.',
    validResult: 'Hợp lệ — checksum khớp (wordlist tiếng Anh)',
    invalidResult: 'Không hợp lệ — không phải cụm BIP-39 thật, hoặc checksum sai',
    mnemonicToEntropyTitle: 'Cụm từ → entropy',
    entropyToMnemonicTitle: 'Entropy → cụm từ',
    mnemonicInputLabel: 'Cụm từ',
    entropyOutputLabel: 'Entropy (hex)',
    entropyInputLabel: 'Entropy (hex — 32/40/48/56/64 ký tự hex)',
    mnemonicOutputLabel: 'Cụm từ',
    convertButton: 'Đổi',
    convertFailed: 'Không đổi được.',
    seedMnemonicLabel: 'Cụm từ',
    seedPassphraseLabel: 'Passphrase (tuỳ chọn)',
    seedPassphraseHint:
      'BIP-39 gọi đây là "từ thứ 25" — cùng cụm từ nhưng khác passphrase sẽ dẫn ra seed hoàn toàn khác.',
    seedButton: 'Dẫn ra seed',
    seedFailed: 'Không dẫn được seed.',
    seedOutputLabel: 'Seed (hex, 64 byte)',
    privacy:
      'Sinh và kiểm tra hoàn toàn trong trình duyệt bằng crypto.getRandomValues — không gửi đi đâu cả. Chỉ hỗ trợ wordlist tiếng Anh.',
    error_invalidMnemonic: 'Cụm từ không hợp lệ: {detail}',
    error_invalidEntropyHex: 'Entropy phải là chuỗi hex có độ dài chẵn.',
    error_invalidEntropyLength:
      'Entropy phải là 16, 20, 24, 28 hoặc 32 byte (128–256 bit); nhận được {bytes}.',
  },
  es: {
    title: 'Herramienta de frase mnemónica BIP-39',
    warningBanner:
      'No uses una frase generada en ningún sitio web — este incluido — para una wallet con fondos reales. Esta herramienta es solo para aprender y probar; una pestaña del navegador no es un lugar seguro para generar o manejar una seed phrase que protege dinero real.',
    tabGenerate: 'Generar',
    tabValidate: 'Validar',
    tabConvert: 'Convertir',
    tabSeed: 'Seed',
    wordCountLabel: 'Cantidad de palabras',
    generateButton: 'Generar frase',
    generating: 'Generando…',
    generateFailed: 'No se pudo generar una frase.',
    generatedPhraseLabel: 'Frase mnemónica',
    validateLabel: 'Frase mnemónica a comprobar',
    validateButton: 'Comprobar',
    validateFailed: 'No se pudo comprobar esta frase.',
    validResult: 'Válida — el checksum coincide (wordlist en inglés)',
    invalidResult: 'Inválida — no es una frase BIP-39 real, o el checksum no coincide',
    mnemonicToEntropyTitle: 'Frase → entropía',
    entropyToMnemonicTitle: 'Entropía → frase',
    mnemonicInputLabel: 'Frase mnemónica',
    entropyOutputLabel: 'Entropía (hex)',
    entropyInputLabel: 'Entropía (hex — 32/40/48/56/64 caracteres hex)',
    mnemonicOutputLabel: 'Frase mnemónica',
    convertButton: 'Convertir',
    convertFailed: 'No se pudo convertir.',
    seedMnemonicLabel: 'Frase mnemónica',
    seedPassphraseLabel: 'Frase de paso (opcional)',
    seedPassphraseHint:
      'BIP-39 llama a esto la "palabra 25" — la misma frase con una frase de paso distinta deriva un seed completamente diferente.',
    seedButton: 'Derivar seed',
    seedFailed: 'No se pudo derivar el seed.',
    seedOutputLabel: 'Seed (hex, 64 bytes)',
    privacy:
      'Generado y comprobado enteramente en tu navegador con crypto.getRandomValues — nada se envía a ningún lado. Solo wordlist en inglés.',
    error_invalidMnemonic: 'Frase inválida: {detail}',
    error_invalidEntropyHex: 'La entropía debe ser una cadena hex de longitud par.',
    error_invalidEntropyLength:
      'La entropía debe ser 16, 20, 24, 28 o 32 bytes (128–256 bits); se recibieron {bytes}.',
  },
  pt: {
    title: 'Ferramenta de frase mnemônica BIP-39',
    warningBanner:
      'Não use uma frase gerada em nenhum site — este incluído — para uma carteira com fundos reais. Esta ferramenta é só para aprender e testar; uma aba do navegador não é um lugar seguro para gerar ou manusear uma seed phrase que protege dinheiro real.',
    tabGenerate: 'Gerar',
    tabValidate: 'Validar',
    tabConvert: 'Converter',
    tabSeed: 'Seed',
    wordCountLabel: 'Número de palavras',
    generateButton: 'Gerar frase',
    generating: 'Gerando…',
    generateFailed: 'Não foi possível gerar uma frase.',
    generatedPhraseLabel: 'Frase mnemônica',
    validateLabel: 'Frase mnemônica para checar',
    validateButton: 'Checar',
    validateFailed: 'Não foi possível checar esta frase.',
    validResult: 'Válida — o checksum confere (wordlist em inglês)',
    invalidResult: 'Inválida — não é uma frase BIP-39 real, ou o checksum não confere',
    mnemonicToEntropyTitle: 'Frase → entropia',
    entropyToMnemonicTitle: 'Entropia → frase',
    mnemonicInputLabel: 'Frase mnemônica',
    entropyOutputLabel: 'Entropia (hex)',
    entropyInputLabel: 'Entropia (hex — 32/40/48/56/64 caracteres hex)',
    mnemonicOutputLabel: 'Frase mnemônica',
    convertButton: 'Converter',
    convertFailed: 'Não foi possível converter.',
    seedMnemonicLabel: 'Frase mnemônica',
    seedPassphraseLabel: 'Frase secreta (opcional)',
    seedPassphraseHint:
      'O BIP-39 chama isso de "25ª palavra" — a mesma frase com uma frase secreta diferente deriva um seed completamente diferente.',
    seedButton: 'Derivar seed',
    seedFailed: 'Não foi possível derivar o seed.',
    seedOutputLabel: 'Seed (hex, 64 bytes)',
    privacy:
      'Gerado e checado totalmente no seu navegador com crypto.getRandomValues — nada é enviado. Apenas wordlist em inglês.',
    error_invalidMnemonic: 'Frase inválida: {detail}',
    error_invalidEntropyHex: 'A entropia deve ser uma string hex de comprimento par.',
    error_invalidEntropyLength:
      'A entropia deve ter 16, 20, 24, 28 ou 32 bytes (128–256 bits); recebido {bytes}.',
  },
};
