import type { LocalizedStrings } from '@anytools/ui';

const EN = {
  title: 'Percentage Calculator',
  description: 'Tip, discount, tax, grade, growth — three percentage modes.',
  mode: 'Mode',
  modePercentOf: 'X% of Y',
  modeWhatPercent: 'X = ?% of Y',
  modeChange: '% change',
  percentageX: 'Percentage (X)',
  partX: 'Part (X)',
  oldValueX: 'Old value (X)',
  ofValueY: 'Of value (Y)',
  wholeY: 'Whole (Y)',
  newValueY: 'New value (Y)',
  resultPercentOf: '{a}% of {b}',
  resultWhatPercent: '{a} is X% of {b}',
  resultChange: 'Change from {a} to {b}',
};

export const STRINGS: LocalizedStrings<typeof EN> = {
  en: EN,
  vi: {
    title: 'Tính phần trăm',
    description: 'Tiền tip, giảm giá, thuế, điểm số, tăng trưởng — ba chế độ phần trăm.',
    mode: 'Chế độ',
    modePercentOf: 'X% của Y',
    modeWhatPercent: 'X = ?% của Y',
    modeChange: '% thay đổi',
    percentageX: 'Phần trăm (X)',
    partX: 'Phần (X)',
    oldValueX: 'Giá trị cũ (X)',
    ofValueY: 'Của giá trị (Y)',
    wholeY: 'Tổng (Y)',
    newValueY: 'Giá trị mới (Y)',
    resultPercentOf: '{a}% của {b}',
    resultWhatPercent: '{a} là X% của {b}',
    resultChange: 'Thay đổi từ {a} sang {b}',
  },
  es: {
    title: 'Calculadora de porcentajes',
    description: 'Propina, descuento, impuesto, nota, crecimiento: tres modos de porcentaje.',
    mode: 'Modo',
    modePercentOf: 'X% de Y',
    modeWhatPercent: 'X = ¿?% de Y',
    modeChange: '% de cambio',
    percentageX: 'Porcentaje (X)',
    partX: 'Parte (X)',
    oldValueX: 'Valor anterior (X)',
    ofValueY: 'Del valor (Y)',
    wholeY: 'Total (Y)',
    newValueY: 'Valor nuevo (Y)',
    resultPercentOf: '{a}% de {b}',
    resultWhatPercent: '{a} es el X% de {b}',
    resultChange: 'Cambio de {a} a {b}',
  },
  pt: {
    title: 'Calculadora de porcentagem',
    description: 'Gorjeta, desconto, imposto, nota, crescimento: três modos de porcentagem.',
    mode: 'Modo',
    modePercentOf: 'X% de Y',
    modeWhatPercent: 'X = ?% de Y',
    modeChange: '% de variação',
    percentageX: 'Porcentagem (X)',
    partX: 'Parte (X)',
    oldValueX: 'Valor antigo (X)',
    ofValueY: 'Do valor (Y)',
    wholeY: 'Total (Y)',
    newValueY: 'Valor novo (Y)',
    resultPercentOf: '{a}% de {b}',
    resultWhatPercent: '{a} é X% de {b}',
    resultChange: 'Variação de {a} para {b}',
  },
};
