import type { LocalizedStrings } from '@anytools/ui';

const EN = {
  title: 'Resize Image',
  dropLabel: 'Image to resize',
  failed: 'Resize failed',
  howToSize: 'How to size it',
  mode_fit: 'Fit inside a box (keeps the aspect ratio)',
  mode_percent: 'Percentage of the original',
  mode_exact: 'Exact width and height',
  longestSide: 'Longest side (px)',
  scale: 'Scale: {n}%',
  enlargeNote: 'Above 100% the image is enlarged. Nothing new is added — it will look softer.',
  width: 'Width (px)',
  height: 'Height (px)',
  outputFormat: 'Output format',
  resizing: 'Resizing…',
  resize: 'Resize',
  cappedNote:
    'the source was above what a canvas can hold, so the output is capped at 16.7 megapixels',
  resultAlt: 'Resized',
  download: 'Download {name}',
};

export const STRINGS: LocalizedStrings<typeof EN> = {
  en: EN,
  vi: {
    title: 'Đổi cỡ ảnh',
    dropLabel: 'Ảnh cần đổi cỡ',
    failed: 'Đổi cỡ thất bại',
    howToSize: 'Cách chọn kích thước',
    mode_fit: 'Vừa trong một khung (giữ tỷ lệ)',
    mode_percent: 'Phần trăm so với ảnh gốc',
    mode_exact: 'Chiều rộng và chiều cao chính xác',
    longestSide: 'Cạnh dài nhất (px)',
    scale: 'Tỷ lệ: {n}%',
    enlargeNote: 'Trên 100% ảnh sẽ được phóng to. Không có chi tiết mới — ảnh sẽ trông mềm hơn.',
    width: 'Chiều rộng (px)',
    height: 'Chiều cao (px)',
    outputFormat: 'Định dạng đầu ra',
    resizing: 'Đang đổi cỡ…',
    resize: 'Đổi cỡ',
    cappedNote:
      'ảnh gốc vượt quá kích thước canvas có thể chứa nên đầu ra bị giới hạn ở 16,7 megapixel',
    resultAlt: 'Ảnh đã đổi cỡ',
    download: 'Tải {name}',
  },
  es: {
    title: 'Redimensionar imagen',
    dropLabel: 'Imagen a redimensionar',
    failed: 'El redimensionado falló',
    howToSize: 'Cómo dimensionarla',
    mode_fit: 'Ajustar dentro de un cuadro (mantiene la proporción)',
    mode_percent: 'Porcentaje del original',
    mode_exact: 'Ancho y alto exactos',
    longestSide: 'Lado más largo (px)',
    scale: 'Escala: {n}%',
    enlargeNote:
      'Por encima del 100% la imagen se amplía. No se añade nada nuevo — se verá más suave.',
    width: 'Ancho (px)',
    height: 'Alto (px)',
    outputFormat: 'Formato de salida',
    resizing: 'Redimensionando…',
    resize: 'Redimensionar',
    cappedNote:
      'el original superaba lo que un canvas puede contener, así que la salida se limita a 16,7 megapíxeles',
    resultAlt: 'Redimensionada',
    download: 'Descargar {name}',
  },
  pt: {
    title: 'Redimensionar imagem',
    dropLabel: 'Imagem a redimensionar',
    failed: 'O redimensionamento falhou',
    howToSize: 'Como dimensionar',
    mode_fit: 'Caber em uma caixa (mantém a proporção)',
    mode_percent: 'Porcentagem do original',
    mode_exact: 'Largura e altura exatas',
    longestSide: 'Lado mais longo (px)',
    scale: 'Escala: {n}%',
    enlargeNote:
      'Acima de 100% a imagem é ampliada. Nada novo é adicionado — ela ficará mais suave.',
    width: 'Largura (px)',
    height: 'Altura (px)',
    outputFormat: 'Formato de saída',
    resizing: 'Redimensionando…',
    resize: 'Redimensionar',
    cappedNote:
      'o original passava do que um canvas consegue conter, então a saída é limitada a 16,7 megapixels',
    resultAlt: 'Redimensionada',
    download: 'Baixar {name}',
  },
};
