import type { LocalizedStrings } from '@anytools/ui';

const EN = {
  title: 'Regex Tester',
  pattern: 'Pattern',
  patternPlaceholder: 'e.g. (?<year>\\d{4})-(?<month>\\d{2})',
  flags: 'Flags:',
  // Flag letters (g, i, m, s, u, y) stay as-is in the UI; these are the descriptions.
  flagGlobal: 'global',
  flagIgnoreCase: 'ignore case',
  flagMultiline: '^/$ per line',
  flagDotAll: 'dot matches newline',
  flagUnicode: 'unicode',
  flagSticky: 'sticky',
  test: 'Test',
  replace: 'Replace',
  testText: 'Test text',
  replacementPlaceholder: 'Replacement (use $1, $2, $<name> for groups)',
  running: 'Running…',
  capped: 'Text capped at {n} chars',
  charCount: '{n} / {max} chars',
  matchOne: '1 match',
  matchMany: '{n} matches',
  groups: 'groups:',
  named: 'named:',
  showingFirst: 'Showing first 50 of {n} matches.',
  afterReplace: 'After replace',
  // {run} is the Run button label in <strong>; {n} the character cap.
  footnote:
    'Click {run} to execute — avoids re-running on every keystroke. Text is capped at {n} chars and execution at 1 second to prevent catastrophic backtracking from freezing the tab. Runs in your browser.',
};

export const STRINGS: LocalizedStrings<typeof EN> = {
  en: EN,
  vi: {
    title: 'Kiểm tra Regex',
    pattern: 'Mẫu',
    patternPlaceholder: 'vd. (?<year>\\d{4})-(?<month>\\d{2})',
    flags: 'Cờ:',
    flagGlobal: 'toàn bộ',
    flagIgnoreCase: 'bỏ qua hoa/thường',
    flagMultiline: '^/$ theo từng dòng',
    flagDotAll: 'dấu chấm khớp cả xuống dòng',
    flagUnicode: 'unicode',
    flagSticky: 'sticky',
    test: 'Kiểm tra',
    replace: 'Thay thế',
    testText: 'Văn bản kiểm tra',
    replacementPlaceholder: 'Chuỗi thay thế (dùng $1, $2, $<name> cho nhóm)',
    running: 'Đang chạy…',
    capped: 'Văn bản bị cắt còn {n} ký tự',
    charCount: '{n} / {max} ký tự',
    matchOne: '1 kết quả khớp',
    matchMany: '{n} kết quả khớp',
    groups: 'nhóm:',
    named: 'nhóm đặt tên:',
    showingFirst: 'Hiển thị 50 trong {n} kết quả khớp.',
    afterReplace: 'Sau khi thay thế',
    footnote:
      'Bấm {run} để thực thi — tránh chạy lại sau mỗi lần gõ. Văn bản giới hạn {n} ký tự và thời gian chạy 1 giây để backtracking bùng nổ không làm treo tab. Chạy trong trình duyệt của bạn.',
  },
  es: {
    title: 'Probador de Regex',
    pattern: 'Patrón',
    patternPlaceholder: 'p. ej. (?<year>\\d{4})-(?<month>\\d{2})',
    flags: 'Banderas:',
    flagGlobal: 'global',
    flagIgnoreCase: 'ignorar mayúsculas',
    flagMultiline: '^/$ por línea',
    flagDotAll: 'el punto coincide con salto de línea',
    flagUnicode: 'unicode',
    flagSticky: 'sticky',
    test: 'Probar',
    replace: 'Reemplazar',
    testText: 'Texto de prueba',
    replacementPlaceholder: 'Reemplazo (usa $1, $2, $<name> para los grupos)',
    running: 'Ejecutando…',
    capped: 'Texto limitado a {n} caracteres',
    charCount: '{n} / {max} caracteres',
    matchOne: '1 coincidencia',
    matchMany: '{n} coincidencias',
    groups: 'grupos:',
    named: 'con nombre:',
    showingFirst: 'Mostrando las primeras 50 de {n} coincidencias.',
    afterReplace: 'Tras el reemplazo',
    footnote:
      'Pulsa {run} para ejecutar — evita volver a ejecutar con cada tecla. El texto se limita a {n} caracteres y la ejecución a 1 segundo para que el backtracking catastrófico no congele la pestaña. Se ejecuta en tu navegador.',
  },
  pt: {
    title: 'Testador de Regex',
    pattern: 'Padrão',
    patternPlaceholder: 'ex.: (?<year>\\d{4})-(?<month>\\d{2})',
    flags: 'Flags:',
    flagGlobal: 'global',
    flagIgnoreCase: 'ignorar maiúsculas',
    flagMultiline: '^/$ por linha',
    flagDotAll: 'ponto casa com quebra de linha',
    flagUnicode: 'unicode',
    flagSticky: 'sticky',
    test: 'Testar',
    replace: 'Substituir',
    testText: 'Texto de teste',
    replacementPlaceholder: 'Substituição (use $1, $2, $<name> para os grupos)',
    running: 'Executando…',
    capped: 'Texto limitado a {n} caracteres',
    charCount: '{n} / {max} caracteres',
    matchOne: '1 correspondência',
    matchMany: '{n} correspondências',
    groups: 'grupos:',
    named: 'nomeados:',
    showingFirst: 'Mostrando as primeiras 50 de {n} correspondências.',
    afterReplace: 'Após a substituição',
    footnote:
      'Clique em {run} para executar — evita reexecutar a cada tecla. O texto é limitado a {n} caracteres e a execução a 1 segundo para que o backtracking catastrófico não trave a aba. Roda no seu navegador.',
  },
};
