import type { LocalizedStrings } from '@anytools/ui';

const EN = {
  title: 'Calorie & TDEE Calculator',
  description: 'BMR × activity factor × goal adjustment.',
  sexLabel: 'Sex (biological)',
  male: 'Male',
  female: 'Female',
  age: 'Age',
  unitYears: 'yrs',
  activityLevel: 'Activity level',
  activity_sedentary: 'Sedentary (desk job)',
  activity_light: 'Light (1-3×/week)',
  activity_moderate: 'Moderate (3-5×/week)',
  activity_active: 'Active (6-7×/week)',
  activity_athlete: 'Athlete (2× daily)',
  tableTitle: 'Daily Calorie Targets',
  row_bmr: 'BMR (rest)',
  row_tdee: 'Maintenance (TDEE)',
  row_mildLoss: 'Mild weight loss (-250)',
  row_loss: 'Weight loss (-500)',
  row_mildGain: 'Mild weight gain (+250)',
  row_gain: 'Weight gain (+500)',
  disclaimer:
    'Estimation only. Real metabolic rates vary ±10%. Sustained large deficits (>500 cal/day) trigger metabolic adaptation; bodies push back.',
};

export const STRINGS: LocalizedStrings<typeof EN> = {
  en: EN,
  vi: {
    title: 'Máy tính calo & TDEE',
    description: 'BMR × hệ số vận động × điều chỉnh theo mục tiêu.',
    sexLabel: 'Giới tính (sinh học)',
    male: 'Nam',
    female: 'Nữ',
    age: 'Tuổi',
    unitYears: 'tuổi',
    activityLevel: 'Mức vận động',
    activity_sedentary: 'Ít vận động (ngồi bàn giấy)',
    activity_light: 'Nhẹ (1-3 buổi/tuần)',
    activity_moderate: 'Vừa (3-5 buổi/tuần)',
    activity_active: 'Nhiều (6-7 buổi/tuần)',
    activity_athlete: 'Vận động viên (2 buổi/ngày)',
    tableTitle: 'Mục tiêu calo mỗi ngày',
    row_bmr: 'BMR (nghỉ ngơi)',
    row_tdee: 'Duy trì (TDEE)',
    row_mildLoss: 'Giảm cân nhẹ (-250)',
    row_loss: 'Giảm cân (-500)',
    row_mildGain: 'Tăng cân nhẹ (+250)',
    row_gain: 'Tăng cân (+500)',
    disclaimer:
      'Chỉ mang tính ước lượng. Tốc độ trao đổi chất thực tế lệch ±10%. Thâm hụt lớn kéo dài (>500 cal/ngày) gây thích nghi trao đổi chất; cơ thể sẽ phản kháng.',
  },
  es: {
    title: 'Calculadora de calorías y TDEE',
    description: 'TMB × factor de actividad × ajuste según objetivo.',
    sexLabel: 'Sexo (biológico)',
    male: 'Hombre',
    female: 'Mujer',
    age: 'Edad',
    unitYears: 'años',
    activityLevel: 'Nivel de actividad',
    activity_sedentary: 'Sedentario (trabajo de oficina)',
    activity_light: 'Ligero (1-3×/semana)',
    activity_moderate: 'Moderado (3-5×/semana)',
    activity_active: 'Activo (6-7×/semana)',
    activity_athlete: 'Atleta (2× al día)',
    tableTitle: 'Objetivos diarios de calorías',
    row_bmr: 'TMB (reposo)',
    row_tdee: 'Mantenimiento (TDEE)',
    row_mildLoss: 'Pérdida de peso leve (-250)',
    row_loss: 'Pérdida de peso (-500)',
    row_mildGain: 'Aumento de peso leve (+250)',
    row_gain: 'Aumento de peso (+500)',
    disclaimer:
      'Solo estimación. Las tasas metabólicas reales varían ±10 %. Los déficits grandes sostenidos (>500 cal/día) provocan adaptación metabólica; el cuerpo se resiste.',
  },
  pt: {
    title: 'Calculadora de calorias e TDEE',
    description: 'TMB × fator de atividade × ajuste por objetivo.',
    sexLabel: 'Sexo (biológico)',
    male: 'Masculino',
    female: 'Feminino',
    age: 'Idade',
    unitYears: 'anos',
    activityLevel: 'Nível de atividade',
    activity_sedentary: 'Sedentário (trabalho de escritório)',
    activity_light: 'Leve (1-3×/semana)',
    activity_moderate: 'Moderado (3-5×/semana)',
    activity_active: 'Ativo (6-7×/semana)',
    activity_athlete: 'Atleta (2× por dia)',
    tableTitle: 'Metas diárias de calorias',
    row_bmr: 'TMB (repouso)',
    row_tdee: 'Manutenção (TDEE)',
    row_mildLoss: 'Perda de peso leve (-250)',
    row_loss: 'Perda de peso (-500)',
    row_mildGain: 'Ganho de peso leve (+250)',
    row_gain: 'Ganho de peso (+500)',
    disclaimer:
      'Apenas estimativa. As taxas metabólicas reais variam ±10%. Déficits grandes e prolongados (>500 cal/dia) causam adaptação metabólica; o corpo reage.',
  },
};
