import type { LocalizedStrings } from '@anytools/ui';

const EN = {
  title: 'Discord Timestamp Generator',
  dateTime: 'Date and time',
  timezone: 'This is local time in',
  now: 'Now',
  enterHint: 'Pick a date and time to generate the codes.',
  invalidHint: 'That date and time could not be parsed.',
  error_invalidDateTime: 'Pick a valid date and time.',
  code: 'Code',
  copyAll: 'Copy all 7',
  yourPreview: 'How this looks to you right now',
  otherZonesPreview: 'How the exact same code looks elsewhere',
  style_t: 'Short time',
  style_T: 'Long time',
  style_d: 'Short date',
  style_D: 'Long date',
  style_f: 'Short date/time',
  style_F: 'Long date/time',
  style_R: 'Relative',
  detectedZoneNote: 'Detected from your device: {zone}',
};

export const STRINGS: LocalizedStrings<typeof EN> = {
  en: EN,
  vi: {
    title: 'Trình tạo Timestamp Discord',
    dateTime: 'Ngày và giờ',
    timezone: 'Đây là giờ địa phương tại',
    now: 'Bây giờ',
    enterHint: 'Chọn ngày giờ để tạo các mã.',
    invalidHint: 'Không đọc được ngày giờ này.',
    error_invalidDateTime: 'Hãy chọn ngày giờ hợp lệ.',
    code: 'Mã',
    copyAll: 'Copy cả 7 mã',
    yourPreview: 'Hiện tại trông thế nào với bạn',
    otherZonesPreview: 'Đúng mã đó trông thế nào ở nơi khác',
    style_t: 'Giờ ngắn',
    style_T: 'Giờ dài',
    style_d: 'Ngày ngắn',
    style_D: 'Ngày dài',
    style_f: 'Ngày/giờ ngắn',
    style_F: 'Ngày/giờ dài',
    style_R: 'Tương đối',
    detectedZoneNote: 'Nhận diện từ thiết bị của bạn: {zone}',
  },
  es: {
    title: 'Generador de marcas de tiempo de Discord',
    dateTime: 'Fecha y hora',
    timezone: 'Esto es hora local en',
    now: 'Ahora',
    enterHint: 'Elige una fecha y hora para generar los códigos.',
    invalidHint: 'No se pudo interpretar esa fecha y hora.',
    error_invalidDateTime: 'Elige una fecha y hora válidas.',
    code: 'Código',
    copyAll: 'Copiar los 7',
    yourPreview: 'Cómo se ve para ti ahora mismo',
    otherZonesPreview: 'Cómo se ve exactamente el mismo código en otro lugar',
    style_t: 'Hora corta',
    style_T: 'Hora larga',
    style_d: 'Fecha corta',
    style_D: 'Fecha larga',
    style_f: 'Fecha/hora corta',
    style_F: 'Fecha/hora larga',
    style_R: 'Relativo',
    detectedZoneNote: 'Detectado desde tu dispositivo: {zone}',
  },
  pt: {
    title: 'Gerador de timestamp do Discord',
    dateTime: 'Data e hora',
    timezone: 'Este é o horário local em',
    now: 'Agora',
    enterHint: 'Escolha uma data e hora para gerar os códigos.',
    invalidHint: 'Não foi possível interpretar essa data e hora.',
    error_invalidDateTime: 'Escolha uma data e hora válidas.',
    code: 'Código',
    copyAll: 'Copiar os 7',
    yourPreview: 'Como fica para você agora',
    otherZonesPreview: 'Como o mesmo código fica em outro lugar',
    style_t: 'Hora curta',
    style_T: 'Hora longa',
    style_d: 'Data curta',
    style_D: 'Data longa',
    style_f: 'Data/hora curta',
    style_F: 'Data/hora longa',
    style_R: 'Relativo',
    detectedZoneNote: 'Detectado a partir do seu dispositivo: {zone}',
  },
};
