import type { LocalizedStrings } from '@anytools/ui';

const EN = {
  title: 'QR Code Generator',
  tabText: 'Text',
  tabEmail: 'Email',
  tabPhone: 'Phone',
  anyText: 'Any text...',
  subjectOptional: 'Subject (optional)',
  bodyOptional: 'Body (optional)',
  ssid: 'SSID (network name)',
  wifiPassword: 'Password (leave empty for open)',
  wifiOpen: 'Open (no password)',
  firstName: 'First name',
  lastName: 'Last name',
  organization: 'Organization',
  jobTitle: 'Job title',
  phone: 'Phone',
  email: 'Email',
  website: 'Website',
  errorCorrection: 'Error correction',
  eccDefault: 'M (~15%) — default',
  eccLogos: 'H (~30%) — for logos',
  darkColor: 'Dark color',
  lightColor: 'Light color',
  previewAlt: 'QR code preview',
  downloadPng: 'Download PNG',
  downloadSvg: 'Download SVG',
  generationFailed: 'Generation failed',
  error_payloadEmpty: 'Payload is empty',
};

export const STRINGS: LocalizedStrings<typeof EN> = {
  en: EN,
  vi: {
    title: 'Tạo mã QR',
    tabText: 'Văn bản',
    tabEmail: 'Email',
    tabPhone: 'Điện thoại',
    anyText: 'Văn bản bất kỳ...',
    subjectOptional: 'Tiêu đề (không bắt buộc)',
    bodyOptional: 'Nội dung (không bắt buộc)',
    ssid: 'SSID (tên mạng)',
    wifiPassword: 'Mật khẩu (để trống nếu mạng mở)',
    wifiOpen: 'Mở (không mật khẩu)',
    firstName: 'Tên',
    lastName: 'Họ',
    organization: 'Tổ chức',
    jobTitle: 'Chức danh',
    phone: 'Điện thoại',
    email: 'Email',
    website: 'Trang web',
    errorCorrection: 'Mức sửa lỗi',
    eccDefault: 'M (~15%) — mặc định',
    eccLogos: 'H (~30%) — dành cho logo',
    darkColor: 'Màu tối',
    lightColor: 'Màu sáng',
    previewAlt: 'Xem trước mã QR',
    downloadPng: 'Tải PNG',
    downloadSvg: 'Tải SVG',
    generationFailed: 'Tạo mã thất bại',
    error_payloadEmpty: 'Nội dung trống',
  },
  es: {
    title: 'Generador de códigos QR',
    tabText: 'Texto',
    tabEmail: 'Correo',
    tabPhone: 'Teléfono',
    anyText: 'Cualquier texto...',
    subjectOptional: 'Asunto (opcional)',
    bodyOptional: 'Cuerpo (opcional)',
    ssid: 'SSID (nombre de la red)',
    wifiPassword: 'Contraseña (déjala vacía si es abierta)',
    wifiOpen: 'Abierta (sin contraseña)',
    firstName: 'Nombre',
    lastName: 'Apellido',
    organization: 'Organización',
    jobTitle: 'Cargo',
    phone: 'Teléfono',
    email: 'Correo',
    website: 'Sitio web',
    errorCorrection: 'Corrección de errores',
    eccDefault: 'M (~15%) — predeterminado',
    eccLogos: 'H (~30%) — para logos',
    darkColor: 'Color oscuro',
    lightColor: 'Color claro',
    previewAlt: 'Vista previa del código QR',
    downloadPng: 'Descargar PNG',
    downloadSvg: 'Descargar SVG',
    generationFailed: 'La generación falló',
    error_payloadEmpty: 'El contenido está vacío',
  },
  pt: {
    title: 'Gerador de QR Code',
    tabText: 'Texto',
    tabEmail: 'E-mail',
    tabPhone: 'Telefone',
    anyText: 'Qualquer texto...',
    subjectOptional: 'Assunto (opcional)',
    bodyOptional: 'Corpo (opcional)',
    ssid: 'SSID (nome da rede)',
    wifiPassword: 'Senha (deixe vazio se for aberta)',
    wifiOpen: 'Aberta (sem senha)',
    firstName: 'Nome',
    lastName: 'Sobrenome',
    organization: 'Organização',
    jobTitle: 'Cargo',
    phone: 'Telefone',
    email: 'E-mail',
    website: 'Site',
    errorCorrection: 'Correção de erros',
    eccDefault: 'M (~15%) — padrão',
    eccLogos: 'H (~30%) — para logos',
    darkColor: 'Cor escura',
    lightColor: 'Cor clara',
    previewAlt: 'Pré-visualização do QR code',
    downloadPng: 'Baixar PNG',
    downloadSvg: 'Baixar SVG',
    generationFailed: 'Falha ao gerar',
    error_payloadEmpty: 'O conteúdo está vazio',
  },
};
