import type { LocalizedStrings } from '@anytools/ui';

const EN = {
  title: 'User Agent Parser',
  uaLabel: 'User-Agent string — yours is filled in below',
  browser: 'Browser',
  engine: 'Engine',
  os: 'Operating system',
  deviceType: 'Device type',
  deviceModel: 'Device model',
  desktop: 'desktop',
  mobile: 'mobile',
  tablet: 'tablet',
  bot: 'bot',
  unknown: 'unknown',
  error_emptyInput: 'Paste a User-Agent string.',
  note: 'User-Agent strings are historical fiction — every browser claims to be Mozilla, Chrome claims to be Safari, Edge claims to be Chrome. Anyone can send any string. Useful as a hint for support and analytics; never as a security control.',
};

export const STRINGS: LocalizedStrings<typeof EN> = {
  en: EN,
  vi: {
    title: 'Phân tích User Agent',
    uaLabel: 'Chuỗi User-Agent — chuỗi của bạn đã được điền sẵn bên dưới',
    browser: 'Trình duyệt',
    engine: 'Engine',
    os: 'Hệ điều hành',
    deviceType: 'Loại thiết bị',
    deviceModel: 'Mẫu thiết bị',
    desktop: 'máy tính',
    mobile: 'điện thoại',
    tablet: 'máy tính bảng',
    bot: 'bot',
    unknown: 'không rõ',
    error_emptyInput: 'Dán một chuỗi User-Agent vào.',
    note: 'Chuỗi User-Agent là "tiểu thuyết lịch sử" — trình duyệt nào cũng tự nhận là Mozilla, Chrome nhận là Safari, Edge nhận là Chrome. Ai cũng có thể gửi chuỗi bất kỳ. Chỉ nên dùng làm gợi ý cho hỗ trợ và phân tích; không bao giờ dùng làm biện pháp bảo mật.',
  },
  es: {
    title: 'Analizador de User Agent',
    uaLabel: 'Cadena User-Agent — la tuya ya está rellenada abajo',
    browser: 'Navegador',
    engine: 'Motor',
    os: 'Sistema operativo',
    deviceType: 'Tipo de dispositivo',
    deviceModel: 'Modelo de dispositivo',
    desktop: 'escritorio',
    mobile: 'móvil',
    tablet: 'tableta',
    bot: 'bot',
    unknown: 'desconocido',
    error_emptyInput: 'Pega una cadena User-Agent.',
    note: 'Las cadenas User-Agent son ficción histórica — todos los navegadores dicen ser Mozilla, Chrome dice ser Safari, Edge dice ser Chrome. Cualquiera puede enviar cualquier cadena. Sirve como pista para soporte y analítica; nunca como control de seguridad.',
  },
  pt: {
    title: 'Analisador de User Agent',
    uaLabel: 'String User-Agent — a sua já está preenchida abaixo',
    browser: 'Navegador',
    engine: 'Motor',
    os: 'Sistema operacional',
    deviceType: 'Tipo de dispositivo',
    deviceModel: 'Modelo do dispositivo',
    desktop: 'desktop',
    mobile: 'celular',
    tablet: 'tablet',
    bot: 'bot',
    unknown: 'desconhecido',
    error_emptyInput: 'Cole uma string User-Agent.',
    note: 'Strings User-Agent são ficção histórica — todo navegador diz ser Mozilla, o Chrome diz ser Safari, o Edge diz ser Chrome. Qualquer um pode enviar qualquer string. Útil como pista para suporte e analytics; nunca como controle de segurança.',
  },
};
