import type { LocalizedStrings } from '@anytools/ui';

const EN = {
  title: 'Pomodoro Timer',
  description: '25 / 5 / 15 minute blocks.',
  mode: 'Mode',
  focus25: 'Focus (25)',
  short5: 'Short (5)',
  long15: 'Long (15)',
  phase_focus: 'Focus',
  phase_short: 'Short break',
  phase_long: 'Long break',
  pause: 'Pause',
  done: 'Done',
  completedToday: 'Completed focus blocks today:',
};

export const STRINGS: LocalizedStrings<typeof EN> = {
  en: EN,
  vi: {
    title: 'Đồng hồ Pomodoro',
    description: 'Các khối 25 / 5 / 15 phút.',
    mode: 'Chế độ',
    focus25: 'Tập trung (25)',
    short5: 'Nghỉ ngắn (5)',
    long15: 'Nghỉ dài (15)',
    phase_focus: 'Tập trung',
    phase_short: 'Nghỉ ngắn',
    phase_long: 'Nghỉ dài',
    pause: 'Tạm dừng',
    done: 'Xong',
    completedToday: 'Số khối tập trung hoàn thành hôm nay:',
  },
  es: {
    title: 'Temporizador Pomodoro',
    description: 'Bloques de 25 / 5 / 15 minutos.',
    mode: 'Modo',
    focus25: 'Enfoque (25)',
    short5: 'Corto (5)',
    long15: 'Largo (15)',
    phase_focus: 'Enfoque',
    phase_short: 'Descanso corto',
    phase_long: 'Descanso largo',
    pause: 'Pausar',
    done: 'Listo',
    completedToday: 'Bloques de enfoque completados hoy:',
  },
  pt: {
    title: 'Timer Pomodoro',
    description: 'Blocos de 25 / 5 / 15 minutos.',
    mode: 'Modo',
    focus25: 'Foco (25)',
    short5: 'Curta (5)',
    long15: 'Longa (15)',
    phase_focus: 'Foco',
    phase_short: 'Pausa curta',
    phase_long: 'Pausa longa',
    pause: 'Pausar',
    done: 'Concluído',
    completedToday: 'Blocos de foco concluídos hoje:',
  },
};
