import type { LocalizedStrings } from '@anytools/ui';

const EN = {
  title: 'IP Subnet Calculator',
  addressPrefix: 'IPv4 address / prefix',
  cidrNotation: 'CIDR notation',
  networkAddress: 'Network address',
  broadcastAddress: 'Broadcast address',
  firstHost: 'First usable host',
  lastHost: 'Last usable host',
  usableHosts: 'Usable hosts',
  totalAddresses: 'Total addresses',
  netmask: 'Netmask',
  wildcardMask: 'Wildcard mask',
  ipClass: 'IP class',
  scope: 'Scope',
  privateScope: 'Private (RFC 1918)',
  publicScope: 'Public',
  binaryAddress: 'address',
  binaryNetmask: 'netmask',
  // {code} is an example CIDR rendered in <code>.
  hint: 'Enter CIDR like {code} (prefix 0–32).',
};

export const STRINGS: LocalizedStrings<typeof EN> = {
  en: EN,
  vi: {
    title: 'Tính toán subnet IP',
    addressPrefix: 'Địa chỉ IPv4 / prefix',
    cidrNotation: 'Ký hiệu CIDR',
    networkAddress: 'Địa chỉ mạng',
    broadcastAddress: 'Địa chỉ broadcast',
    firstHost: 'Host đầu tiên dùng được',
    lastHost: 'Host cuối cùng dùng được',
    usableHosts: 'Số host dùng được',
    totalAddresses: 'Tổng số địa chỉ',
    netmask: 'Netmask',
    wildcardMask: 'Wildcard mask',
    ipClass: 'Lớp IP',
    scope: 'Phạm vi',
    privateScope: 'Riêng (RFC 1918)',
    publicScope: 'Công cộng',
    binaryAddress: 'địa chỉ',
    binaryNetmask: 'netmask',
    hint: 'Nhập CIDR dạng {code} (prefix 0–32).',
  },
  es: {
    title: 'Calculadora de subred IP',
    addressPrefix: 'Dirección IPv4 / prefijo',
    cidrNotation: 'Notación CIDR',
    networkAddress: 'Dirección de red',
    broadcastAddress: 'Dirección de broadcast',
    firstHost: 'Primer host utilizable',
    lastHost: 'Último host utilizable',
    usableHosts: 'Hosts utilizables',
    totalAddresses: 'Direcciones totales',
    netmask: 'Máscara de red',
    wildcardMask: 'Máscara wildcard',
    ipClass: 'Clase de IP',
    scope: 'Ámbito',
    privateScope: 'Privada (RFC 1918)',
    publicScope: 'Pública',
    binaryAddress: 'dirección',
    binaryNetmask: 'máscara',
    hint: 'Introduce un CIDR como {code} (prefijo 0–32).',
  },
  pt: {
    title: 'Calculadora de sub-rede IP',
    addressPrefix: 'Endereço IPv4 / prefixo',
    cidrNotation: 'Notação CIDR',
    networkAddress: 'Endereço de rede',
    broadcastAddress: 'Endereço de broadcast',
    firstHost: 'Primeiro host utilizável',
    lastHost: 'Último host utilizável',
    usableHosts: 'Hosts utilizáveis',
    totalAddresses: 'Total de endereços',
    netmask: 'Máscara de rede',
    wildcardMask: 'Máscara wildcard',
    ipClass: 'Classe de IP',
    scope: 'Escopo',
    privateScope: 'Privado (RFC 1918)',
    publicScope: 'Público',
    binaryAddress: 'endereço',
    binaryNetmask: 'máscara',
    hint: 'Digite um CIDR como {code} (prefixo 0–32).',
  },
};
