import type { LocalizedStrings } from '@anytools/ui';

const EN = {
  title: 'Random Picker',
  description: 'Dice, coin, number, list — one screen.',
  mode: 'Mode',
  dice: 'Dice',
  coin: 'Coin',
  number: 'Number',
  pick: 'Pick',
  diceCount: 'Dice count',
  sidesPerDie: 'Sides per die',
  min: 'Min',
  max: 'Max',
  itemsOnePerLine: 'Items (one per line)',
  listItems: 'List items',
  roll: 'Roll',
  flip: 'Flip',
  heads: 'Heads',
  tails: 'Tails',
};

export const STRINGS: LocalizedStrings<typeof EN> = {
  en: EN,
  vi: {
    title: 'Chọn ngẫu nhiên',
    description: 'Xúc xắc, đồng xu, số, danh sách — trên một màn hình.',
    mode: 'Chế độ',
    dice: 'Xúc xắc',
    coin: 'Đồng xu',
    number: 'Số',
    pick: 'Chọn',
    diceCount: 'Số xúc xắc',
    sidesPerDie: 'Số mặt mỗi xúc xắc',
    min: 'Nhỏ nhất',
    max: 'Lớn nhất',
    itemsOnePerLine: 'Danh sách (mỗi dòng một mục)',
    listItems: 'Các mục trong danh sách',
    roll: 'Gieo',
    flip: 'Tung',
    heads: 'Sấp',
    tails: 'Ngửa',
  },
  es: {
    title: 'Selector aleatorio',
    description: 'Dados, moneda, número, lista: todo en una pantalla.',
    mode: 'Modo',
    dice: 'Dados',
    coin: 'Moneda',
    number: 'Número',
    pick: 'Elegir',
    diceCount: 'Cantidad de dados',
    sidesPerDie: 'Caras por dado',
    min: 'Mín',
    max: 'Máx',
    itemsOnePerLine: 'Elementos (uno por línea)',
    listItems: 'Elementos de la lista',
    roll: 'Lanzar',
    flip: 'Lanzar',
    heads: 'Cara',
    tails: 'Cruz',
  },
  pt: {
    title: 'Sorteador aleatório',
    description: 'Dados, moeda, número, lista: tudo em uma tela.',
    mode: 'Modo',
    dice: 'Dados',
    coin: 'Moeda',
    number: 'Número',
    pick: 'Sortear',
    diceCount: 'Quantidade de dados',
    sidesPerDie: 'Lados por dado',
    min: 'Mín',
    max: 'Máx',
    itemsOnePerLine: 'Itens (um por linha)',
    listItems: 'Itens da lista',
    roll: 'Rolar',
    flip: 'Jogar',
    heads: 'Cara',
    tails: 'Coroa',
  },
};
