import type { LocalizedStrings } from '@anytools/ui';

const EN = {
  title: 'Watermark Image',
  dropLabel: 'Photos to watermark',
  markKind: 'Watermark',
  markKindText: 'Text',
  markKindImage: 'Logo image',
  textLabel: 'Text',
  textPlaceholder: 'e.g. © Your Name',
  colorLabel: 'Colour',
  logoDropLabel: 'Logo (PNG with transparency works best)',
  sizeLabel: 'Size ({n}% of image width)',
  positionLabel: 'Position',
  positionCustom: 'Free position',
  xPercent: 'Horizontal ({n}%)',
  yPercent: 'Vertical ({n}%)',
  opacityLabel: 'Opacity ({n}%)',
  rotationLabel: 'Rotation ({n}°)',
  tileLabel: 'Repeat across the whole image (tile)',
  livePreview: 'Live preview',
  previewHint: 'Shown on the first photo — updates as you change the controls below.',
  outputFormat: 'Output format',
  formatOriginal: 'Keep original',
  quality: 'Quality ({n}%)',
  watermarkOne: 'Watermark image',
  watermarkMany: 'Watermark {n} images',
  watermarking: 'Stamping…',
  watermarkingProgress: 'Stamping… {done}/{total}',
  downloadAllZip: 'Download all {n} as .zip',
  zipFailed: 'Could not build the .zip.',
  previewFailed: 'Could not render the preview.',
  failed: 'Watermarking failed',
  error_watermarkTextEmpty: 'Type the text you want stamped on the images.',
  error_opacityRange: 'Opacity must be above 0 and at most 1.',
  error_watermarkLogoMissing: 'Choose a logo image to stamp.',
  grid_topLeft: 'Top left',
  grid_topCenter: 'Top centre',
  grid_topRight: 'Top right',
  grid_middleLeft: 'Middle left',
  grid_center: 'Centre',
  grid_middleRight: 'Middle right',
  grid_bottomLeft: 'Bottom left',
  grid_bottomCenter: 'Bottom centre',
  grid_bottomRight: 'Bottom right',
};

export const STRINGS: LocalizedStrings<typeof EN> = {
  en: EN,
  vi: {
    title: 'Đóng dấu mờ lên ảnh',
    dropLabel: 'Ảnh cần đóng dấu',
    markKind: 'Kiểu dấu',
    markKindText: 'Chữ',
    markKindImage: 'Logo',
    textLabel: 'Nội dung',
    textPlaceholder: 'vd. © Tên của bạn',
    colorLabel: 'Màu chữ',
    logoDropLabel: 'Logo (PNG có nền trong suốt là tốt nhất)',
    sizeLabel: 'Cỡ ({n}% chiều rộng ảnh)',
    positionLabel: 'Vị trí',
    positionCustom: 'Vị trí tự do',
    xPercent: 'Ngang ({n}%)',
    yPercent: 'Dọc ({n}%)',
    opacityLabel: 'Độ mờ ({n}%)',
    rotationLabel: 'Góc xoay ({n}°)',
    tileLabel: 'Lặp kín cả ảnh (tile)',
    livePreview: 'Xem trước trực tiếp',
    previewHint: 'Hiện trên ảnh đầu tiên — cập nhật ngay khi bạn chỉnh các tuỳ chọn bên dưới.',
    outputFormat: 'Định dạng xuất',
    formatOriginal: 'Giữ định dạng gốc',
    quality: 'Chất lượng ({n}%)',
    watermarkOne: 'Đóng dấu ảnh',
    watermarkMany: 'Đóng dấu {n} ảnh',
    watermarking: 'Đang đóng dấu…',
    watermarkingProgress: 'Đang đóng dấu… {done}/{total}',
    downloadAllZip: 'Tải cả {n} ảnh dạng .zip',
    zipFailed: 'Không thể tạo file .zip.',
    previewFailed: 'Không thể dựng bản xem trước.',
    failed: 'Đóng dấu thất bại',
    error_watermarkTextEmpty: 'Nhập nội dung chữ bạn muốn đóng dấu lên ảnh.',
    error_opacityRange: 'Độ mờ phải lớn hơn 0 và tối đa là 1.',
    error_watermarkLogoMissing: 'Chọn một ảnh logo để đóng dấu.',
    grid_topLeft: 'Trên trái',
    grid_topCenter: 'Trên giữa',
    grid_topRight: 'Trên phải',
    grid_middleLeft: 'Giữa trái',
    grid_center: 'Chính giữa',
    grid_middleRight: 'Giữa phải',
    grid_bottomLeft: 'Dưới trái',
    grid_bottomCenter: 'Dưới giữa',
    grid_bottomRight: 'Dưới phải',
  },
  es: {
    title: 'Marca de agua en imagen',
    dropLabel: 'Fotos a marcar',
    markKind: 'Tipo de marca',
    markKindText: 'Texto',
    markKindImage: 'Logotipo',
    textLabel: 'Texto',
    textPlaceholder: 'p. ej. © Tu Nombre',
    colorLabel: 'Color',
    logoDropLabel: 'Logotipo (PNG con transparencia funciona mejor)',
    sizeLabel: 'Tamaño ({n}% del ancho de la imagen)',
    positionLabel: 'Posición',
    positionCustom: 'Posición libre',
    xPercent: 'Horizontal ({n}%)',
    yPercent: 'Vertical ({n}%)',
    opacityLabel: 'Opacidad ({n}%)',
    rotationLabel: 'Rotación ({n}°)',
    tileLabel: 'Repetir en toda la imagen (mosaico)',
    livePreview: 'Vista previa en vivo',
    previewHint: 'Se muestra en la primera foto — se actualiza al cambiar los controles.',
    outputFormat: 'Formato de salida',
    formatOriginal: 'Mantener el original',
    quality: 'Calidad ({n}%)',
    watermarkOne: 'Marcar imagen',
    watermarkMany: 'Marcar {n} imágenes',
    watermarking: 'Estampando…',
    watermarkingProgress: 'Estampando… {done}/{total}',
    downloadAllZip: 'Descargar las {n} en .zip',
    zipFailed: 'No se pudo crear el .zip.',
    previewFailed: 'No se pudo generar la vista previa.',
    failed: 'Error al marcar',
    error_watermarkTextEmpty: 'Escribe el texto que quieres estampar en las imágenes.',
    error_opacityRange: 'La opacidad debe ser mayor que 0 y como máximo 1.',
    error_watermarkLogoMissing: 'Elige una imagen de logotipo para estampar.',
    grid_topLeft: 'Arriba izquierda',
    grid_topCenter: 'Arriba centro',
    grid_topRight: 'Arriba derecha',
    grid_middleLeft: 'Medio izquierda',
    grid_center: 'Centro',
    grid_middleRight: 'Medio derecha',
    grid_bottomLeft: 'Abajo izquierda',
    grid_bottomCenter: 'Abajo centro',
    grid_bottomRight: 'Abajo derecha',
  },
  pt: {
    title: 'Marca d’água em imagem',
    dropLabel: 'Fotos para marcar',
    markKind: 'Tipo de marca',
    markKindText: 'Texto',
    markKindImage: 'Logótipo',
    textLabel: 'Texto',
    textPlaceholder: 'ex.: © Seu Nome',
    colorLabel: 'Cor',
    logoDropLabel: 'Logótipo (PNG com transparência funciona melhor)',
    sizeLabel: 'Tamanho ({n}% da largura da imagem)',
    positionLabel: 'Posição',
    positionCustom: 'Posição livre',
    xPercent: 'Horizontal ({n}%)',
    yPercent: 'Vertical ({n}%)',
    opacityLabel: 'Opacidade ({n}%)',
    rotationLabel: 'Rotação ({n}°)',
    tileLabel: 'Repetir por toda a imagem (mosaico)',
    livePreview: 'Pré-visualização ao vivo',
    previewHint: 'Mostrada na primeira foto — atualiza ao mudar os controlos abaixo.',
    outputFormat: 'Formato de saída',
    formatOriginal: 'Manter o original',
    quality: 'Qualidade ({n}%)',
    watermarkOne: 'Marcar imagem',
    watermarkMany: 'Marcar {n} imagens',
    watermarking: 'Aplicando…',
    watermarkingProgress: 'Aplicando… {done}/{total}',
    downloadAllZip: 'Baixar as {n} em .zip',
    zipFailed: 'Não foi possível criar o .zip.',
    previewFailed: 'Não foi possível gerar a pré-visualização.',
    failed: 'Falha ao marcar',
    error_watermarkTextEmpty: 'Digite o texto que deseja marcar nas imagens.',
    error_opacityRange: 'A opacidade deve ser maior que 0 e no máximo 1.',
    error_watermarkLogoMissing: 'Escolha uma imagem de logótipo para marcar.',
    grid_topLeft: 'Superior esquerda',
    grid_topCenter: 'Superior centro',
    grid_topRight: 'Superior direita',
    grid_middleLeft: 'Meio esquerda',
    grid_center: 'Centro',
    grid_middleRight: 'Meio direita',
    grid_bottomLeft: 'Inferior esquerda',
    grid_bottomCenter: 'Inferior centro',
    grid_bottomRight: 'Inferior direita',
  },
};
