import type { LocalizedStrings } from '@anytools/ui';

const EN = {
  title: 'CSS Clip Path Generator',
  hint: 'Drag a vertex to move it, or focus one and use the arrow keys. The small squares on each edge add a vertex there; Delete on a vertex removes it (three is the minimum).',
  shape: 'Shape',
  polygon: 'Polygon',
  circle: 'Circle',
  ellipse: 'Ellipse',
  inset: 'Inset',
  presets: 'Presets',
  preset_Triangle: 'Triangle',
  preset_Diamond: 'Diamond',
  preset_Pentagon: 'Pentagon',
  preset_Hexagon: 'Hexagon',
  preset_Octagon: 'Octagon',
  preset_Star: 'Star',
  preset_Chevron: 'Chevron',
  preset_Arrow: 'Arrow',
  preset_Cross: 'Cross',
  preset_SpeechBubble: 'Speech bubble',
  preset_Parallelogram: 'Parallelogram',
  preset_Trapezoid: 'Trapezoid',
  radius: 'Radius',
  radiusX: 'Radius X',
  radiusY: 'Radius Y',
  centreX: 'Centre X',
  centreY: 'Centre Y',
  top: 'Top',
  right: 'Right',
  bottom: 'Bottom',
  left: 'Left',
  cornerRadius: 'Corner radius',
  units: 'Units',
  boxWidth: 'Box width',
  boxHeight: 'Box height',
  boxWidthAria: 'Reference box width in px',
  boxHeightAria: 'Reference box height in px',
  pxNote:
    'px values are frozen at this box size — the shape will not follow a responsive element. Percentages are the safer default.',
  boxWarning:
    'A box side has to be at least 1px. The CSS below still uses the last size that was: {w}×{h}.',
  verticesValue: '{n} vertices · value: {code}',
  vertexHandle: 'Vertex {n} at {x}% {y}% — arrow keys move it, Delete removes it',
  addVertexAfter: 'Add a vertex on the edge after vertex {n}',
};

export const STRINGS: LocalizedStrings<typeof EN> = {
  en: EN,
  vi: {
    title: 'Tạo CSS Clip Path',
    hint: 'Kéo một đỉnh để di chuyển, hoặc chọn đỉnh rồi dùng phím mũi tên. Các ô vuông nhỏ trên mỗi cạnh thêm đỉnh tại đó; nhấn Delete trên một đỉnh để xóa (tối thiểu ba đỉnh).',
    shape: 'Hình dạng',
    polygon: 'Đa giác',
    circle: 'Tròn',
    ellipse: 'Elip',
    inset: 'Inset',
    presets: 'Mẫu có sẵn',
    preset_Triangle: 'Tam giác',
    preset_Diamond: 'Hình thoi',
    preset_Pentagon: 'Ngũ giác',
    preset_Hexagon: 'Lục giác',
    preset_Octagon: 'Bát giác',
    preset_Star: 'Ngôi sao',
    preset_Chevron: 'Mũi nhọn',
    preset_Arrow: 'Mũi tên',
    preset_Cross: 'Chữ thập',
    preset_SpeechBubble: 'Bong bóng thoại',
    preset_Parallelogram: 'Hình bình hành',
    preset_Trapezoid: 'Hình thang',
    radius: 'Bán kính',
    radiusX: 'Bán kính X',
    radiusY: 'Bán kính Y',
    centreX: 'Tâm X',
    centreY: 'Tâm Y',
    top: 'Trên',
    right: 'Phải',
    bottom: 'Dưới',
    left: 'Trái',
    cornerRadius: 'Bo góc',
    units: 'Đơn vị',
    boxWidth: 'Chiều rộng khung',
    boxHeight: 'Chiều cao khung',
    boxWidthAria: 'Chiều rộng khung tham chiếu (px)',
    boxHeightAria: 'Chiều cao khung tham chiếu (px)',
    pxNote:
      'Giá trị px bị cố định theo kích thước khung này — hình sẽ không co giãn theo phần tử responsive. Phần trăm là lựa chọn an toàn hơn.',
    boxWarning:
      'Cạnh khung phải ít nhất 1px. CSS bên dưới vẫn dùng kích thước hợp lệ gần nhất: {w}×{h}.',
    verticesValue: '{n} đỉnh · giá trị: {code}',
    vertexHandle: 'Đỉnh {n} tại {x}% {y}% — phím mũi tên để di chuyển, Delete để xóa',
    addVertexAfter: 'Thêm đỉnh trên cạnh sau đỉnh {n}',
  },
  es: {
    title: 'Generador de clip-path CSS',
    hint: 'Arrastra un vértice para moverlo, o enfócalo y usa las flechas. Los cuadraditos de cada arista añaden un vértice ahí; Supr sobre un vértice lo elimina (el mínimo es tres).',
    shape: 'Forma',
    polygon: 'Polígono',
    circle: 'Círculo',
    ellipse: 'Elipse',
    inset: 'Inset',
    presets: 'Preajustes',
    preset_Triangle: 'Triángulo',
    preset_Diamond: 'Rombo',
    preset_Pentagon: 'Pentágono',
    preset_Hexagon: 'Hexágono',
    preset_Octagon: 'Octágono',
    preset_Star: 'Estrella',
    preset_Chevron: 'Chevrón',
    preset_Arrow: 'Flecha',
    preset_Cross: 'Cruz',
    preset_SpeechBubble: 'Bocadillo',
    preset_Parallelogram: 'Paralelogramo',
    preset_Trapezoid: 'Trapecio',
    radius: 'Radio',
    radiusX: 'Radio X',
    radiusY: 'Radio Y',
    centreX: 'Centro X',
    centreY: 'Centro Y',
    top: 'Arriba',
    right: 'Derecha',
    bottom: 'Abajo',
    left: 'Izquierda',
    cornerRadius: 'Radio de esquina',
    units: 'Unidades',
    boxWidth: 'Ancho de la caja',
    boxHeight: 'Alto de la caja',
    boxWidthAria: 'Ancho de la caja de referencia en px',
    boxHeightAria: 'Alto de la caja de referencia en px',
    pxNote:
      'Los valores en px quedan fijos a este tamaño de caja: la forma no seguirá a un elemento responsivo. Los porcentajes son la opción más segura.',
    boxWarning:
      'Un lado de la caja debe medir al menos 1px. El CSS de abajo sigue usando el último tamaño válido: {w}×{h}.',
    verticesValue: '{n} vértices · valor: {code}',
    vertexHandle: 'Vértice {n} en {x}% {y}%: las flechas lo mueven, Supr lo elimina',
    addVertexAfter: 'Añadir un vértice en la arista después del vértice {n}',
  },
  pt: {
    title: 'Gerador de clip-path CSS',
    hint: 'Arraste um vértice para movê-lo, ou foque nele e use as setas. Os quadradinhos em cada aresta adicionam um vértice ali; Delete em um vértice o remove (o mínimo é três).',
    shape: 'Forma',
    polygon: 'Polígono',
    circle: 'Círculo',
    ellipse: 'Elipse',
    inset: 'Inset',
    presets: 'Predefinições',
    preset_Triangle: 'Triângulo',
    preset_Diamond: 'Losango',
    preset_Pentagon: 'Pentágono',
    preset_Hexagon: 'Hexágono',
    preset_Octagon: 'Octógono',
    preset_Star: 'Estrela',
    preset_Chevron: 'Chevron',
    preset_Arrow: 'Seta',
    preset_Cross: 'Cruz',
    preset_SpeechBubble: 'Balão de fala',
    preset_Parallelogram: 'Paralelogramo',
    preset_Trapezoid: 'Trapézio',
    radius: 'Raio',
    radiusX: 'Raio X',
    radiusY: 'Raio Y',
    centreX: 'Centro X',
    centreY: 'Centro Y',
    top: 'Topo',
    right: 'Direita',
    bottom: 'Base',
    left: 'Esquerda',
    cornerRadius: 'Raio dos cantos',
    units: 'Unidades',
    boxWidth: 'Largura da caixa',
    boxHeight: 'Altura da caixa',
    boxWidthAria: 'Largura da caixa de referência em px',
    boxHeightAria: 'Altura da caixa de referência em px',
    pxNote:
      'Valores em px ficam fixos neste tamanho de caixa: a forma não acompanhará um elemento responsivo. Porcentagens são a opção mais segura.',
    boxWarning:
      'Um lado da caixa precisa ter pelo menos 1px. O CSS abaixo ainda usa o último tamanho válido: {w}×{h}.',
    verticesValue: '{n} vértices · valor: {code}',
    vertexHandle: 'Vértice {n} em {x}% {y}%: as setas o movem, Delete o remove',
    addVertexAfter: 'Adicionar um vértice na aresta após o vértice {n}',
  },
};
