import type { LocalizedStrings } from '@anytools/ui';

const EN = {
  title: 'Watermark PDF',
  dropLabel: 'The PDF to stamp. The mark is drawn on top; nothing already on the page is removed.',
  couldNotReadPdf: 'Could not read PDF',
  couldNotReadImage: 'Could not read image',
  chooseImage: 'Choose a PNG or JPG to use as the watermark.',
  failed: 'Could not add the watermark',
  pageCountOne: '{n} page.',
  pageCountMany: '{n} pages.',
  watermark: 'Watermark',
  kindText: 'Text',
  kindImage: 'Image (PNG or JPG)',
  text: 'Text',
  fontSize: 'Font size',
  colour: 'Colour',
  imageDropLabel: 'The image to stamp. A logo with a transparent background works best.',
  width: 'Width — {n}% of the page',
  angle: 'Angle — {n}°',
  opacity: 'Opacity — {n}%',
  pagesToStamp: 'Pages to stamp',
  // {n} is the page count of the loaded PDF.
  rangePlaceholderAll: 'all — or e.g. 1-{n}',
  rangePlaceholder: 'all — or e.g. 1-5, 9',
  previewAlt: 'First page of the PDF, with the watermark drawn over it',
  previewCaption:
    "Page 1, with the mark drawn over it in the browser. A close approximation — the font is your system's Helvetica, not the one written into the PDF.",
  fontNote:
    'Latin text is drawn in Helvetica, the font every PDF reader already has, so nothing is embedded and the file barely grows. Vietnamese, Greek and Cyrillic switch to Noto Sans, embedded as a small subset. Chinese, Japanese, Korean, Arabic and emoji are not covered, and the tool names the characters rather than fail obscurely.',
  stamping: 'Stamping…',
  addWatermark: 'Add watermark',
  stampedOne: 'Stamped {n} of {total} page',
  stampedMany: 'Stamped {n} of {total} pages',
  download: 'Download watermarked.pdf',
};

export const STRINGS: LocalizedStrings<typeof EN> = {
  en: EN,
  vi: {
    title: 'Đóng dấu PDF',
    dropLabel: 'PDF cần đóng dấu. Dấu được vẽ đè lên; nội dung sẵn có trên trang không bị xóa.',
    couldNotReadPdf: 'Không đọc được PDF',
    couldNotReadImage: 'Không đọc được ảnh',
    chooseImage: 'Chọn một ảnh PNG hoặc JPG để làm dấu.',
    failed: 'Không thể thêm dấu',
    pageCountOne: '{n} trang.',
    pageCountMany: '{n} trang.',
    watermark: 'Dấu',
    kindText: 'Chữ',
    kindImage: 'Ảnh (PNG hoặc JPG)',
    text: 'Chữ',
    fontSize: 'Cỡ chữ',
    colour: 'Màu',
    imageDropLabel: 'Ảnh dùng làm dấu. Logo có nền trong suốt cho kết quả tốt nhất.',
    width: 'Chiều rộng — {n}% trang',
    angle: 'Góc — {n}°',
    opacity: 'Độ mờ — {n}%',
    pagesToStamp: 'Các trang cần đóng dấu',
    rangePlaceholderAll: 'tất cả — hoặc vd. 1-{n}',
    rangePlaceholder: 'tất cả — hoặc vd. 1-5, 9',
    previewAlt: 'Trang đầu của PDF, có dấu vẽ đè lên',
    previewCaption:
      'Trang 1, với dấu vẽ đè lên ngay trong trình duyệt. Chỉ là mô phỏng gần đúng — phông là Helvetica của hệ thống bạn, không phải phông ghi vào PDF.',
    fontNote:
      'Chữ Latin được vẽ bằng Helvetica, phông có sẵn trong mọi trình đọc PDF, nên không nhúng gì và tệp gần như không lớn lên. Tiếng Việt, Hy Lạp và Kirin chuyển sang Noto Sans, nhúng dưới dạng tập con nhỏ. Tiếng Trung, Nhật, Hàn, Ả Rập và emoji không được hỗ trợ — công cụ sẽ nêu rõ ký tự nào thay vì báo lỗi mơ hồ.',
    stamping: 'Đang đóng dấu…',
    addWatermark: 'Thêm dấu',
    stampedOne: 'Đã đóng dấu {n}/{total} trang',
    stampedMany: 'Đã đóng dấu {n}/{total} trang',
    download: 'Tải watermarked.pdf',
  },
  es: {
    title: 'Marca de agua en PDF',
    dropLabel:
      'El PDF a marcar. La marca se dibuja encima; nada de lo que ya hay en la página se elimina.',
    couldNotReadPdf: 'No se pudo leer el PDF',
    couldNotReadImage: 'No se pudo leer la imagen',
    chooseImage: 'Elige un PNG o JPG para usar como marca de agua.',
    failed: 'No se pudo añadir la marca de agua',
    pageCountOne: '{n} página.',
    pageCountMany: '{n} páginas.',
    watermark: 'Marca de agua',
    kindText: 'Texto',
    kindImage: 'Imagen (PNG o JPG)',
    text: 'Texto',
    fontSize: 'Tamaño de fuente',
    colour: 'Color',
    imageDropLabel: 'La imagen a estampar. Un logo con fondo transparente funciona mejor.',
    width: 'Ancho — {n}% de la página',
    angle: 'Ángulo — {n}°',
    opacity: 'Opacidad — {n}%',
    pagesToStamp: 'Páginas a marcar',
    rangePlaceholderAll: 'todas — o p. ej. 1-{n}',
    rangePlaceholder: 'todas — o p. ej. 1-5, 9',
    previewAlt: 'Primera página del PDF, con la marca de agua dibujada encima',
    previewCaption:
      'Página 1, con la marca dibujada encima en el navegador. Una aproximación cercana — la fuente es la Helvetica de tu sistema, no la escrita en el PDF.',
    fontNote:
      'El texto latino se dibuja en Helvetica, la fuente que ya tiene todo lector de PDF, así que no se incrusta nada y el archivo apenas crece. Vietnamita, griego y cirílico pasan a Noto Sans, incrustada como un pequeño subconjunto. Chino, japonés, coreano, árabe y emoji no están cubiertos, y la herramienta nombra los caracteres en lugar de fallar de forma confusa.',
    stamping: 'Estampando…',
    addWatermark: 'Añadir marca de agua',
    stampedOne: 'Marcada {n} de {total} página',
    stampedMany: 'Marcadas {n} de {total} páginas',
    download: 'Descargar watermarked.pdf',
  },
  pt: {
    title: "Marca d'água em PDF",
    dropLabel:
      'O PDF a carimbar. A marca é desenhada por cima; nada que já está na página é removido.',
    couldNotReadPdf: 'Não foi possível ler o PDF',
    couldNotReadImage: 'Não foi possível ler a imagem',
    chooseImage: "Escolha um PNG ou JPG para usar como marca d'água.",
    failed: "Não foi possível adicionar a marca d'água",
    pageCountOne: '{n} página.',
    pageCountMany: '{n} páginas.',
    watermark: "Marca d'água",
    kindText: 'Texto',
    kindImage: 'Imagem (PNG ou JPG)',
    text: 'Texto',
    fontSize: 'Tamanho da fonte',
    colour: 'Cor',
    imageDropLabel: 'A imagem a carimbar. Um logo com fundo transparente funciona melhor.',
    width: 'Largura — {n}% da página',
    angle: 'Ângulo — {n}°',
    opacity: 'Opacidade — {n}%',
    pagesToStamp: 'Páginas a carimbar',
    rangePlaceholderAll: 'todas — ou ex. 1-{n}',
    rangePlaceholder: 'todas — ou ex. 1-5, 9',
    previewAlt: "Primeira página do PDF, com a marca d'água desenhada por cima",
    previewCaption:
      'Página 1, com a marca desenhada por cima no navegador. Uma aproximação próxima — a fonte é a Helvetica do seu sistema, não a gravada no PDF.',
    fontNote:
      'Texto latino é desenhado em Helvetica, a fonte que todo leitor de PDF já tem, então nada é incorporado e o arquivo quase não cresce. Vietnamita, grego e cirílico passam para Noto Sans, incorporada como um pequeno subconjunto. Chinês, japonês, coreano, árabe e emoji não são cobertos, e a ferramenta nomeia os caracteres em vez de falhar de forma obscura.',
    stamping: 'Carimbando…',
    addWatermark: "Adicionar marca d'água",
    stampedOne: 'Carimbada {n} de {total} página',
    stampedMany: 'Carimbadas {n} de {total} páginas',
    download: 'Baixar watermarked.pdf',
  },
};
