import type { LocalizedStrings } from '@anytools/ui';

const EN = {
  title: 'Crontab Generator',
  // Preset labels, keyed by the preset id from the logic layer.
  preset_every_minute: 'Every minute',
  preset_every_5_min: 'Every 5 minutes',
  preset_every_15_min: 'Every 15 minutes',
  preset_hourly: 'Every hour',
  preset_daily_midnight: 'Daily at 00:00',
  preset_daily_9am: 'Daily at 09:00',
  preset_weekdays_9am: 'Weekdays at 09:00',
  preset_weekly_sunday: 'Weekly on Sunday 00:00',
  preset_monthly_first: 'Monthly on the 1st 00:00',
  preset_yearly_jan1: 'Yearly on Jan 1 00:00',
  minute: 'Minute',
  hour: 'Hour',
  dayOfMonth: 'Day of month',
  month: 'Month',
  dayOfWeek: 'Day of week',
  dayOfWeekHint: '0–6 (Sun=0), 1-5',
  next5Runs: 'Next 5 runs (UTC)',
};

export const STRINGS: LocalizedStrings<typeof EN> = {
  en: EN,
  vi: {
    title: 'Tạo crontab',
    preset_every_minute: 'Mỗi phút',
    preset_every_5_min: 'Mỗi 5 phút',
    preset_every_15_min: 'Mỗi 15 phút',
    preset_hourly: 'Mỗi giờ',
    preset_daily_midnight: 'Hằng ngày lúc 00:00',
    preset_daily_9am: 'Hằng ngày lúc 09:00',
    preset_weekdays_9am: 'Ngày làm việc lúc 09:00',
    preset_weekly_sunday: 'Hằng tuần, Chủ nhật 00:00',
    preset_monthly_first: 'Mùng 1 hằng tháng 00:00',
    preset_yearly_jan1: 'Hằng năm, 1/1 lúc 00:00',
    minute: 'Phút',
    hour: 'Giờ',
    dayOfMonth: 'Ngày trong tháng',
    month: 'Tháng',
    dayOfWeek: 'Thứ',
    dayOfWeekHint: '0–6 (CN=0), 1-5',
    next5Runs: '5 lần chạy tiếp theo (UTC)',
  },
  es: {
    title: 'Generador de crontab',
    preset_every_minute: 'Cada minuto',
    preset_every_5_min: 'Cada 5 minutos',
    preset_every_15_min: 'Cada 15 minutos',
    preset_hourly: 'Cada hora',
    preset_daily_midnight: 'Diario a las 00:00',
    preset_daily_9am: 'Diario a las 09:00',
    preset_weekdays_9am: 'Días laborables a las 09:00',
    preset_weekly_sunday: 'Semanal, domingo 00:00',
    preset_monthly_first: 'Mensual, día 1 a las 00:00',
    preset_yearly_jan1: 'Anual, 1 de enero 00:00',
    minute: 'Minuto',
    hour: 'Hora',
    dayOfMonth: 'Día del mes',
    month: 'Mes',
    dayOfWeek: 'Día de la semana',
    dayOfWeekHint: '0–6 (Dom=0), 1-5',
    next5Runs: 'Próximas 5 ejecuciones (UTC)',
  },
  pt: {
    title: 'Gerador de crontab',
    preset_every_minute: 'A cada minuto',
    preset_every_5_min: 'A cada 5 minutos',
    preset_every_15_min: 'A cada 15 minutos',
    preset_hourly: 'A cada hora',
    preset_daily_midnight: 'Diário às 00:00',
    preset_daily_9am: 'Diário às 09:00',
    preset_weekdays_9am: 'Dias úteis às 09:00',
    preset_weekly_sunday: 'Semanal, domingo 00:00',
    preset_monthly_first: 'Mensal, dia 1 às 00:00',
    preset_yearly_jan1: 'Anual, 1º de janeiro 00:00',
    minute: 'Minuto',
    hour: 'Hora',
    dayOfMonth: 'Dia do mês',
    month: 'Mês',
    dayOfWeek: 'Dia da semana',
    dayOfWeekHint: '0–6 (Dom=0), 1-5',
    next5Runs: 'Próximas 5 execuções (UTC)',
  },
};
