import type { LocalizedStrings } from '@anytools/ui';

const EN = {
  title: 'Bcrypt Generator',
  tabHash: 'Hash',
  tabVerify: 'Verify',
  password: 'Password',
  passwordToHash: 'Password to hash',
  // {n} is the cost factor (number of rounds).
  costRounds: 'Cost rounds: {n} (2^{n} iterations)',
  hashing: 'Hashing…',
  generateHash: 'Generate hash',
  passwordToVerify: 'Password to verify',
  existingHash: 'Existing bcrypt hash',
  bcryptHash: 'Bcrypt hash',
  checking: 'Checking…',
  match: 'Match ✓',
  noMatch: 'No match ✗',
};

export const STRINGS: LocalizedStrings<typeof EN> = {
  en: EN,
  vi: {
    title: 'Tạo hash Bcrypt',
    tabHash: 'Tạo hash',
    tabVerify: 'Xác minh',
    password: 'Mật khẩu',
    passwordToHash: 'Mật khẩu cần băm',
    costRounds: 'Số vòng (cost): {n} (2^{n} lần lặp)',
    hashing: 'Đang băm…',
    generateHash: 'Tạo hash',
    passwordToVerify: 'Mật khẩu cần xác minh',
    existingHash: 'Hash bcrypt hiện có',
    bcryptHash: 'Hash bcrypt',
    checking: 'Đang kiểm tra…',
    match: 'Khớp ✓',
    noMatch: 'Không khớp ✗',
  },
  es: {
    title: 'Generador Bcrypt',
    tabHash: 'Hash',
    tabVerify: 'Verificar',
    password: 'Contraseña',
    passwordToHash: 'Contraseña a hashear',
    costRounds: 'Rondas de coste: {n} (2^{n} iteraciones)',
    hashing: 'Calculando hash…',
    generateHash: 'Generar hash',
    passwordToVerify: 'Contraseña a verificar',
    existingHash: 'Hash bcrypt existente',
    bcryptHash: 'Hash bcrypt',
    checking: 'Comprobando…',
    match: 'Coincide ✓',
    noMatch: 'No coincide ✗',
  },
  pt: {
    title: 'Gerador Bcrypt',
    tabHash: 'Hash',
    tabVerify: 'Verificar',
    password: 'Senha',
    passwordToHash: 'Senha a ser hasheada',
    costRounds: 'Rodadas de custo: {n} (2^{n} iterações)',
    hashing: 'Calculando hash…',
    generateHash: 'Gerar hash',
    passwordToVerify: 'Senha a verificar',
    existingHash: 'Hash bcrypt existente',
    bcryptHash: 'Hash bcrypt',
    checking: 'Verificando…',
    match: 'Confere ✓',
    noMatch: 'Não confere ✗',
  },
};
