import type { LocalizedStrings } from '@anytools/ui';

const EN = {
  title: 'Timestamp Converter',
  inputLabel: 'Input — Unix seconds, millis, ISO 8601, or RFC 2822',
  now: 'Now',
  timezone: 'Timezone',
  enterHint: 'Enter a timestamp to convert.',
  parseFailed: 'Parse failed',
  detected: 'Detected',
  unixSeconds: 'Unix seconds',
  unixMillis: 'Unix millis',
  // {zone} is an IANA timezone id such as Asia/Ho_Chi_Minh.
  inZone: 'In {zone}',
  relative: 'Relative',
  error_tooLarge: 'That number is too large for a Unix timestamp in seconds or milliseconds.',
  error_unrecognized:
    'Unrecognized timestamp format. Try Unix seconds/millis, ISO 8601, or RFC 2822.',
  format_unixSeconds: 'unix-seconds',
  format_unixMillis: 'unix-millis',
  format_iso: 'iso',
  format_rfc2822: 'rfc2822',
  format_unknown: 'unknown',
  rel_sec: '{n} sec',
  rel_min: '{n} min',
  rel_hr: '{n} hr',
  rel_days: '{n} days',
  rel_years: '{n} years',
  rel_future: 'in {t}',
  rel_past: '{t} ago',
};

export const STRINGS: LocalizedStrings<typeof EN> = {
  en: EN,
  vi: {
    title: 'Chuyển đổi timestamp',
    inputLabel: 'Đầu vào — giây Unix, mili giây, ISO 8601 hoặc RFC 2822',
    now: 'Bây giờ',
    timezone: 'Múi giờ',
    enterHint: 'Nhập một timestamp để chuyển đổi.',
    parseFailed: 'Phân tích thất bại',
    detected: 'Nhận diện',
    unixSeconds: 'Giây Unix',
    unixMillis: 'Mili giây Unix',
    inZone: 'Theo {zone}',
    relative: 'Tương đối',
    error_tooLarge: 'Số này quá lớn cho dấu thời gian Unix tính bằng giây hoặc mili giây.',
    error_unrecognized:
      'Không nhận ra định dạng dấu thời gian. Thử giây/mili giây Unix, ISO 8601 hoặc RFC 2822.',
    format_unixSeconds: 'giây Unix',
    format_unixMillis: 'mili giây Unix',
    format_iso: 'ISO 8601',
    format_rfc2822: 'RFC 2822',
    format_unknown: 'không xác định',
    rel_sec: '{n} giây',
    rel_min: '{n} phút',
    rel_hr: '{n} giờ',
    rel_days: '{n} ngày',
    rel_years: '{n} năm',
    rel_future: '{t} nữa',
    rel_past: '{t} trước',
  },
  es: {
    title: 'Conversor de timestamps',
    inputLabel: 'Entrada — segundos Unix, milisegundos, ISO 8601 o RFC 2822',
    now: 'Ahora',
    timezone: 'Zona horaria',
    enterHint: 'Introduce un timestamp para convertirlo.',
    parseFailed: 'No se pudo interpretar',
    detected: 'Detectado',
    unixSeconds: 'Segundos Unix',
    unixMillis: 'Milisegundos Unix',
    inZone: 'En {zone}',
    relative: 'Relativo',
    error_tooLarge:
      'Ese número es demasiado grande para una marca de tiempo Unix en segundos o milisegundos.',
    error_unrecognized:
      'Formato de marca de tiempo no reconocido. Prueba con segundos/milisegundos Unix, ISO 8601 o RFC 2822.',
    format_unixSeconds: 'segundos Unix',
    format_unixMillis: 'milisegundos Unix',
    format_iso: 'ISO 8601',
    format_rfc2822: 'RFC 2822',
    format_unknown: 'desconocido',
    rel_sec: '{n} s',
    rel_min: '{n} min',
    rel_hr: '{n} h',
    rel_days: '{n} días',
    rel_years: '{n} años',
    rel_future: 'dentro de {t}',
    rel_past: 'hace {t}',
  },
  pt: {
    title: 'Conversor de timestamp',
    inputLabel: 'Entrada — segundos Unix, milissegundos, ISO 8601 ou RFC 2822',
    now: 'Agora',
    timezone: 'Fuso horário',
    enterHint: 'Digite um timestamp para converter.',
    parseFailed: 'Falha ao interpretar',
    detected: 'Detectado',
    unixSeconds: 'Segundos Unix',
    unixMillis: 'Milissegundos Unix',
    inZone: 'Em {zone}',
    relative: 'Relativo',
    error_tooLarge:
      'Esse número é grande demais para um timestamp Unix em segundos ou milissegundos.',
    error_unrecognized:
      'Formato de timestamp não reconhecido. Tente segundos/milissegundos Unix, ISO 8601 ou RFC 2822.',
    format_unixSeconds: 'segundos Unix',
    format_unixMillis: 'milissegundos Unix',
    format_iso: 'ISO 8601',
    format_rfc2822: 'RFC 2822',
    format_unknown: 'desconhecido',
    rel_sec: '{n} s',
    rel_min: '{n} min',
    rel_hr: '{n} h',
    rel_days: '{n} dias',
    rel_years: '{n} anos',
    rel_future: 'em {t}',
    rel_past: 'há {t}',
  },
};
