import type { LocalizedStrings } from '@anytools/ui';

const EN = {
  title: 'Word & Character Counter',
  description: 'Live counts. Twitter/X and Instagram bio limits tracked.',
  placeholder: 'Paste or type your text...',
  textToCount: 'Text to count',
  words: 'Words',
  characters: 'Characters',
  charactersNoSpaces: 'Characters (no spaces)',
  sentences: 'Sentences',
  paragraphs: 'Paragraphs',
  platformLimits: 'Platform limits',
  twitter: 'Twitter / X',
  instagramBio: 'Instagram bio',
};

export const STRINGS: LocalizedStrings<typeof EN> = {
  en: EN,
  vi: {
    title: 'Đếm từ & ký tự',
    description: 'Đếm trực tiếp. Theo dõi giới hạn Twitter/X và tiểu sử Instagram.',
    placeholder: 'Dán hoặc nhập văn bản của bạn...',
    textToCount: 'Văn bản cần đếm',
    words: 'Số từ',
    characters: 'Số ký tự',
    charactersNoSpaces: 'Số ký tự (không tính khoảng trắng)',
    sentences: 'Số câu',
    paragraphs: 'Số đoạn',
    platformLimits: 'Giới hạn nền tảng',
    twitter: 'Twitter / X',
    instagramBio: 'Tiểu sử Instagram',
  },
  es: {
    title: 'Contador de palabras y caracteres',
    description: 'Conteo en vivo. Se controlan los límites de Twitter/X y la bio de Instagram.',
    placeholder: 'Pega o escribe tu texto...',
    textToCount: 'Texto a contar',
    words: 'Palabras',
    characters: 'Caracteres',
    charactersNoSpaces: 'Caracteres (sin espacios)',
    sentences: 'Oraciones',
    paragraphs: 'Párrafos',
    platformLimits: 'Límites por plataforma',
    twitter: 'Twitter / X',
    instagramBio: 'Bio de Instagram',
  },
  pt: {
    title: 'Contador de palavras e caracteres',
    description: 'Contagem ao vivo. Limites do Twitter/X e da bio do Instagram monitorados.',
    placeholder: 'Cole ou digite seu texto...',
    textToCount: 'Texto a contar',
    words: 'Palavras',
    characters: 'Caracteres',
    charactersNoSpaces: 'Caracteres (sem espaços)',
    sentences: 'Frases',
    paragraphs: 'Parágrafos',
    platformLimits: 'Limites por plataforma',
    twitter: 'Twitter / X',
    instagramBio: 'Bio do Instagram',
  },
};
