import type { LocalizedStrings } from '@anytools/ui';

const EN = {
  title: 'Image to Text (OCR)',
  dropLabel: 'Images to read',
  failed: 'The image could not be read.',
  stage_starting: 'Starting the recogniser',
  stage_loadingLang: 'Loading the language',
  stage_reading: 'Reading',
  stage_working: 'Working',
  language: 'Language of the text',
  lang_eng: 'English',
  lang_vie: 'Vietnamese',
  lang_spa: 'Spanish',
  lang_por: 'Portuguese',
  keepLineBreaks: 'Keep line breaks inside each block',
  reading: 'Reading…',
  recognize: 'Recognize text',
  stopping: 'Stopping…',
  stoppingNote:
    'Stopping. The run is abandoned, so no text comes out of it — read the images in smaller batches if a full one is too long.',
  progressLine: '{stage} — image {index} of {total} ({pct}%)',
  avgConfidence: 'Average confidence {conf}%',
  acrossImages: ' across {n} images',
  failedNote: '{failed} of {total} could not be read at all — see the list below.',
  lowConfidence:
    'Below about 70% the output usually needs correcting — a sharper, straighter, higher-resolution image is the fix.',
  checkText: 'Check the text below before using it; OCR is never exact.',
  recognisedText: 'Recognised text',
  downloadTxt: 'Download .txt',
  itemLine: '{words} words, {conf}% confidence',
  error_fileUnreadable: 'This file could not be read.',
};

export const STRINGS: LocalizedStrings<typeof EN> = {
  en: EN,
  vi: {
    title: 'Ảnh sang văn bản (OCR)',
    dropLabel: 'Ảnh cần đọc',
    failed: 'Không đọc được ảnh.',
    stage_starting: 'Đang khởi động bộ nhận dạng',
    stage_loadingLang: 'Đang tải ngôn ngữ',
    stage_reading: 'Đang đọc',
    stage_working: 'Đang xử lý',
    language: 'Ngôn ngữ của văn bản',
    lang_eng: 'Tiếng Anh',
    lang_vie: 'Tiếng Việt',
    lang_spa: 'Tiếng Tây Ban Nha',
    lang_por: 'Tiếng Bồ Đào Nha',
    keepLineBreaks: 'Giữ ngắt dòng trong từng khối',
    reading: 'Đang đọc…',
    recognize: 'Nhận dạng văn bản',
    stopping: 'Đang dừng…',
    stoppingNote:
      'Đang dừng. Lượt chạy bị hủy nên không có văn bản nào được xuất ra — hãy đọc ảnh theo từng đợt nhỏ hơn nếu một đợt quá lâu.',
    progressLine: '{stage} — ảnh {index}/{total} ({pct}%)',
    avgConfidence: 'Độ tin cậy trung bình {conf}%',
    acrossImages: ' trên {n} ảnh',
    failedNote: '{failed}/{total} ảnh hoàn toàn không đọc được — xem danh sách bên dưới.',
    lowConfidence:
      'Dưới khoảng 70% thì kết quả thường cần sửa lại — ảnh sắc nét hơn, thẳng hơn, độ phân giải cao hơn là cách khắc phục.',
    checkText:
      'Hãy kiểm tra văn bản bên dưới trước khi dùng; OCR không bao giờ chính xác tuyệt đối.',
    recognisedText: 'Văn bản đã nhận dạng',
    downloadTxt: 'Tải .txt',
    itemLine: '{words} từ, độ tin cậy {conf}%',
    error_fileUnreadable: 'Không đọc được tệp này.',
  },
  es: {
    title: 'Imagen a texto (OCR)',
    dropLabel: 'Imágenes a leer',
    failed: 'No se pudo leer la imagen.',
    stage_starting: 'Iniciando el reconocedor',
    stage_loadingLang: 'Cargando el idioma',
    stage_reading: 'Leyendo',
    stage_working: 'Trabajando',
    language: 'Idioma del texto',
    lang_eng: 'Inglés',
    lang_vie: 'Vietnamita',
    lang_spa: 'Español',
    lang_por: 'Portugués',
    keepLineBreaks: 'Conservar los saltos de línea dentro de cada bloque',
    reading: 'Leyendo…',
    recognize: 'Reconocer texto',
    stopping: 'Deteniendo…',
    stoppingNote:
      'Deteniendo. La ejecución se abandona, así que no sale texto de ella — lee las imágenes en lotes más pequeños si uno completo tarda demasiado.',
    progressLine: '{stage} — imagen {index} de {total} ({pct}%)',
    avgConfidence: 'Confianza media {conf}%',
    acrossImages: ' en {n} imágenes',
    failedNote: '{failed} de {total} no se pudieron leer en absoluto — mira la lista de abajo.',
    lowConfidence:
      'Por debajo de un 70% el resultado suele necesitar corrección — una imagen más nítida, más recta y de mayor resolución es la solución.',
    checkText: 'Revisa el texto de abajo antes de usarlo; el OCR nunca es exacto.',
    recognisedText: 'Texto reconocido',
    downloadTxt: 'Descargar .txt',
    itemLine: '{words} palabras, {conf}% de confianza',
    error_fileUnreadable: 'No se pudo leer este archivo.',
  },
  pt: {
    title: 'Imagem para texto (OCR)',
    dropLabel: 'Imagens a ler',
    failed: 'Não foi possível ler a imagem.',
    stage_starting: 'Iniciando o reconhecedor',
    stage_loadingLang: 'Carregando o idioma',
    stage_reading: 'Lendo',
    stage_working: 'Trabalhando',
    language: 'Idioma do texto',
    lang_eng: 'Inglês',
    lang_vie: 'Vietnamita',
    lang_spa: 'Espanhol',
    lang_por: 'Português',
    keepLineBreaks: 'Manter as quebras de linha dentro de cada bloco',
    reading: 'Lendo…',
    recognize: 'Reconhecer texto',
    stopping: 'Parando…',
    stoppingNote:
      'Parando. A execução é abandonada, então nenhum texto sai dela — leia as imagens em lotes menores se um lote completo demorar demais.',
    progressLine: '{stage} — imagem {index} de {total} ({pct}%)',
    avgConfidence: 'Confiança média {conf}%',
    acrossImages: ' em {n} imagens',
    failedNote: '{failed} de {total} não puderam ser lidas — veja a lista abaixo.',
    lowConfidence:
      'Abaixo de cerca de 70% o resultado costuma precisar de correção — uma imagem mais nítida, mais reta e de maior resolução é a solução.',
    checkText: 'Confira o texto abaixo antes de usá-lo; OCR nunca é exato.',
    recognisedText: 'Texto reconhecido',
    downloadTxt: 'Baixar .txt',
    itemLine: '{words} palavras, {conf}% de confiança',
    error_fileUnreadable: 'Não foi possível ler este arquivo.',
  },
};
