import type { LocalizedStrings } from '@anytools/ui';

const EN = {
  title: 'Rotate PDF',
  dropLabel: 'PDF to rotate',
  couldNotReadPdf: 'Could not read PDF',
  failed: 'Rotation failed',
  pageCountOne: '{n} page',
  pageCountMany: '{n} pages',
  rotateBy: 'Rotate clockwise by',
  whichPages: 'Which pages',
  everyPage: 'Every page',
  onlyThese: 'Only these pages',
  rotating: 'Rotating…',
  rotate: 'Rotate {angle}°',
  rotatedOne: 'Rotated {n} of {total} page.',
  rotatedMany: 'Rotated {n} of {total} pages.',
  download: 'Download {name}',
};

export const STRINGS: LocalizedStrings<typeof EN> = {
  en: EN,
  vi: {
    title: 'Xoay PDF',
    dropLabel: 'PDF cần xoay',
    couldNotReadPdf: 'Không đọc được PDF',
    failed: 'Xoay thất bại',
    pageCountOne: '{n} trang',
    pageCountMany: '{n} trang',
    rotateBy: 'Xoay theo chiều kim đồng hồ',
    whichPages: 'Trang nào',
    everyPage: 'Tất cả các trang',
    onlyThese: 'Chỉ những trang này',
    rotating: 'Đang xoay…',
    rotate: 'Xoay {angle}°',
    rotatedOne: 'Đã xoay {n}/{total} trang.',
    rotatedMany: 'Đã xoay {n}/{total} trang.',
    download: 'Tải {name}',
  },
  es: {
    title: 'Rotar PDF',
    dropLabel: 'PDF a rotar',
    couldNotReadPdf: 'No se pudo leer el PDF',
    failed: 'La rotación falló',
    pageCountOne: '{n} página',
    pageCountMany: '{n} páginas',
    rotateBy: 'Rotar en sentido horario',
    whichPages: 'Qué páginas',
    everyPage: 'Todas las páginas',
    onlyThese: 'Solo estas páginas',
    rotating: 'Rotando…',
    rotate: 'Rotar {angle}°',
    rotatedOne: 'Rotada {n} de {total} página.',
    rotatedMany: 'Rotadas {n} de {total} páginas.',
    download: 'Descargar {name}',
  },
  pt: {
    title: 'Girar PDF',
    dropLabel: 'PDF a girar',
    couldNotReadPdf: 'Não foi possível ler o PDF',
    failed: 'A rotação falhou',
    pageCountOne: '{n} página',
    pageCountMany: '{n} páginas',
    rotateBy: 'Girar no sentido horário',
    whichPages: 'Quais páginas',
    everyPage: 'Todas as páginas',
    onlyThese: 'Apenas estas páginas',
    rotating: 'Girando…',
    rotate: 'Girar {angle}°',
    rotatedOne: 'Girada {n} de {total} página.',
    rotatedMany: 'Giradas {n} de {total} páginas.',
    download: 'Baixar {name}',
  },
};
