import type { LocalizedStrings } from '@anytools/ui';

const EN = {
  title: 'CSS Gradient Generator',
  gradientPreview: 'Gradient preview',
  type: 'Type',
  linear: 'Linear',
  radial: 'Radial',
  conic: 'Conic',
  repeating: 'Repeating',
  startAngle: 'Start angle',
  angle: 'Angle',
  shape: 'Shape',
  circle: 'Circle',
  ellipse: 'Ellipse',
  size: 'Size',
  radialSize: 'Radial size',
  centreX: 'Centre X',
  centreY: 'Centre Y',
  colourStops: 'Colour stops',
  stopPicker: 'Stop {n} colour picker',
  stopColour: 'Stop {n} colour',
  stopPosition: 'Stop {n} position in percent',
  stopHandle: 'Stop {n} at {pct}% — drag, or use the arrow keys',
  removeStop: 'Remove stop {n}',
  addStop: 'Add stop',
  presets: 'Presets',
  preset_Sunset: 'Sunset',
  preset_Ocean: 'Ocean',
  preset_Peach: 'Peach',
  preset_Midnight: 'Midnight',
  preset_Mint: 'Mint',
  preset_Spotlight: 'Spotlight',
  preset_ColourWheel: 'Colour wheel',
  preset_Stripes: 'Stripes',
  editExisting: 'Edit an existing gradient',
  pasteCss: 'Paste CSS to load',
  loadCss: 'Load CSS',
};

export const STRINGS: LocalizedStrings<typeof EN> = {
  en: EN,
  vi: {
    title: 'Tạo CSS Gradient',
    gradientPreview: 'Xem trước gradient',
    type: 'Kiểu',
    linear: 'Tuyến tính',
    radial: 'Tỏa tròn',
    conic: 'Hình nón',
    repeating: 'Lặp lại',
    startAngle: 'Góc bắt đầu',
    angle: 'Góc',
    shape: 'Hình dạng',
    circle: 'Tròn',
    ellipse: 'Elip',
    size: 'Kích thước',
    radialSize: 'Kích thước tỏa tròn',
    centreX: 'Tâm X',
    centreY: 'Tâm Y',
    colourStops: 'Điểm màu',
    stopPicker: 'Bộ chọn màu điểm {n}',
    stopColour: 'Màu điểm {n}',
    stopPosition: 'Vị trí điểm {n} theo phần trăm',
    stopHandle: 'Điểm {n} tại {pct}% — kéo hoặc dùng phím mũi tên',
    removeStop: 'Xóa điểm {n}',
    addStop: 'Thêm điểm màu',
    presets: 'Mẫu có sẵn',
    preset_Sunset: 'Hoàng hôn',
    preset_Ocean: 'Đại dương',
    preset_Peach: 'Đào',
    preset_Midnight: 'Nửa đêm',
    preset_Mint: 'Bạc hà',
    preset_Spotlight: 'Đèn rọi',
    preset_ColourWheel: 'Vòng màu',
    preset_Stripes: 'Kẻ sọc',
    editExisting: 'Chỉnh sửa gradient có sẵn',
    pasteCss: 'Dán CSS để tải',
    loadCss: 'Tải CSS',
  },
  es: {
    title: 'Generador de degradados CSS',
    gradientPreview: 'Vista previa del degradado',
    type: 'Tipo',
    linear: 'Lineal',
    radial: 'Radial',
    conic: 'Cónico',
    repeating: 'Repetido',
    startAngle: 'Ángulo inicial',
    angle: 'Ángulo',
    shape: 'Forma',
    circle: 'Círculo',
    ellipse: 'Elipse',
    size: 'Tamaño',
    radialSize: 'Tamaño radial',
    centreX: 'Centro X',
    centreY: 'Centro Y',
    colourStops: 'Paradas de color',
    stopPicker: 'Selector de color de la parada {n}',
    stopColour: 'Color de la parada {n}',
    stopPosition: 'Posición de la parada {n} en porcentaje',
    stopHandle: 'Parada {n} en {pct}%: arrastra o usa las flechas',
    removeStop: 'Quitar parada {n}',
    addStop: 'Añadir parada',
    presets: 'Preajustes',
    preset_Sunset: 'Atardecer',
    preset_Ocean: 'Océano',
    preset_Peach: 'Melocotón',
    preset_Midnight: 'Medianoche',
    preset_Mint: 'Menta',
    preset_Spotlight: 'Foco',
    preset_ColourWheel: 'Rueda de color',
    preset_Stripes: 'Rayas',
    editExisting: 'Editar un degradado existente',
    pasteCss: 'Pega CSS para cargarlo',
    loadCss: 'Cargar CSS',
  },
  pt: {
    title: 'Gerador de gradientes CSS',
    gradientPreview: 'Pré-visualização do gradiente',
    type: 'Tipo',
    linear: 'Linear',
    radial: 'Radial',
    conic: 'Cônico',
    repeating: 'Repetido',
    startAngle: 'Ângulo inicial',
    angle: 'Ângulo',
    shape: 'Forma',
    circle: 'Círculo',
    ellipse: 'Elipse',
    size: 'Tamanho',
    radialSize: 'Tamanho radial',
    centreX: 'Centro X',
    centreY: 'Centro Y',
    colourStops: 'Paradas de cor',
    stopPicker: 'Seletor de cor da parada {n}',
    stopColour: 'Cor da parada {n}',
    stopPosition: 'Posição da parada {n} em porcentagem',
    stopHandle: 'Parada {n} em {pct}%: arraste ou use as setas',
    removeStop: 'Remover parada {n}',
    addStop: 'Adicionar parada',
    presets: 'Predefinições',
    preset_Sunset: 'Pôr do sol',
    preset_Ocean: 'Oceano',
    preset_Peach: 'Pêssego',
    preset_Midnight: 'Meia-noite',
    preset_Mint: 'Menta',
    preset_Spotlight: 'Holofote',
    preset_ColourWheel: 'Roda de cores',
    preset_Stripes: 'Listras',
    editExisting: 'Editar um gradiente existente',
    pasteCss: 'Cole o CSS para carregar',
    loadCss: 'Carregar CSS',
  },
};
