import type { LocalizedStrings } from '@anytools/ui';

const EN = {
  title: 'JWT Sign & Verify',
  tabSign: 'Sign',
  tabVerify: 'Verify',
  algorithmLabel: 'Algorithm',
  algoHmacGroup: 'HMAC (shared secret)',
  algoRsaEcGroup: 'RSA / EC (key pair)',
  // Sign tab
  payloadLabel: 'Payload (JSON)',
  secretLabel: 'Secret',
  privateKeyLabel: 'Private key (PEM PKCS#8)',
  expiresInLabel: 'Expires in',
  expiresInHint: 'e.g. "1h", "7d" — leave empty to omit the "exp" claim',
  signButton: 'Sign',
  signing: 'Signing…',
  signFailed: 'Could not sign the token.',
  signedTokenLabel: 'Signed JWT',
  // Verify tab
  tokenLabel: 'JWT token',
  publicKeyLabel: 'Public key (PEM SPKI)',
  verifyButton: 'Verify',
  verifying: 'Verifying…',
  verifyFailed: 'Could not verify the token.',
  headerLabel: 'Header',
  payloadOutLabel: 'Payload',
  // Verify statuses (badges)
  statusValid: 'Signature valid',
  statusInvalidSignature: 'Invalid signature',
  statusExpired: 'Expired',
  statusNotYetValid: 'Not yet valid',
  statusAlgRejected: 'Algorithm rejected',
  statusMalformed: 'Malformed token',
  privacySign:
    'Signing happens in your browser with WebCrypto. A private key pasted here never leaves this tab — but do not sign production tokens with a browser tool; use your backend.',
  privacyVerify:
    'Verification happens in your browser. Nothing you paste here — token, secret, or key — is ever sent anywhere.',
  error_invalidPayloadJson: 'Payload must be a JSON object, e.g. {"sub":"123"}.',
  error_missingSecret: 'Enter a secret / key first.',
  // {detail} is the underlying jose/WebCrypto error message.
  error_invalidPrivateKey:
    'Could not read the private key: {detail}. Expected a PEM PKCS#8 key ("-----BEGIN PRIVATE KEY-----"), matching the selected algorithm.',
  error_invalidPublicKey:
    'Could not read the public key: {detail}. Expected a PEM SPKI key ("-----BEGIN PUBLIC KEY-----"), matching the selected algorithm.',
  error_signFailed: 'Signing failed: {detail}',
};

export const STRINGS: LocalizedStrings<typeof EN> = {
  en: EN,
  vi: {
    title: 'Ký & Xác minh JWT',
    tabSign: 'Ký',
    tabVerify: 'Xác minh',
    algorithmLabel: 'Thuật toán',
    algoHmacGroup: 'HMAC (secret chung)',
    algoRsaEcGroup: 'RSA / EC (cặp khoá)',
    payloadLabel: 'Payload (JSON)',
    secretLabel: 'Secret',
    privateKeyLabel: 'Khoá riêng (PEM PKCS#8)',
    expiresInLabel: 'Hết hạn sau',
    expiresInHint: 'vd "1h", "7d" — để trống nếu không cần claim "exp"',
    signButton: 'Ký',
    signing: 'Đang ký…',
    signFailed: 'Không thể ký token.',
    signedTokenLabel: 'JWT đã ký',
    tokenLabel: 'Chuỗi JWT',
    publicKeyLabel: 'Khoá công khai (PEM SPKI)',
    verifyButton: 'Xác minh',
    verifying: 'Đang xác minh…',
    verifyFailed: 'Không thể xác minh token.',
    headerLabel: 'Header',
    payloadOutLabel: 'Payload',
    statusValid: 'Chữ ký hợp lệ',
    statusInvalidSignature: 'Chữ ký sai',
    statusExpired: 'Đã hết hạn',
    statusNotYetValid: 'Chưa tới hiệu lực',
    statusAlgRejected: 'Thuật toán bị từ chối',
    statusMalformed: 'Token không hợp lệ',
    privacySign:
      'Việc ký diễn ra trong trình duyệt bằng WebCrypto. Khoá riêng dán vào đây không rời khỏi tab — nhưng đừng ký token production bằng công cụ trình duyệt, hãy dùng backend của bạn.',
    privacyVerify:
      'Việc xác minh diễn ra trong trình duyệt. Mọi thứ bạn dán vào đây — token, secret, khoá — không gửi đi đâu cả.',
    error_invalidPayloadJson: 'Payload phải là một JSON object, vd {"sub":"123"}.',
    error_missingSecret: 'Nhập secret / khoá trước đã.',
    error_invalidPrivateKey:
      'Không đọc được khoá riêng: {detail}. Cần khoá PEM PKCS#8 ("-----BEGIN PRIVATE KEY-----"), đúng thuật toán đã chọn.',
    error_invalidPublicKey:
      'Không đọc được khoá công khai: {detail}. Cần khoá PEM SPKI ("-----BEGIN PUBLIC KEY-----"), đúng thuật toán đã chọn.',
    error_signFailed: 'Ký thất bại: {detail}',
  },
  es: {
    title: 'Firmar y verificar JWT',
    tabSign: 'Firmar',
    tabVerify: 'Verificar',
    algorithmLabel: 'Algoritmo',
    algoHmacGroup: 'HMAC (secreto compartido)',
    algoRsaEcGroup: 'RSA / EC (par de claves)',
    payloadLabel: 'Payload (JSON)',
    secretLabel: 'Secreto',
    privateKeyLabel: 'Clave privada (PEM PKCS#8)',
    expiresInLabel: 'Expira en',
    expiresInHint: 'ej. "1h", "7d" — deja vacío para omitir el claim "exp"',
    signButton: 'Firmar',
    signing: 'Firmando…',
    signFailed: 'No se pudo firmar el token.',
    signedTokenLabel: 'JWT firmado',
    tokenLabel: 'Token JWT',
    publicKeyLabel: 'Clave pública (PEM SPKI)',
    verifyButton: 'Verificar',
    verifying: 'Verificando…',
    verifyFailed: 'No se pudo verificar el token.',
    headerLabel: 'Encabezado',
    payloadOutLabel: 'Payload',
    statusValid: 'Firma válida',
    statusInvalidSignature: 'Firma inválida',
    statusExpired: 'Expirado',
    statusNotYetValid: 'Aún no válido',
    statusAlgRejected: 'Algoritmo rechazado',
    statusMalformed: 'Token inválido',
    privacySign:
      'La firma ocurre en tu navegador con WebCrypto. Una clave privada pegada aquí nunca sale de esta pestaña — pero no firmes tokens de producción con una herramienta de navegador; usa tu backend.',
    privacyVerify:
      'La verificación ocurre en tu navegador. Nada de lo que pegues aquí — token, secreto o clave — se envía a ningún lado.',
    error_invalidPayloadJson: 'El payload debe ser un objeto JSON, ej. {"sub":"123"}.',
    error_missingSecret: 'Ingresa un secreto / clave primero.',
    error_invalidPrivateKey:
      'No se pudo leer la clave privada: {detail}. Se espera una clave PEM PKCS#8 ("-----BEGIN PRIVATE KEY-----"), acorde al algoritmo elegido.',
    error_invalidPublicKey:
      'No se pudo leer la clave pública: {detail}. Se espera una clave PEM SPKI ("-----BEGIN PUBLIC KEY-----"), acorde al algoritmo elegido.',
    error_signFailed: 'Falló la firma: {detail}',
  },
  pt: {
    title: 'Assinar e verificar JWT',
    tabSign: 'Assinar',
    tabVerify: 'Verificar',
    algorithmLabel: 'Algoritmo',
    algoHmacGroup: 'HMAC (segredo compartilhado)',
    algoRsaEcGroup: 'RSA / EC (par de chaves)',
    payloadLabel: 'Payload (JSON)',
    secretLabel: 'Segredo',
    privateKeyLabel: 'Chave privada (PEM PKCS#8)',
    expiresInLabel: 'Expira em',
    expiresInHint: 'ex. "1h", "7d" — deixe vazio para omitir o claim "exp"',
    signButton: 'Assinar',
    signing: 'Assinando…',
    signFailed: 'Não foi possível assinar o token.',
    signedTokenLabel: 'JWT assinado',
    tokenLabel: 'Token JWT',
    publicKeyLabel: 'Chave pública (PEM SPKI)',
    verifyButton: 'Verificar',
    verifying: 'Verificando…',
    verifyFailed: 'Não foi possível verificar o token.',
    headerLabel: 'Cabeçalho',
    payloadOutLabel: 'Payload',
    statusValid: 'Assinatura válida',
    statusInvalidSignature: 'Assinatura inválida',
    statusExpired: 'Expirado',
    statusNotYetValid: 'Ainda não válido',
    statusAlgRejected: 'Algoritmo rejeitado',
    statusMalformed: 'Token inválido',
    privacySign:
      'A assinatura acontece no seu navegador com WebCrypto. Uma chave privada colada aqui nunca sai desta aba — mas não assine tokens de produção com uma ferramenta de navegador; use seu backend.',
    privacyVerify:
      'A verificação acontece no seu navegador. Nada do que você cola aqui — token, segredo ou chave — é enviado a lugar nenhum.',
    error_invalidPayloadJson: 'O payload deve ser um objeto JSON, ex. {"sub":"123"}.',
    error_missingSecret: 'Informe um segredo / chave primeiro.',
    error_invalidPrivateKey:
      'Não foi possível ler a chave privada: {detail}. Esperado uma chave PEM PKCS#8 ("-----BEGIN PRIVATE KEY-----"), compatível com o algoritmo escolhido.',
    error_invalidPublicKey:
      'Não foi possível ler a chave pública: {detail}. Esperado uma chave PEM SPKI ("-----BEGIN PUBLIC KEY-----"), compatível com o algoritmo escolhido.',
    error_signFailed: 'Falha ao assinar: {detail}',
  },
};
