import type { LocalizedStrings } from '@anytools/ui';

const EN = {
  title: 'PDF Password',
  modeLock: 'Add password',
  modeUnlock: 'Remove password',
  dropLabelLock: 'PDF to lock',
  dropLabelUnlock: 'PDF to unlock',

  userPasswordLabel: 'Password to open the file',
  ownerPasswordLabel: 'Owner password (optional)',
  ownerPasswordHint:
    'Restricts printing/editing without it. Leave blank to reuse the password above.',
  permissionsLegend: 'Allow the password holder to',
  permPrinting: 'Print',
  permCopying: 'Copy text and images',
  permModifying: 'Edit the document',
  permAnnotating: 'Comment and fill forms',
  lockButton: 'Lock PDF',
  locking: 'Locking…',
  lockedOne: 'Locked. 1 page, protected with AES-256.',
  lockedMany: 'Locked. {n} pages, protected with AES-256.',
  downloadLocked: 'Download {name}',

  unlockPasswordLabel: 'Password',
  unlockButton: 'Remove password',
  unlocking: 'Removing…',
  continueAnyway: 'Continue anyway',
  cancel: 'Cancel',
  formWarningOne:
    'This PDF has 1 form field. Removing the password will drop it, along with any annotations, bookmarks and document metadata not attached to a page.',
  formWarningMany:
    'This PDF has {n} form fields. Removing the password will drop them, along with any annotations, bookmarks and document metadata not attached to a page.',
  unlockedOne: 'Password removed. 1 page kept.',
  unlockedMany: 'Password removed. {n} pages kept.',
  downloadUnlocked: 'Download {name}',

  couldNotReadPdf: 'Could not read PDF',
  failed: 'Failed',
  error_passwordRequired: 'Enter a password to lock the PDF with.',
  error_unlockPasswordRequired: "Enter the PDF's password to remove it.",
  error_wrongPassword: 'That password did not open "{name}".',
  error_alreadyLocked: '"{name}" already has a password. Remove it first, then add the new one.',
};

export const STRINGS: LocalizedStrings<typeof EN> = {
  en: EN,
  vi: {
    title: 'Mật khẩu PDF',
    modeLock: 'Đặt mật khẩu',
    modeUnlock: 'Gỡ mật khẩu',
    dropLabelLock: 'PDF cần khóa',
    dropLabelUnlock: 'PDF cần mở khóa',
    userPasswordLabel: 'Mật khẩu để mở tệp',
    ownerPasswordLabel: 'Mật khẩu chủ sở hữu (tuỳ chọn)',
    ownerPasswordHint:
      'Hạn chế in/sửa nếu không có mật khẩu này. Để trống sẽ dùng chung mật khẩu ở trên.',
    permissionsLegend: 'Cho phép người có mật khẩu',
    permPrinting: 'In tài liệu',
    permCopying: 'Sao chép văn bản và hình ảnh',
    permModifying: 'Chỉnh sửa tài liệu',
    permAnnotating: 'Bình luận và điền biểu mẫu',
    lockButton: 'Khóa PDF',
    locking: 'Đang khóa…',
    lockedOne: 'Đã khóa. 1 trang, bảo vệ bằng AES-256.',
    lockedMany: 'Đã khóa. {n} trang, bảo vệ bằng AES-256.',
    downloadLocked: 'Tải {name}',
    unlockPasswordLabel: 'Mật khẩu',
    unlockButton: 'Gỡ mật khẩu',
    unlocking: 'Đang gỡ…',
    continueAnyway: 'Vẫn tiếp tục',
    cancel: 'Hủy',
    formWarningOne:
      'PDF này có 1 trường biểu mẫu. Gỡ mật khẩu sẽ làm mất trường đó, cùng mọi chú thích, dấu trang và metadata không gắn vào trang.',
    formWarningMany:
      'PDF này có {n} trường biểu mẫu. Gỡ mật khẩu sẽ làm mất các trường đó, cùng mọi chú thích, dấu trang và metadata không gắn vào trang.',
    unlockedOne: 'Đã gỡ mật khẩu. Giữ nguyên 1 trang.',
    unlockedMany: 'Đã gỡ mật khẩu. Giữ nguyên {n} trang.',
    downloadUnlocked: 'Tải {name}',
    couldNotReadPdf: 'Không đọc được PDF',
    failed: 'Thất bại',
    error_passwordRequired: 'Nhập mật khẩu để khóa PDF.',
    error_unlockPasswordRequired: 'Nhập mật khẩu của PDF để gỡ nó.',
    error_wrongPassword: 'Mật khẩu đó không mở được "{name}".',
    error_alreadyLocked: '"{name}" đã có mật khẩu. Hãy gỡ trước rồi mới đặt mật khẩu mới.',
  },
  es: {
    title: 'Contraseña de PDF',
    modeLock: 'Añadir contraseña',
    modeUnlock: 'Quitar contraseña',
    dropLabelLock: 'PDF a proteger',
    dropLabelUnlock: 'PDF a desbloquear',
    userPasswordLabel: 'Contraseña para abrir el archivo',
    ownerPasswordLabel: 'Contraseña de propietario (opcional)',
    ownerPasswordHint:
      'Restringe imprimir/editar sin ella. Déjala en blanco para reutilizar la contraseña de arriba.',
    permissionsLegend: 'Permitir a quien tenga la contraseña',
    permPrinting: 'Imprimir',
    permCopying: 'Copiar texto e imágenes',
    permModifying: 'Editar el documento',
    permAnnotating: 'Comentar y rellenar formularios',
    lockButton: 'Proteger PDF',
    locking: 'Protegiendo…',
    lockedOne: 'Protegido. 1 página, cifrado con AES-256.',
    lockedMany: 'Protegido. {n} páginas, cifrado con AES-256.',
    downloadLocked: 'Descargar {name}',
    unlockPasswordLabel: 'Contraseña',
    unlockButton: 'Quitar contraseña',
    unlocking: 'Quitando…',
    continueAnyway: 'Continuar de todos modos',
    cancel: 'Cancelar',
    formWarningOne:
      'Este PDF tiene 1 campo de formulario. Quitar la contraseña lo eliminará, junto con anotaciones, marcadores y metadatos no asociados a una página.',
    formWarningMany:
      'Este PDF tiene {n} campos de formulario. Quitar la contraseña los eliminará, junto con anotaciones, marcadores y metadatos no asociados a una página.',
    unlockedOne: 'Contraseña quitada. Se conservó 1 página.',
    unlockedMany: 'Contraseña quitada. Se conservaron {n} páginas.',
    downloadUnlocked: 'Descargar {name}',
    couldNotReadPdf: 'No se pudo leer el PDF',
    failed: 'Falló',
    error_passwordRequired: 'Introduce una contraseña para proteger el PDF.',
    error_unlockPasswordRequired: 'Introduce la contraseña del PDF para quitarla.',
    error_wrongPassword: 'Esa contraseña no abrió "{name}".',
    error_alreadyLocked:
      '"{name}" ya tiene una contraseña. Quítala primero y luego añade la nueva.',
  },
  pt: {
    title: 'Senha de PDF',
    modeLock: 'Adicionar senha',
    modeUnlock: 'Remover senha',
    dropLabelLock: 'PDF a proteger',
    dropLabelUnlock: 'PDF a desbloquear',
    userPasswordLabel: 'Senha para abrir o arquivo',
    ownerPasswordLabel: 'Senha de proprietário (opcional)',
    ownerPasswordHint:
      'Restringe impressão/edição sem ela. Deixe em branco para reutilizar a senha acima.',
    permissionsLegend: 'Permitir a quem tiver a senha',
    permPrinting: 'Imprimir',
    permCopying: 'Copiar texto e imagens',
    permModifying: 'Editar o documento',
    permAnnotating: 'Comentar e preencher formulários',
    lockButton: 'Proteger PDF',
    locking: 'Protegendo…',
    lockedOne: 'Protegido. 1 página, criptografado com AES-256.',
    lockedMany: 'Protegido. {n} páginas, criptografadas com AES-256.',
    downloadLocked: 'Baixar {name}',
    unlockPasswordLabel: 'Senha',
    unlockButton: 'Remover senha',
    unlocking: 'Removendo…',
    continueAnyway: 'Continuar mesmo assim',
    cancel: 'Cancelar',
    formWarningOne:
      'Este PDF tem 1 campo de formulário. Remover a senha vai descartá-lo, junto com anotações, marcadores e metadados não presos a uma página.',
    formWarningMany:
      'Este PDF tem {n} campos de formulário. Remover a senha vai descartá-los, junto com anotações, marcadores e metadados não presos a uma página.',
    unlockedOne: 'Senha removida. 1 página mantida.',
    unlockedMany: 'Senha removida. {n} páginas mantidas.',
    downloadUnlocked: 'Baixar {name}',
    couldNotReadPdf: 'Não foi possível ler o PDF',
    failed: 'Falhou',
    error_passwordRequired: 'Informe uma senha para proteger o PDF.',
    error_unlockPasswordRequired: 'Informe a senha do PDF para removê-la.',
    error_wrongPassword: 'Essa senha não abriu "{name}".',
    error_alreadyLocked: '"{name}" já tem uma senha. Remova-a primeiro e depois adicione a nova.',
  },
};
