import type { LocalizedStrings } from '@anytools/ui';

const EN = {
  title: 'Slugify',
  single: 'Single',
  bulk: 'Bulk (line-by-line)',
  separator: 'Separator:',
  hyphen: '- (hyphen)',
  underscore: '_ (underscore)',
  dot: '. (dot)',
  locale: 'Locale:',
  lowercase: 'lowercase',
  strict: 'strict (strip punctuation)',
  slugOne: '{n} slug',
  slugMany: '{n} slugs',
};

export const STRINGS: LocalizedStrings<typeof EN> = {
  en: EN,
  vi: {
    title: 'Tạo slug',
    single: 'Đơn',
    bulk: 'Hàng loạt (mỗi dòng một)',
    separator: 'Dấu nối:',
    hyphen: '- (gạch ngang)',
    underscore: '_ (gạch dưới)',
    dot: '. (dấu chấm)',
    locale: 'Ngôn ngữ:',
    lowercase: 'chữ thường',
    strict: 'nghiêm ngặt (bỏ dấu câu)',
    slugOne: '{n} slug',
    slugMany: '{n} slug',
  },
  es: {
    title: 'Slugify',
    single: 'Individual',
    bulk: 'En lote (línea por línea)',
    separator: 'Separador:',
    hyphen: '- (guion)',
    underscore: '_ (guion bajo)',
    dot: '. (punto)',
    locale: 'Idioma:',
    lowercase: 'minúsculas',
    strict: 'estricto (quitar puntuación)',
    slugOne: '{n} slug',
    slugMany: '{n} slugs',
  },
  pt: {
    title: 'Slugify',
    single: 'Único',
    bulk: 'Em lote (linha por linha)',
    separator: 'Separador:',
    hyphen: '- (hífen)',
    underscore: '_ (sublinhado)',
    dot: '. (ponto)',
    locale: 'Idioma:',
    lowercase: 'minúsculas',
    strict: 'estrito (remover pontuação)',
    slugOne: '{n} slug',
    slugMany: '{n} slugs',
  },
};
