import type { LocalizedStrings } from '@anytools/ui';

const EN = {
  category: 'Category',
  length: 'Length',
  weight: 'Weight',
  temperature: 'Temp',
  volume: 'Volume',
  speed: 'Speed',
  unitFor: '{label} unit',
  valueFor: '{label} value',
  unit_m: 'Meter (m)',
  unit_cm: 'Centimeter (cm)',
  unit_mm: 'Millimeter (mm)',
  unit_km: 'Kilometer (km)',
  unit_in: 'Inch (in)',
  unit_ft: 'Foot (ft)',
  unit_yd: 'Yard (yd)',
  unit_mi: 'Mile (mi)',
  unit_kg: 'Kilogram (kg)',
  unit_g: 'Gram (g)',
  unit_mg: 'Milligram (mg)',
  unit_t: 'Metric ton (t)',
  unit_lb: 'Pound (lb)',
  unit_oz: 'Ounce (oz)',
  unit_C: 'Celsius (°C)',
  unit_F: 'Fahrenheit (°F)',
  unit_K: 'Kelvin (K)',
  unit_L: 'Liter (L)',
  unit_mL: 'Milliliter (mL)',
  unit_m3: 'Cubic meter (m³)',
  unit_gal_us: 'US gallon',
  unit_gal_uk: 'UK gallon',
  unit_fl_oz: 'US fluid ounce',
  unit_cup: 'US cup',
  unit_mps: 'Meter/second (m/s)',
  unit_kph: 'Kilometer/hour (km/h)',
  unit_mph: 'Mile/hour (mph)',
  unit_kn: 'Knot',
  unit_fps: 'Foot/second (ft/s)',
};

export const STRINGS: LocalizedStrings<typeof EN> = {
  en: EN,
  vi: {
    category: 'Loại',
    length: 'Chiều dài',
    weight: 'Khối lượng',
    temperature: 'Nhiệt độ',
    volume: 'Thể tích',
    speed: 'Tốc độ',
    unitFor: 'Đơn vị {label}',
    valueFor: 'Giá trị {label}',
    unit_m: 'Mét (m)',
    unit_cm: 'Xentimét (cm)',
    unit_mm: 'Milimét (mm)',
    unit_km: 'Kilômét (km)',
    unit_in: 'Inch (in)',
    unit_ft: 'Foot (ft)',
    unit_yd: 'Yard (yd)',
    unit_mi: 'Dặm (mi)',
    unit_kg: 'Kilôgam (kg)',
    unit_g: 'Gam (g)',
    unit_mg: 'Miligam (mg)',
    unit_t: 'Tấn (t)',
    unit_lb: 'Pound (lb)',
    unit_oz: 'Ounce (oz)',
    unit_C: 'Độ C (°C)',
    unit_F: 'Độ F (°F)',
    unit_K: 'Kelvin (K)',
    unit_L: 'Lít (L)',
    unit_mL: 'Mililít (mL)',
    unit_m3: 'Mét khối (m³)',
    unit_gal_us: 'Gallon Mỹ',
    unit_gal_uk: 'Gallon Anh',
    unit_fl_oz: 'Fluid ounce Mỹ',
    unit_cup: 'Cup Mỹ',
    unit_mps: 'Mét/giây (m/s)',
    unit_kph: 'Kilômét/giờ (km/h)',
    unit_mph: 'Dặm/giờ (mph)',
    unit_kn: 'Hải lý/giờ (knot)',
    unit_fps: 'Foot/giây (ft/s)',
  },
  es: {
    category: 'Categoría',
    length: 'Longitud',
    weight: 'Peso',
    temperature: 'Temp.',
    volume: 'Volumen',
    speed: 'Velocidad',
    unitFor: 'Unidad de {label}',
    valueFor: 'Valor de {label}',
    unit_m: 'Metro (m)',
    unit_cm: 'Centímetro (cm)',
    unit_mm: 'Milímetro (mm)',
    unit_km: 'Kilómetro (km)',
    unit_in: 'Pulgada (in)',
    unit_ft: 'Pie (ft)',
    unit_yd: 'Yarda (yd)',
    unit_mi: 'Milla (mi)',
    unit_kg: 'Kilogramo (kg)',
    unit_g: 'Gramo (g)',
    unit_mg: 'Miligramo (mg)',
    unit_t: 'Tonelada (t)',
    unit_lb: 'Libra (lb)',
    unit_oz: 'Onza (oz)',
    unit_C: 'Celsius (°C)',
    unit_F: 'Fahrenheit (°F)',
    unit_K: 'Kelvin (K)',
    unit_L: 'Litro (L)',
    unit_mL: 'Mililitro (mL)',
    unit_m3: 'Metro cúbico (m³)',
    unit_gal_us: 'Galón (EE. UU.)',
    unit_gal_uk: 'Galón (Reino Unido)',
    unit_fl_oz: 'Onza líquida (EE. UU.)',
    unit_cup: 'Taza (EE. UU.)',
    unit_mps: 'Metro/segundo (m/s)',
    unit_kph: 'Kilómetro/hora (km/h)',
    unit_mph: 'Milla/hora (mph)',
    unit_kn: 'Nudo',
    unit_fps: 'Pie/segundo (ft/s)',
  },
  pt: {
    category: 'Categoria',
    length: 'Comprimento',
    weight: 'Peso',
    temperature: 'Temp.',
    volume: 'Volume',
    speed: 'Velocidade',
    unitFor: 'Unidade de {label}',
    valueFor: 'Valor de {label}',
    unit_m: 'Metro (m)',
    unit_cm: 'Centímetro (cm)',
    unit_mm: 'Milímetro (mm)',
    unit_km: 'Quilômetro (km)',
    unit_in: 'Polegada (in)',
    unit_ft: 'Pé (ft)',
    unit_yd: 'Jarda (yd)',
    unit_mi: 'Milha (mi)',
    unit_kg: 'Quilograma (kg)',
    unit_g: 'Grama (g)',
    unit_mg: 'Miligrama (mg)',
    unit_t: 'Tonelada (t)',
    unit_lb: 'Libra (lb)',
    unit_oz: 'Onça (oz)',
    unit_C: 'Celsius (°C)',
    unit_F: 'Fahrenheit (°F)',
    unit_K: 'Kelvin (K)',
    unit_L: 'Litro (L)',
    unit_mL: 'Mililitro (mL)',
    unit_m3: 'Metro cúbico (m³)',
    unit_gal_us: 'Galão (EUA)',
    unit_gal_uk: 'Galão (Reino Unido)',
    unit_fl_oz: 'Onça líquida (EUA)',
    unit_cup: 'Xícara (EUA)',
    unit_mps: 'Metro/segundo (m/s)',
    unit_kph: 'Quilômetro/hora (km/h)',
    unit_mph: 'Milha/hora (mph)',
    unit_kn: 'Nó',
    unit_fps: 'Pé/segundo (ft/s)',
  },
};
