import type { LocalizedStrings } from '@anytools/ui';

const EN = {
  title: 'Password Generator',
  levelWeak: 'weak',
  levelFair: 'fair',
  levelStrong: 'strong',
  levelExcellent: 'excellent',
  // {n} is the entropy in bits.
  bits: '{n} bits',
  // {t} is the crack-time label produced by the logic layer.
  crackTime: 'est. crack time: {t}',
  length: 'Length:',
  lowercase: 'Lowercase a–z',
  uppercase: 'Uppercase A–Z',
  numbers: 'Numbers 0–9',
  symbols: 'Symbols !@#…',
  excludeAmbiguous: 'Exclude ambiguous (0,O,l,1,I)',
  generateNew: 'Generate new',
  // {code} is replaced with the <code>crypto.getRandomValues</code> element.
  note: 'Generated with {code}. For storage, hash with bcrypt / Argon2, never with plain SHA.',
};

export const STRINGS: LocalizedStrings<typeof EN> = {
  en: EN,
  vi: {
    title: 'Tạo mật khẩu',
    levelWeak: 'yếu',
    levelFair: 'trung bình',
    levelStrong: 'mạnh',
    levelExcellent: 'rất mạnh',
    bits: '{n} bit',
    crackTime: 'thời gian bẻ khóa ước tính: {t}',
    length: 'Độ dài:',
    lowercase: 'Chữ thường a–z',
    uppercase: 'Chữ hoa A–Z',
    numbers: 'Chữ số 0–9',
    symbols: 'Ký tự đặc biệt !@#…',
    excludeAmbiguous: 'Loại ký tự dễ nhầm (0,O,l,1,I)',
    generateNew: 'Tạo mới',
    note: 'Tạo bằng {code}. Khi lưu trữ, hãy băm bằng bcrypt / Argon2, không bao giờ dùng SHA thuần.',
  },
  es: {
    title: 'Generador de contraseñas',
    levelWeak: 'débil',
    levelFair: 'aceptable',
    levelStrong: 'fuerte',
    levelExcellent: 'excelente',
    bits: '{n} bits',
    crackTime: 'tiempo estimado para descifrarla: {t}',
    length: 'Longitud:',
    lowercase: 'Minúsculas a–z',
    uppercase: 'Mayúsculas A–Z',
    numbers: 'Números 0–9',
    symbols: 'Símbolos !@#…',
    excludeAmbiguous: 'Excluir ambiguos (0,O,l,1,I)',
    generateNew: 'Generar otra',
    note: 'Generada con {code}. Para almacenarla, hashea con bcrypt / Argon2, nunca con SHA a secas.',
  },
  pt: {
    title: 'Gerador de senhas',
    levelWeak: 'fraca',
    levelFair: 'razoável',
    levelStrong: 'forte',
    levelExcellent: 'excelente',
    bits: '{n} bits',
    crackTime: 'tempo estimado para quebrar: {t}',
    length: 'Comprimento:',
    lowercase: 'Minúsculas a–z',
    uppercase: 'Maiúsculas A–Z',
    numbers: 'Números 0–9',
    symbols: 'Símbolos !@#…',
    excludeAmbiguous: 'Excluir ambíguos (0,O,l,1,I)',
    generateNew: 'Gerar nova',
    note: 'Gerada com {code}. Para armazenar, use hash bcrypt / Argon2, nunca SHA puro.',
  },
};
