import type { LocalizedStrings } from '@anytools/ui';

const EN = {
  title: 'Cubic Bezier Generator',
  hint: 'Drag the two handles, or use the arrow keys after clicking one. The dashed lines run from the fixed start (0,0) and end (1,1) points to each handle.',
  handleP1: 'Control point 1, x {x}, y {y}. Drag or use arrow keys.',
  handleP2: 'Control point 2, x {x}, y {y}. Drag or use arrow keys.',
  cssKeywords: 'CSS keywords',
  overshoot: 'Overshoot presets',
  coordinates: 'Control point values',
  cssOutput: 'CSS',
  variableOutput: 'As a custom property',
  preview: 'Preview',
  previewHint:
    'The block moves left to right using this exact easing, so you can see what the numbers feel like.',
  play: 'Play',
  replay: 'Replay',
  duration: 'Duration',
  // {n} preset name, sentence-cased for display
  preset_linear: 'linear',
  preset_ease: 'ease',
  preset_easein: 'ease-in',
  preset_easeout: 'ease-out',
  preset_easeinout: 'ease-in-out',
  preset_easeinback: 'ease-in-back',
  preset_easeoutback: 'ease-out-back',
  preset_easeinoutback: 'ease-in-out-back',
};

export const STRINGS: LocalizedStrings<typeof EN> = {
  en: EN,
  vi: {
    title: 'Trình tạo Cubic Bezier',
    hint: 'Kéo hai tay cầm, hoặc bấm chọn rồi dùng phím mũi tên. Đường nét đứt nối từ điểm đầu cố định (0,0) và điểm cuối (1,1) tới mỗi tay cầm.',
    handleP1: 'Điểm điều khiển 1, x {x}, y {y}. Kéo hoặc dùng phím mũi tên.',
    handleP2: 'Điểm điều khiển 2, x {x}, y {y}. Kéo hoặc dùng phím mũi tên.',
    cssKeywords: 'Từ khoá CSS',
    overshoot: 'Mẫu quá đà (overshoot)',
    coordinates: 'Giá trị điểm điều khiển',
    cssOutput: 'CSS',
    variableOutput: 'Dạng biến CSS tuỳ chỉnh',
    preview: 'Xem trước',
    previewHint:
      'Khối vuông chạy từ trái sang phải đúng theo easing này, để bạn thấy các con số cảm giác thế nào.',
    play: 'Phát',
    replay: 'Phát lại',
    duration: 'Thời lượng',
    preset_linear: 'linear',
    preset_ease: 'ease',
    preset_easein: 'ease-in',
    preset_easeout: 'ease-out',
    preset_easeinout: 'ease-in-out',
    preset_easeinback: 'ease-in-back',
    preset_easeoutback: 'ease-out-back',
    preset_easeinoutback: 'ease-in-out-back',
  },
  es: {
    title: 'Generador de Cubic Bezier',
    hint: 'Arrastra las dos asas, o haz clic en una y usa las flechas del teclado. Las líneas discontinuas van desde el inicio fijo (0,0) y el final (1,1) hasta cada asa.',
    handleP1: 'Punto de control 1, x {x}, y {y}. Arrastra o usa las flechas.',
    handleP2: 'Punto de control 2, x {x}, y {y}. Arrastra o usa las flechas.',
    cssKeywords: 'Palabras clave CSS',
    overshoot: 'Ejemplos con rebote (overshoot)',
    coordinates: 'Valores de los puntos de control',
    cssOutput: 'CSS',
    variableOutput: 'Como propiedad personalizada',
    preview: 'Vista previa',
    previewHint:
      'El bloque se mueve de izquierda a derecha con este easing exacto, para que veas cómo se siente cada número.',
    play: 'Reproducir',
    replay: 'Repetir',
    duration: 'Duración',
    preset_linear: 'linear',
    preset_ease: 'ease',
    preset_easein: 'ease-in',
    preset_easeout: 'ease-out',
    preset_easeinout: 'ease-in-out',
    preset_easeinback: 'ease-in-back',
    preset_easeoutback: 'ease-out-back',
    preset_easeinoutback: 'ease-in-out-back',
  },
  pt: {
    title: 'Gerador de Cubic Bezier',
    hint: 'Arraste as duas alças, ou clique numa e use as setas do teclado. As linhas tracejadas ligam o início fixo (0,0) e o fim (1,1) a cada alça.',
    handleP1: 'Ponto de controle 1, x {x}, y {y}. Arraste ou use as setas.',
    handleP2: 'Ponto de controle 2, x {x}, y {y}. Arraste ou use as setas.',
    cssKeywords: 'Palavras-chave CSS',
    overshoot: 'Exemplos com exagero (overshoot)',
    coordinates: 'Valores dos pontos de controle',
    cssOutput: 'CSS',
    variableOutput: 'Como propriedade personalizada',
    preview: 'Pré-visualização',
    previewHint:
      'O bloco se move da esquerda para a direita com esse easing exato, para você sentir o que os números fazem.',
    play: 'Reproduzir',
    replay: 'Repetir',
    duration: 'Duração',
    preset_linear: 'linear',
    preset_ease: 'ease',
    preset_easein: 'ease-in',
    preset_easeout: 'ease-out',
    preset_easeinout: 'ease-in-out',
    preset_easeinback: 'ease-in-back',
    preset_easeoutback: 'ease-out-back',
    preset_easeinoutback: 'ease-in-out-back',
  },
};
