import type { LocalizedStrings } from '@anytools/ui';

const EN = {
  title: 'Cron Parser',
  cronExpression: 'Cron expression',
  fieldsHint: '5 fields: minute hour day month weekday',
  presetEveryMinute: 'Every minute',
  presetEvery5Minutes: 'Every 5 minutes',
  presetHourly: 'Hourly',
  presetDailyMidnight: 'Daily midnight',
  presetDaily9am: 'Daily 9am',
  presetWeeklySunMidnight: 'Weekly Sun midnight',
  presetMonthly1st: 'Monthly 1st',
  presetBusinessHours: 'Business hours',
  description: 'Description: ',
  next10Runs: 'Next 10 runs (UTC)',
  error_invalidCron: '{detail}',
};

export const STRINGS: LocalizedStrings<typeof EN> = {
  en: EN,
  vi: {
    title: 'Phân tích cron',
    cronExpression: 'Biểu thức cron',
    fieldsHint: '5 trường: phút giờ ngày tháng thứ',
    presetEveryMinute: 'Mỗi phút',
    presetEvery5Minutes: 'Mỗi 5 phút',
    presetHourly: 'Mỗi giờ',
    presetDailyMidnight: 'Hằng ngày lúc 0h',
    presetDaily9am: 'Hằng ngày lúc 9h',
    presetWeeklySunMidnight: 'Hằng tuần, Chủ nhật 0h',
    presetMonthly1st: 'Mùng 1 hằng tháng',
    presetBusinessHours: 'Giờ hành chính',
    description: 'Mô tả: ',
    next10Runs: '10 lần chạy tiếp theo (UTC)',
    error_invalidCron: 'Biểu thức cron không hợp lệ: {detail}',
  },
  es: {
    title: 'Analizador de cron',
    cronExpression: 'Expresión cron',
    fieldsHint: '5 campos: minuto hora día mes día-de-semana',
    presetEveryMinute: 'Cada minuto',
    presetEvery5Minutes: 'Cada 5 minutos',
    presetHourly: 'Cada hora',
    presetDailyMidnight: 'Diario a medianoche',
    presetDaily9am: 'Diario a las 9',
    presetWeeklySunMidnight: 'Semanal, domingo a medianoche',
    presetMonthly1st: 'Mensual, día 1',
    presetBusinessHours: 'Horario laboral',
    description: 'Descripción: ',
    next10Runs: 'Próximas 10 ejecuciones (UTC)',
    error_invalidCron: 'Expresión cron no válida: {detail}',
  },
  pt: {
    title: 'Analisador de cron',
    cronExpression: 'Expressão cron',
    fieldsHint: '5 campos: minuto hora dia mês dia-da-semana',
    presetEveryMinute: 'A cada minuto',
    presetEvery5Minutes: 'A cada 5 minutos',
    presetHourly: 'A cada hora',
    presetDailyMidnight: 'Diário à meia-noite',
    presetDaily9am: 'Diário às 9h',
    presetWeeklySunMidnight: 'Semanal, domingo à meia-noite',
    presetMonthly1st: 'Mensal, dia 1',
    presetBusinessHours: 'Horário comercial',
    description: 'Descrição: ',
    next10Runs: 'Próximas 10 execuções (UTC)',
    error_invalidCron: 'Expressão cron inválida: {detail}',
  },
};
