import type { LocalizedStrings } from '@anytools/ui';

const EN = {
  title: 'Triangle Calculator',
  description: "Three sides → angles, area, perimeter. Heron's formula.",
  sideA: 'Side a',
  sideB: 'Side b',
  sideC: 'Side c',
  area: 'Area',
  perimeter: 'Perimeter',
  angleA: 'Angle A',
  angleB: 'Angle B',
  angleC: 'Angle C',
  type: 'Type',
  rightTriangle: 'Right triangle',
  oblique: 'Oblique',
  invalid: 'Sides violate triangle inequality.',
};

export const STRINGS: LocalizedStrings<typeof EN> = {
  en: EN,
  vi: {
    title: 'Tính tam giác',
    description: 'Ba cạnh → góc, diện tích, chu vi. Công thức Heron.',
    sideA: 'Cạnh a',
    sideB: 'Cạnh b',
    sideC: 'Cạnh c',
    area: 'Diện tích',
    perimeter: 'Chu vi',
    angleA: 'Góc A',
    angleB: 'Góc B',
    angleC: 'Góc C',
    type: 'Loại',
    rightTriangle: 'Tam giác vuông',
    oblique: 'Tam giác thường',
    invalid: 'Các cạnh vi phạm bất đẳng thức tam giác.',
  },
  es: {
    title: 'Calculadora de triángulos',
    description: 'Tres lados → ángulos, área, perímetro. Fórmula de Herón.',
    sideA: 'Lado a',
    sideB: 'Lado b',
    sideC: 'Lado c',
    area: 'Área',
    perimeter: 'Perímetro',
    angleA: 'Ángulo A',
    angleB: 'Ángulo B',
    angleC: 'Ángulo C',
    type: 'Tipo',
    rightTriangle: 'Triángulo rectángulo',
    oblique: 'Oblicuo',
    invalid: 'Los lados no cumplen la desigualdad triangular.',
  },
  pt: {
    title: 'Calculadora de triângulos',
    description: 'Três lados → ângulos, área, perímetro. Fórmula de Heron.',
    sideA: 'Lado a',
    sideB: 'Lado b',
    sideC: 'Lado c',
    area: 'Área',
    perimeter: 'Perímetro',
    angleA: 'Ângulo A',
    angleB: 'Ângulo B',
    angleC: 'Ângulo C',
    type: 'Tipo',
    rightTriangle: 'Triângulo retângulo',
    oblique: 'Oblíquo',
    invalid: 'Os lados violam a desigualdade triangular.',
  },
};
