import type { LocalizedStrings } from '@anytools/ui';

const EN = {
  title: 'Color Blindness Simulator',
  modeImage: 'Image',
  modeColor: 'Color code',
  uploadLabel: 'Image to simulate',
  deficiency: 'Deficiency',
  type_protanopia: 'Protanopia (no L cones)',
  type_deuteranopia: 'Deuteranopia (no M cones)',
  type_tritanopia: 'Tritanopia (no S cones)',
  type_achromatopsia: 'Achromatopsia (no color vision)',
  compare: 'Compare',
  original: 'Original',
  simulated: 'Simulated',
  colorLabel: 'Color to test',
  colorPlaceholder: '#e67e22',
  error_invalidColor: 'Enter a hex color like #e67e22 or #f80.',
  loading: 'Rendering…',
  approximationNote:
    'This is a mathematical approximation of dichromatic color vision, not a substitute for testing with people who actually have the condition.',
};

export const STRINGS: LocalizedStrings<typeof EN> = {
  en: EN,
  vi: {
    title: 'Mô phỏng mù màu',
    modeImage: 'Ảnh',
    modeColor: 'Mã màu',
    uploadLabel: 'Ảnh cần mô phỏng',
    deficiency: 'Loại mù màu',
    type_protanopia: 'Protanopia (thiếu nón L)',
    type_deuteranopia: 'Deuteranopia (thiếu nón M)',
    type_tritanopia: 'Tritanopia (thiếu nón S)',
    type_achromatopsia: 'Achromatopsia (không thấy màu)',
    compare: 'So sánh',
    original: 'Gốc',
    simulated: 'Mô phỏng',
    colorLabel: 'Màu cần kiểm tra',
    colorPlaceholder: '#e67e22',
    error_invalidColor: 'Nhập mã màu hex như #e67e22 hoặc #f80.',
    loading: 'Đang dựng…',
    approximationNote:
      'Đây là mô phỏng toán học cho thị giác mù màu hai sắc, không thay thế cho việc kiểm thử với người thật có tình trạng này.',
  },
  es: {
    title: 'Simulador de daltonismo',
    modeImage: 'Imagen',
    modeColor: 'Código de color',
    uploadLabel: 'Imagen para simular',
    deficiency: 'Tipo de daltonismo',
    type_protanopia: 'Protanopía (sin conos L)',
    type_deuteranopia: 'Deuteranopía (sin conos M)',
    type_tritanopia: 'Tritanopía (sin conos S)',
    type_achromatopsia: 'Acromatopsia (sin visión de color)',
    compare: 'Comparar',
    original: 'Original',
    simulated: 'Simulado',
    colorLabel: 'Color a probar',
    colorPlaceholder: '#e67e22',
    error_invalidColor: 'Escribe un color hex como #e67e22 o #f80.',
    loading: 'Generando…',
    approximationNote:
      'Esto es una aproximación matemática de la visión dicromática, no un sustituto de probar con personas que realmente tienen la condición.',
  },
  pt: {
    title: 'Simulador de daltonismo',
    modeImage: 'Imagem',
    modeColor: 'Código de cor',
    uploadLabel: 'Imagem para simular',
    deficiency: 'Tipo de daltonismo',
    type_protanopia: 'Protanopia (sem cones L)',
    type_deuteranopia: 'Deuteranopia (sem cones M)',
    type_tritanopia: 'Tritanopia (sem cones S)',
    type_achromatopsia: 'Acromatopsia (sem visão de cor)',
    compare: 'Comparar',
    original: 'Original',
    simulated: 'Simulado',
    colorLabel: 'Cor para testar',
    colorPlaceholder: '#e67e22',
    error_invalidColor: 'Digite uma cor hex como #e67e22 ou #f80.',
    loading: 'Gerando…',
    approximationNote:
      'Isto é uma aproximação matemática da visão dicromática, não um substituto para testes com pessoas que realmente têm a condição.',
  },
};
