import type { LocalizedStrings } from '@anytools/ui';

const EN = {
  title: 'URL Parser',
  url: 'URL',
  protocol: 'Protocol',
  username: 'Username',
  password: 'Password',
  hostname: 'Hostname',
  port: 'Port',
  defaultPort: '{port} (default)',
  origin: 'Origin',
  path: 'Path',
  fragment: 'Fragment',
  pathSegments: 'Path segments',
  queryParams: 'Query parameters ({n})',
  noParams: 'None.',
  key: 'Key',
  value: 'Value',
  empty: '(empty)',
  invalidUrl: 'Invalid URL',
};

export const STRINGS: LocalizedStrings<typeof EN> = {
  en: EN,
  vi: {
    title: 'Phân tích URL',
    url: 'URL',
    protocol: 'Giao thức',
    username: 'Tên người dùng',
    password: 'Mật khẩu',
    hostname: 'Tên máy chủ',
    port: 'Cổng',
    defaultPort: '{port} (mặc định)',
    origin: 'Origin',
    path: 'Đường dẫn',
    fragment: 'Fragment',
    pathSegments: 'Các đoạn đường dẫn',
    queryParams: 'Tham số truy vấn ({n})',
    noParams: 'Không có.',
    key: 'Khóa',
    value: 'Giá trị',
    empty: '(trống)',
    invalidUrl: 'URL không hợp lệ',
  },
  es: {
    title: 'Analizador de URL',
    url: 'URL',
    protocol: 'Protocolo',
    username: 'Usuario',
    password: 'Contraseña',
    hostname: 'Nombre de host',
    port: 'Puerto',
    defaultPort: '{port} (predeterminado)',
    origin: 'Origen',
    path: 'Ruta',
    fragment: 'Fragmento',
    pathSegments: 'Segmentos de la ruta',
    queryParams: 'Parámetros de consulta ({n})',
    noParams: 'Ninguno.',
    key: 'Clave',
    value: 'Valor',
    empty: '(vacío)',
    invalidUrl: 'URL no válida',
  },
  pt: {
    title: 'Analisador de URL',
    url: 'URL',
    protocol: 'Protocolo',
    username: 'Usuário',
    password: 'Senha',
    hostname: 'Nome do host',
    port: 'Porta',
    defaultPort: '{port} (padrão)',
    origin: 'Origem',
    path: 'Caminho',
    fragment: 'Fragmento',
    pathSegments: 'Segmentos do caminho',
    queryParams: 'Parâmetros de consulta ({n})',
    noParams: 'Nenhum.',
    key: 'Chave',
    value: 'Valor',
    empty: '(vazio)',
    invalidUrl: 'URL inválida',
  },
};
