import type { LocalizedStrings } from '@anytools/ui';

const EN = {
  title: 'Lorem Ipsum Generator',
  variant: 'Variant',
  variantClassic: 'Classic Lorem',
  variantVietnamese: 'Vietnamese',
  variantSpanish: 'Spanish',
  variantHipster: 'Hipster',
  unit: 'Unit',
  unitParagraphs: 'paragraphs',
  unitSentences: 'sentences',
  unitWords: 'words',
  count: 'Count (1–500)',
  outputPlain: 'plain text',
  outputHtml: 'HTML',
  regenerate: 'Regenerate',
};

export const STRINGS: LocalizedStrings<typeof EN> = {
  en: EN,
  vi: {
    title: 'Tạo văn bản Lorem Ipsum',
    variant: 'Kiểu',
    variantClassic: 'Lorem cổ điển',
    variantVietnamese: 'Tiếng Việt',
    variantSpanish: 'Tiếng Tây Ban Nha',
    variantHipster: 'Hipster',
    unit: 'Đơn vị',
    unitParagraphs: 'đoạn văn',
    unitSentences: 'câu',
    unitWords: 'từ',
    count: 'Số lượng (1–500)',
    outputPlain: 'văn bản thuần',
    outputHtml: 'HTML',
    regenerate: 'Tạo lại',
  },
  es: {
    title: 'Generador de Lorem Ipsum',
    variant: 'Variante',
    variantClassic: 'Lorem clásico',
    variantVietnamese: 'Vietnamita',
    variantSpanish: 'Español',
    variantHipster: 'Hipster',
    unit: 'Unidad',
    unitParagraphs: 'párrafos',
    unitSentences: 'oraciones',
    unitWords: 'palabras',
    count: 'Cantidad (1–500)',
    outputPlain: 'texto plano',
    outputHtml: 'HTML',
    regenerate: 'Regenerar',
  },
  pt: {
    title: 'Gerador de Lorem Ipsum',
    variant: 'Variante',
    variantClassic: 'Lorem clássico',
    variantVietnamese: 'Vietnamita',
    variantSpanish: 'Espanhol',
    variantHipster: 'Hipster',
    unit: 'Unidade',
    unitParagraphs: 'parágrafos',
    unitSentences: 'frases',
    unitWords: 'palavras',
    count: 'Quantidade (1–500)',
    outputPlain: 'texto simples',
    outputHtml: 'HTML',
    regenerate: 'Gerar novamente',
  },
};
