import type { LocalizedStrings } from '@anytools/ui';

const EN = {
  title: 'Time Card Calculator',
  description: 'Track 7 days of clock-in/out + breaks. Overnight shifts handled automatically.',
  day_Monday: 'Monday',
  day_Tuesday: 'Tuesday',
  day_Wednesday: 'Wednesday',
  day_Thursday: 'Thursday',
  day_Friday: 'Friday',
  day_Saturday: 'Saturday',
  day_Sunday: 'Sunday',
  dayIn: '{day} in',
  dayOut: '{day} out',
  dayBreak: '{day} break (min)',
  hourlyRate: 'Hourly rate',
  totalHours: 'Total hours',
  regular: 'Regular (≤40h)',
  overtime: 'Overtime (>40h)',
  hoursAtRate: '{h} h @ ${rate}/h',
  pay: 'Pay (FLSA 1.5× OT)',
};

export const STRINGS: LocalizedStrings<typeof EN> = {
  en: EN,
  vi: {
    title: 'Tính bảng chấm công',
    description: 'Theo dõi 7 ngày giờ vào/ra + nghỉ giữa ca. Ca qua đêm được tự động xử lý.',
    day_Monday: 'Thứ Hai',
    day_Tuesday: 'Thứ Ba',
    day_Wednesday: 'Thứ Tư',
    day_Thursday: 'Thứ Năm',
    day_Friday: 'Thứ Sáu',
    day_Saturday: 'Thứ Bảy',
    day_Sunday: 'Chủ Nhật',
    dayIn: 'Giờ vào {day}',
    dayOut: 'Giờ ra {day}',
    dayBreak: 'Nghỉ {day} (phút)',
    hourlyRate: 'Lương theo giờ',
    totalHours: 'Tổng số giờ',
    regular: 'Giờ thường (≤40h)',
    overtime: 'Tăng ca (>40h)',
    hoursAtRate: '{h} giờ × ${rate}/giờ',
    pay: 'Lương (FLSA 1.5× tăng ca)',
  },
  es: {
    title: 'Calculadora de horas trabajadas',
    description:
      'Registra 7 días de entrada/salida + descansos. Los turnos nocturnos se calculan solos.',
    day_Monday: 'Lunes',
    day_Tuesday: 'Martes',
    day_Wednesday: 'Miércoles',
    day_Thursday: 'Jueves',
    day_Friday: 'Viernes',
    day_Saturday: 'Sábado',
    day_Sunday: 'Domingo',
    dayIn: 'Entrada {day}',
    dayOut: 'Salida {day}',
    dayBreak: 'Descanso {day} (min)',
    hourlyRate: 'Tarifa por hora',
    totalHours: 'Horas totales',
    regular: 'Regulares (≤40h)',
    overtime: 'Extra (>40h)',
    hoursAtRate: '{h} h a ${rate}/h',
    pay: 'Pago (FLSA 1.5× extra)',
  },
  pt: {
    title: 'Calculadora de cartão de ponto',
    description:
      'Registre 7 dias de entrada/saída + intervalos. Turnos noturnos são calculados automaticamente.',
    day_Monday: 'Segunda',
    day_Tuesday: 'Terça',
    day_Wednesday: 'Quarta',
    day_Thursday: 'Quinta',
    day_Friday: 'Sexta',
    day_Saturday: 'Sábado',
    day_Sunday: 'Domingo',
    dayIn: 'Entrada {day}',
    dayOut: 'Saída {day}',
    dayBreak: 'Intervalo {day} (min)',
    hourlyRate: 'Valor por hora',
    totalHours: 'Total de horas',
    regular: 'Normais (≤40h)',
    overtime: 'Extras (>40h)',
    hoursAtRate: '{h} h a ${rate}/h',
    pay: 'Pagamento (FLSA 1,5× extra)',
  },
};
