import type { LocalizedStrings } from '@anytools/ui';

const EN = {
  title: 'Running Pace Calculator',
  description: 'Pace from distance + time. Race-distance projections.',
  kilometers: 'Kilometers',
  miles: 'Miles',
  distanceUnit: 'Distance unit',
  distance: 'Distance',
  time: 'Time',
  minutes: 'Minutes',
  seconds: 'Seconds',
  minutesHint: 'minutes',
  secondsHint: 'seconds',
  tableTitle: 'Pace + race projections',
  pacePerKm: 'Pace per km',
  pacePerMile: 'Pace per mile',
  race_half: 'Half marathon',
  race_marathon: 'Marathon',
};

export const STRINGS: LocalizedStrings<typeof EN> = {
  en: EN,
  vi: {
    title: 'Máy tính pace chạy bộ',
    description: 'Tính pace từ quãng đường + thời gian. Dự đoán thành tích các cự ly.',
    kilometers: 'Ki-lô-mét',
    miles: 'Dặm',
    distanceUnit: 'Đơn vị quãng đường',
    distance: 'Quãng đường',
    time: 'Thời gian',
    minutes: 'Phút',
    seconds: 'Giây',
    minutesHint: 'phút',
    secondsHint: 'giây',
    tableTitle: 'Pace + dự đoán cự ly',
    pacePerKm: 'Pace mỗi km',
    pacePerMile: 'Pace mỗi dặm',
    race_half: 'Bán marathon',
    race_marathon: 'Marathon',
  },
  es: {
    title: 'Calculadora de ritmo de carrera',
    description: 'Ritmo a partir de distancia + tiempo. Proyecciones por distancia de carrera.',
    kilometers: 'Kilómetros',
    miles: 'Millas',
    distanceUnit: 'Unidad de distancia',
    distance: 'Distancia',
    time: 'Tiempo',
    minutes: 'Minutos',
    seconds: 'Segundos',
    minutesHint: 'minutos',
    secondsHint: 'segundos',
    tableTitle: 'Ritmo + proyecciones de carrera',
    pacePerKm: 'Ritmo por km',
    pacePerMile: 'Ritmo por milla',
    race_half: 'Media maratón',
    race_marathon: 'Maratón',
  },
  pt: {
    title: 'Calculadora de ritmo de corrida',
    description: 'Ritmo a partir de distância + tempo. Projeções por distância de prova.',
    kilometers: 'Quilômetros',
    miles: 'Milhas',
    distanceUnit: 'Unidade de distância',
    distance: 'Distância',
    time: 'Tempo',
    minutes: 'Minutos',
    seconds: 'Segundos',
    minutesHint: 'minutos',
    secondsHint: 'segundos',
    tableTitle: 'Ritmo + projeções de prova',
    pacePerKm: 'Ritmo por km',
    pacePerMile: 'Ritmo por milha',
    race_half: 'Meia maratona',
    race_marathon: 'Maratona',
  },
};
