import type { LocalizedStrings } from '@anytools/ui';

const EN = {
  title: 'Crop Image',
  dropLabel: 'Image to crop',
  failed: 'Crop failed',
  aspect_free: 'Free',
  aspect_square: '1:1 square',
  aspect_portrait: '4:5 portrait',
  aspect_landscape: '3:2 landscape',
  aspect_wide: '16:9 widescreen',
  dragHint: 'Drag on the image to select an area.',
  dragHintSmall:
    'Drag on the image to select an area — the current selection is too small to crop.',
  selection: 'Selection: {w} × {h} px',
  ofSize: 'of {w} × {h}',
  imageAlt: 'Drag on this image to choose the crop area',
  outputFormat: 'Output format',
  resetSelection: 'Reset selection',
  cropping: 'Cropping…',
  crop: 'Crop',
  scaledNote: 'cut from a smaller decode: the {w} × {h} original is above what a canvas can hold',
  resultAlt: 'Cropped result',
  download: 'Download {name}',
};

export const STRINGS: LocalizedStrings<typeof EN> = {
  en: EN,
  vi: {
    title: 'Cắt ảnh',
    dropLabel: 'Ảnh cần cắt',
    failed: 'Cắt thất bại',
    aspect_free: 'Tự do',
    aspect_square: '1:1 vuông',
    aspect_portrait: '4:5 dọc',
    aspect_landscape: '3:2 ngang',
    aspect_wide: '16:9 màn rộng',
    dragHint: 'Kéo trên ảnh để chọn vùng cắt.',
    dragHintSmall: 'Kéo trên ảnh để chọn vùng cắt — vùng hiện tại quá nhỏ để cắt.',
    selection: 'Vùng chọn: {w} × {h} px',
    ofSize: 'trên {w} × {h}',
    imageAlt: 'Kéo trên ảnh này để chọn vùng cắt',
    outputFormat: 'Định dạng đầu ra',
    resetSelection: 'Đặt lại vùng chọn',
    cropping: 'Đang cắt…',
    crop: 'Cắt',
    scaledNote:
      'cắt từ bản giải mã nhỏ hơn: ảnh gốc {w} × {h} vượt quá kích thước canvas có thể chứa',
    resultAlt: 'Kết quả cắt',
    download: 'Tải {name}',
  },
  es: {
    title: 'Recortar imagen',
    dropLabel: 'Imagen a recortar',
    failed: 'El recorte falló',
    aspect_free: 'Libre',
    aspect_square: '1:1 cuadrado',
    aspect_portrait: '4:5 vertical',
    aspect_landscape: '3:2 horizontal',
    aspect_wide: '16:9 panorámico',
    dragHint: 'Arrastra sobre la imagen para seleccionar un área.',
    dragHintSmall:
      'Arrastra sobre la imagen para seleccionar un área — la selección actual es demasiado pequeña para recortar.',
    selection: 'Selección: {w} × {h} px',
    ofSize: 'de {w} × {h}',
    imageAlt: 'Arrastra sobre esta imagen para elegir el área de recorte',
    outputFormat: 'Formato de salida',
    resetSelection: 'Restablecer selección',
    cropping: 'Recortando…',
    crop: 'Recortar',
    scaledNote:
      'recortada de una decodificación más pequeña: el original de {w} × {h} supera lo que un canvas puede contener',
    resultAlt: 'Resultado recortado',
    download: 'Descargar {name}',
  },
  pt: {
    title: 'Cortar imagem',
    dropLabel: 'Imagem a cortar',
    failed: 'O corte falhou',
    aspect_free: 'Livre',
    aspect_square: '1:1 quadrado',
    aspect_portrait: '4:5 retrato',
    aspect_landscape: '3:2 paisagem',
    aspect_wide: '16:9 widescreen',
    dragHint: 'Arraste sobre a imagem para selecionar uma área.',
    dragHintSmall:
      'Arraste sobre a imagem para selecionar uma área — a seleção atual é pequena demais para cortar.',
    selection: 'Seleção: {w} × {h} px',
    ofSize: 'de {w} × {h}',
    imageAlt: 'Arraste sobre esta imagem para escolher a área de corte',
    outputFormat: 'Formato de saída',
    resetSelection: 'Redefinir seleção',
    cropping: 'Cortando…',
    crop: 'Cortar',
    scaledNote:
      'cortada de uma decodificação menor: o original de {w} × {h} passa do que um canvas consegue conter',
    resultAlt: 'Resultado cortado',
    download: 'Baixar {name}',
  },
};
