import type { LocalizedStrings } from '@anytools/ui';

const EN = {
  title: 'X.509 Certificate Decoder',
  pasteLabel: 'Paste PEM certificate',
  pastePlaceholder: '-----BEGIN CERTIFICATE-----',
  uploadLabel: 'Or upload a .cer / .crt / .der file',
  decodeButton: 'Decode',
  decoding: 'Decoding…',
  decodeFailed: 'Could not decode.',
  certificateN: 'Certificate {n} of {total}',
  subject: 'Subject',
  issuer: 'Issuer',
  serialNumber: 'Serial number',
  validFrom: 'Valid from',
  validTo: 'Valid to',
  daysRemaining: '{n} days remaining',
  daysExpiredAgo: 'Expired {n} days ago',
  signatureAlgorithm: 'Signature algorithm',
  publicKey: 'Public key',
  // {curve} filled only for EC keys.
  publicKeyEc: '{algorithm} ({curve})',
  // {size} filled only for RSA keys.
  publicKeyRsa: '{algorithm}, {size}-bit',
  subjectAltName: 'Subject Alternative Name',
  keyUsage: 'Key usage',
  extendedKeyUsage: 'Extended key usage',
  basicConstraints: 'Basic constraints',
  isCa: 'CA: {value}',
  yes: 'yes',
  no: 'no',
  pathLength: ', path length {n}',
  fingerprintSha1: 'SHA-1 fingerprint',
  fingerprintSha256: 'SHA-256 fingerprint',
  badgeSelfSigned: 'Self-signed',
  badgeExpired: 'Expired',
  badgeNotYetValid: 'Not yet valid',
  badgeExpiringSoon: 'Expires soon',
  // KeyUsage / ExtendedKeyUsage ids (RFC 5280) — the widget's translation of logic.ts's stable ids.
  ku_digitalSignature: 'Digital Signature',
  ku_nonRepudiation: 'Non Repudiation',
  ku_keyEncipherment: 'Key Encipherment',
  ku_dataEncipherment: 'Data Encipherment',
  ku_keyAgreement: 'Key Agreement',
  ku_keyCertSign: 'Certificate Signing',
  ku_cRLSign: 'CRL Signing',
  ku_encipherOnly: 'Encipher Only',
  ku_decipherOnly: 'Decipher Only',
  eku_serverAuth: 'TLS Server Authentication',
  eku_clientAuth: 'TLS Client Authentication',
  eku_codeSigning: 'Code Signing',
  eku_emailProtection: 'Email Protection',
  eku_timeStamping: 'Time Stamping',
  eku_ocspSigning: 'OCSP Signing',
  privacy: 'Parsed entirely in your browser with WebCrypto — the certificate is never uploaded.',
  error_invalidCertificate: 'Could not read this as an X.509 certificate: {detail}',
  error_noCertificateFound:
    'No "-----BEGIN CERTIFICATE-----" block found. Paste a PEM certificate, or use the file upload for a DER-encoded .cer/.crt/.der.',
};

export const STRINGS: LocalizedStrings<typeof EN> = {
  en: EN,
  vi: {
    title: 'Giải mã chứng chỉ X.509',
    pasteLabel: 'Dán chứng chỉ PEM',
    pastePlaceholder: '-----BEGIN CERTIFICATE-----',
    uploadLabel: 'Hoặc tải file .cer / .crt / .der',
    decodeButton: 'Giải mã',
    decoding: 'Đang giải mã…',
    decodeFailed: 'Không giải mã được.',
    certificateN: 'Chứng chỉ {n} / {total}',
    subject: 'Subject',
    issuer: 'Issuer',
    serialNumber: 'Số serial',
    validFrom: 'Hiệu lực từ',
    validTo: 'Hiệu lực đến',
    daysRemaining: 'Còn {n} ngày',
    daysExpiredAgo: 'Đã hết hạn {n} ngày trước',
    signatureAlgorithm: 'Thuật toán chữ ký',
    publicKey: 'Khoá công khai',
    publicKeyEc: '{algorithm} ({curve})',
    publicKeyRsa: '{algorithm}, {size}-bit',
    subjectAltName: 'Subject Alternative Name',
    keyUsage: 'Key usage',
    extendedKeyUsage: 'Extended key usage',
    basicConstraints: 'Basic constraints',
    isCa: 'CA: {value}',
    yes: 'có',
    no: 'không',
    pathLength: ', path length {n}',
    fingerprintSha1: 'Vân tay SHA-1',
    fingerprintSha256: 'Vân tay SHA-256',
    badgeSelfSigned: 'Tự ký',
    badgeExpired: 'Đã hết hạn',
    badgeNotYetValid: 'Chưa tới hiệu lực',
    badgeExpiringSoon: 'Sắp hết hạn',
    ku_digitalSignature: 'Digital Signature',
    ku_nonRepudiation: 'Non Repudiation',
    ku_keyEncipherment: 'Key Encipherment',
    ku_dataEncipherment: 'Data Encipherment',
    ku_keyAgreement: 'Key Agreement',
    ku_keyCertSign: 'Certificate Signing',
    ku_cRLSign: 'CRL Signing',
    ku_encipherOnly: 'Encipher Only',
    ku_decipherOnly: 'Decipher Only',
    eku_serverAuth: 'TLS Server Authentication',
    eku_clientAuth: 'TLS Client Authentication',
    eku_codeSigning: 'Code Signing',
    eku_emailProtection: 'Email Protection',
    eku_timeStamping: 'Time Stamping',
    eku_ocspSigning: 'OCSP Signing',
    privacy: 'Giải mã hoàn toàn trong trình duyệt bằng WebCrypto — chứng chỉ không tải lên đâu cả.',
    error_invalidCertificate: 'Không đọc được đây là chứng chỉ X.509: {detail}',
    error_noCertificateFound:
      'Không thấy khối "-----BEGIN CERTIFICATE-----" nào. Dán chứng chỉ PEM, hoặc tải file DER (.cer/.crt/.der).',
  },
  es: {
    title: 'Decodificador de certificados X.509',
    pasteLabel: 'Pega el certificado PEM',
    pastePlaceholder: '-----BEGIN CERTIFICATE-----',
    uploadLabel: 'O sube un archivo .cer / .crt / .der',
    decodeButton: 'Decodificar',
    decoding: 'Decodificando…',
    decodeFailed: 'No se pudo decodificar.',
    certificateN: 'Certificado {n} de {total}',
    subject: 'Subject',
    issuer: 'Issuer',
    serialNumber: 'Número de serie',
    validFrom: 'Válido desde',
    validTo: 'Válido hasta',
    daysRemaining: 'Quedan {n} días',
    daysExpiredAgo: 'Expiró hace {n} días',
    signatureAlgorithm: 'Algoritmo de firma',
    publicKey: 'Clave pública',
    publicKeyEc: '{algorithm} ({curve})',
    publicKeyRsa: '{algorithm}, {size} bits',
    subjectAltName: 'Subject Alternative Name',
    keyUsage: 'Key usage',
    extendedKeyUsage: 'Extended key usage',
    basicConstraints: 'Basic constraints',
    isCa: 'CA: {value}',
    yes: 'sí',
    no: 'no',
    pathLength: ', path length {n}',
    fingerprintSha1: 'Huella SHA-1',
    fingerprintSha256: 'Huella SHA-256',
    badgeSelfSigned: 'Autofirmado',
    badgeExpired: 'Expirado',
    badgeNotYetValid: 'Aún no válido',
    badgeExpiringSoon: 'Expira pronto',
    ku_digitalSignature: 'Digital Signature',
    ku_nonRepudiation: 'Non Repudiation',
    ku_keyEncipherment: 'Key Encipherment',
    ku_dataEncipherment: 'Data Encipherment',
    ku_keyAgreement: 'Key Agreement',
    ku_keyCertSign: 'Certificate Signing',
    ku_cRLSign: 'CRL Signing',
    ku_encipherOnly: 'Encipher Only',
    ku_decipherOnly: 'Decipher Only',
    eku_serverAuth: 'TLS Server Authentication',
    eku_clientAuth: 'TLS Client Authentication',
    eku_codeSigning: 'Code Signing',
    eku_emailProtection: 'Email Protection',
    eku_timeStamping: 'Time Stamping',
    eku_ocspSigning: 'OCSP Signing',
    privacy:
      'Decodificado enteramente en tu navegador con WebCrypto — el certificado nunca se sube.',
    error_invalidCertificate: 'No se pudo leer esto como un certificado X.509: {detail}',
    error_noCertificateFound:
      'No se encontró ningún bloque "-----BEGIN CERTIFICATE-----". Pega un certificado PEM, o sube un archivo DER (.cer/.crt/.der).',
  },
  pt: {
    title: 'Decodificador de certificados X.509',
    pasteLabel: 'Cole o certificado PEM',
    pastePlaceholder: '-----BEGIN CERTIFICATE-----',
    uploadLabel: 'Ou envie um arquivo .cer / .crt / .der',
    decodeButton: 'Decodificar',
    decoding: 'Decodificando…',
    decodeFailed: 'Não foi possível decodificar.',
    certificateN: 'Certificado {n} de {total}',
    subject: 'Subject',
    issuer: 'Issuer',
    serialNumber: 'Número de série',
    validFrom: 'Válido de',
    validTo: 'Válido até',
    daysRemaining: 'Faltam {n} dias',
    daysExpiredAgo: 'Expirou há {n} dias',
    signatureAlgorithm: 'Algoritmo de assinatura',
    publicKey: 'Chave pública',
    publicKeyEc: '{algorithm} ({curve})',
    publicKeyRsa: '{algorithm}, {size} bits',
    subjectAltName: 'Subject Alternative Name',
    keyUsage: 'Key usage',
    extendedKeyUsage: 'Extended key usage',
    basicConstraints: 'Basic constraints',
    isCa: 'CA: {value}',
    yes: 'sim',
    no: 'não',
    pathLength: ', path length {n}',
    fingerprintSha1: 'Fingerprint SHA-1',
    fingerprintSha256: 'Fingerprint SHA-256',
    badgeSelfSigned: 'Autoassinado',
    badgeExpired: 'Expirado',
    badgeNotYetValid: 'Ainda não válido',
    badgeExpiringSoon: 'Expira em breve',
    ku_digitalSignature: 'Digital Signature',
    ku_nonRepudiation: 'Non Repudiation',
    ku_keyEncipherment: 'Key Encipherment',
    ku_dataEncipherment: 'Data Encipherment',
    ku_keyAgreement: 'Key Agreement',
    ku_keyCertSign: 'Certificate Signing',
    ku_cRLSign: 'CRL Signing',
    ku_encipherOnly: 'Encipher Only',
    ku_decipherOnly: 'Decipher Only',
    eku_serverAuth: 'TLS Server Authentication',
    eku_clientAuth: 'TLS Client Authentication',
    eku_codeSigning: 'Code Signing',
    eku_emailProtection: 'Email Protection',
    eku_timeStamping: 'Time Stamping',
    eku_ocspSigning: 'OCSP Signing',
    privacy:
      'Decodificado totalmente no seu navegador com WebCrypto — o certificado nunca é enviado.',
    error_invalidCertificate: 'Não foi possível ler isso como um certificado X.509: {detail}',
    error_noCertificateFound:
      'Nenhum bloco "-----BEGIN CERTIFICATE-----" encontrado. Cole um certificado PEM, ou envie um arquivo DER (.cer/.crt/.der).',
  },
};
