import type { LocalizedStrings } from '@anytools/ui';

const EN = {
  title: 'TOTP Generator',
  base32Secret: 'Base32 secret',
  secretAria: 'TOTP secret',
  random: 'Random',
  digits: 'Digits',
  digits6: '6 digits',
  digits8: '8 digits',
  period: 'Period',
  // {n} is the number of seconds left in the current period.
  refreshesIn: 'refreshes in {n}s',
  invalidSecret: 'Invalid base32 secret (allowed: A–Z, 2–7).',
  qrAlt: 'otpauth QR code',
  issuer: 'Issuer',
  accountLabel: 'Account label',
  scanWith: 'Scan with Google Authenticator, Aegis, 1Password…',
};

export const STRINGS: LocalizedStrings<typeof EN> = {
  en: EN,
  vi: {
    title: 'Tạo mã TOTP',
    base32Secret: 'Khóa bí mật Base32',
    secretAria: 'Khóa bí mật TOTP',
    random: 'Ngẫu nhiên',
    digits: 'Số chữ số',
    digits6: '6 chữ số',
    digits8: '8 chữ số',
    period: 'Chu kỳ',
    refreshesIn: 'làm mới sau {n}s',
    invalidSecret: 'Khóa base32 không hợp lệ (chỉ cho phép: A–Z, 2–7).',
    qrAlt: 'Mã QR otpauth',
    issuer: 'Nhà phát hành',
    accountLabel: 'Nhãn tài khoản',
    scanWith: 'Quét bằng Google Authenticator, Aegis, 1Password…',
  },
  es: {
    title: 'Generador TOTP',
    base32Secret: 'Secreto Base32',
    secretAria: 'Secreto TOTP',
    random: 'Aleatorio',
    digits: 'Dígitos',
    digits6: '6 dígitos',
    digits8: '8 dígitos',
    period: 'Periodo',
    refreshesIn: 'se renueva en {n}s',
    invalidSecret: 'Secreto base32 no válido (permitido: A–Z, 2–7).',
    qrAlt: 'Código QR otpauth',
    issuer: 'Emisor',
    accountLabel: 'Etiqueta de la cuenta',
    scanWith: 'Escanéalo con Google Authenticator, Aegis, 1Password…',
  },
  pt: {
    title: 'Gerador TOTP',
    base32Secret: 'Segredo Base32',
    secretAria: 'Segredo TOTP',
    random: 'Aleatório',
    digits: 'Dígitos',
    digits6: '6 dígitos',
    digits8: '8 dígitos',
    period: 'Período',
    refreshesIn: 'renova em {n}s',
    invalidSecret: 'Segredo base32 inválido (permitido: A–Z, 2–7).',
    qrAlt: 'QR code otpauth',
    issuer: 'Emissor',
    accountLabel: 'Rótulo da conta',
    scanWith: 'Escaneie com Google Authenticator, Aegis, 1Password…',
  },
};
