import type { LocalizedStrings } from '@anytools/ui';

const EN = {
  title: 'SQL Playground',
  sqlLabel: 'SQL',
  sqlPlaceholder:
    "CREATE TABLE users (id INTEGER, name TEXT);\nINSERT INTO users VALUES (1, 'Alice');\nSELECT * FROM users;",
  runQuery: 'Run query',
  tablesLabel: 'Tables',
  noTables: 'No tables yet — run a CREATE TABLE, upload a database, or import a CSV below.',
  csvImportTitle: 'Import CSV as a table',
  tableName: 'Table name',
  tableNamePlaceholder: 'my_table',
  csvText: 'CSV text',
  csvPlaceholder: 'name,age\nAlice,30\nBob,25',
  importCsv: 'Import as table',
  uploadDb: 'Upload .sqlite / .db',
  downloadDb: 'Download .sqlite',
  exportCsv: 'Export result as CSV',
  exportJson: 'Export result as JSON',
  resultLabel: 'Result',
  noResult: 'Run a query that SELECTs something to see a result here.',
  rowCount: '{n} row(s)',
  imported: 'Imported {n} row(s) into "{table}" ({columns}).',
  // {size} the byte cap, already localized/formatted by the caller.
  footnote:
    'A real SQLite database, kept only in this tab — nothing is uploaded. The whole file lives in memory, so uploads are capped at {size}.',
  error_dbTooLarge: '{detail}',
  error_tableNameEmpty: '{detail}',
  error_csvEmpty: '{detail}',
};

export const STRINGS: LocalizedStrings<typeof EN> = {
  en: EN,
  vi: {
    title: 'Playground SQL',
    sqlLabel: 'SQL',
    sqlPlaceholder:
      "CREATE TABLE users (id INTEGER, name TEXT);\nINSERT INTO users VALUES (1, 'Alice');\nSELECT * FROM users;",
    runQuery: 'Chạy query',
    tablesLabel: 'Bảng',
    noTables: 'Chưa có bảng nào — chạy CREATE TABLE, upload database, hoặc import CSV bên dưới.',
    csvImportTitle: 'Import CSV thành bảng',
    tableName: 'Tên bảng',
    tableNamePlaceholder: 'my_table',
    csvText: 'Nội dung CSV',
    csvPlaceholder: 'name,age\nAlice,30\nBob,25',
    importCsv: 'Import thành bảng',
    uploadDb: 'Upload .sqlite / .db',
    downloadDb: 'Tải .sqlite',
    exportCsv: 'Export kết quả sang CSV',
    exportJson: 'Export kết quả sang JSON',
    resultLabel: 'Kết quả',
    noResult: 'Chạy một query có SELECT để thấy kết quả ở đây.',
    rowCount: '{n} dòng',
    imported: 'Đã import {n} dòng vào "{table}" ({columns}).',
    footnote:
      'Một database SQLite thật, chỉ nằm trong tab này — không upload đi đâu. Cả file nằm trong RAM nên upload giới hạn {size}.',
    error_dbTooLarge: '{detail}',
    error_tableNameEmpty: '{detail}',
    error_csvEmpty: '{detail}',
  },
  es: {
    title: 'Playground de SQL',
    sqlLabel: 'SQL',
    sqlPlaceholder:
      "CREATE TABLE users (id INTEGER, name TEXT);\nINSERT INTO users VALUES (1, 'Alice');\nSELECT * FROM users;",
    runQuery: 'Ejecutar consulta',
    tablesLabel: 'Tablas',
    noTables:
      'Todavía no hay tablas — ejecuta un CREATE TABLE, sube una base de datos o importa un CSV abajo.',
    csvImportTitle: 'Importar CSV como tabla',
    tableName: 'Nombre de la tabla',
    tableNamePlaceholder: 'mi_tabla',
    csvText: 'Texto CSV',
    csvPlaceholder: 'name,age\nAlice,30\nBob,25',
    importCsv: 'Importar como tabla',
    uploadDb: 'Subir .sqlite / .db',
    downloadDb: 'Descargar .sqlite',
    exportCsv: 'Exportar resultado como CSV',
    exportJson: 'Exportar resultado como JSON',
    resultLabel: 'Resultado',
    noResult: 'Ejecuta una consulta con SELECT para ver un resultado aquí.',
    rowCount: '{n} fila(s)',
    imported: 'Se importaron {n} fila(s) en "{table}" ({columns}).',
    footnote:
      'Una base de datos SQLite real, que vive solo en esta pestaña — nada se sube. El archivo completo vive en memoria, así que las subidas están limitadas a {size}.',
    error_dbTooLarge: '{detail}',
    error_tableNameEmpty: '{detail}',
    error_csvEmpty: '{detail}',
  },
  pt: {
    title: 'Playground de SQL',
    sqlLabel: 'SQL',
    sqlPlaceholder:
      "CREATE TABLE users (id INTEGER, name TEXT);\nINSERT INTO users VALUES (1, 'Alice');\nSELECT * FROM users;",
    runQuery: 'Executar consulta',
    tablesLabel: 'Tabelas',
    noTables: 'Ainda sem tabelas — rode um CREATE TABLE, envie um banco ou importe um CSV abaixo.',
    csvImportTitle: 'Importar CSV como tabela',
    tableName: 'Nome da tabela',
    tableNamePlaceholder: 'minha_tabela',
    csvText: 'Texto CSV',
    csvPlaceholder: 'name,age\nAlice,30\nBob,25',
    importCsv: 'Importar como tabela',
    uploadDb: 'Enviar .sqlite / .db',
    downloadDb: 'Baixar .sqlite',
    exportCsv: 'Exportar resultado como CSV',
    exportJson: 'Exportar resultado como JSON',
    resultLabel: 'Resultado',
    noResult: 'Rode uma consulta com SELECT para ver um resultado aqui.',
    rowCount: '{n} linha(s)',
    imported: 'Importadas {n} linha(s) em "{table}" ({columns}).',
    footnote:
      'Um banco SQLite real, que vive só nesta aba — nada é enviado. O arquivo inteiro fica na memória, então uploads são limitados a {size}.',
    error_dbTooLarge: '{detail}',
    error_tableNameEmpty: '{detail}',
    error_csvEmpty: '{detail}',
  },
};
