import type { LocalizedStrings } from '@anytools/ui';

const EN = {
  title: 'MessagePack ↔ JSON',
  modeDecode: 'Decode → JSON',
  modeEncode: 'Encode → MessagePack',
  encodingLabel: 'Encoding',
  hex: 'Hex',
  base64: 'Base64',
  payloadLabel: 'MessagePack payload',
  payloadPlaceholder: 'Paste hex or Base64…',
  uploadFile: 'Or upload a .msgpack file',
  jsonLabel: 'JSON',
  jsonPlaceholder: '{ "id": 42, "name": "Ada" }',
  waitingDecode: 'Paste, upload, or drop a payload to decode…',
  waitingEncode: 'Paste JSON to encode…',
  sizeComparison: '{input} in → {output} out ({percent}% {direction})',
  smaller: 'smaller',
  larger: 'larger',
  downloadMsgpack: 'Download .msgpack',
  error_emptyPayload: 'Paste or upload a payload first.',
  error_decodeFailed: 'This payload does not decode as MessagePack: {detail}',
  error_invalidJson: 'Data is not valid JSON: {detail}',
  error_notHexDigit: '"{char}" is not a hex digit — expected 0-9 and a-f',
  error_hexOddLength: 'Hex string has an odd number of digits.',
  error_invalidBase64Input: 'This is not valid Base64.',
  error_payloadTooLarge:
    'This payload is {size}, above the {max} this tool decodes in the browser.',
};

/** For helpers (sizeLine) that need the resolved-strings shape without calling the hook. */
export type MsgpackDecoderStrings = typeof EN;

export const STRINGS: LocalizedStrings<typeof EN> = {
  en: EN,
  vi: {
    title: 'MessagePack ↔ JSON',
    modeDecode: 'Giải mã → JSON',
    modeEncode: 'Mã hóa → MessagePack',
    encodingLabel: 'Định dạng',
    hex: 'Hex',
    base64: 'Base64',
    payloadLabel: 'Payload MessagePack',
    payloadPlaceholder: 'Dán hex hoặc Base64…',
    uploadFile: 'Hoặc tải lên file .msgpack',
    jsonLabel: 'JSON',
    jsonPlaceholder: '{ "id": 42, "name": "Ada" }',
    waitingDecode: 'Dán, tải lên hoặc kéo-thả payload để giải mã…',
    waitingEncode: 'Dán JSON để mã hóa…',
    sizeComparison: '{input} vào → {output} ra (nhỏ hơn/lớn hơn {percent}% — {direction})',
    smaller: 'nhỏ hơn',
    larger: 'lớn hơn',
    downloadMsgpack: 'Tải .msgpack',
    error_emptyPayload: 'Hãy dán hoặc tải lên payload trước.',
    error_decodeFailed: 'Payload này không giải mã được thành MessagePack: {detail}',
    error_invalidJson: 'Dữ liệu không phải JSON hợp lệ: {detail}',
    error_notHexDigit: '"{char}" không phải chữ số hex — cần 0-9 và a-f',
    error_hexOddLength: 'Chuỗi hex có số chữ số lẻ.',
    error_invalidBase64Input: 'Đây không phải Base64 hợp lệ.',
    error_payloadTooLarge:
      'Payload này nặng {size}, vượt mức {max} mà công cụ này giải mã được trong trình duyệt.',
  },
  es: {
    title: 'MessagePack ↔ JSON',
    modeDecode: 'Decodificar → JSON',
    modeEncode: 'Codificar → MessagePack',
    encodingLabel: 'Codificación',
    hex: 'Hex',
    base64: 'Base64',
    payloadLabel: 'Payload MessagePack',
    payloadPlaceholder: 'Pega hex o Base64…',
    uploadFile: 'O sube un archivo .msgpack',
    jsonLabel: 'JSON',
    jsonPlaceholder: '{ "id": 42, "name": "Ada" }',
    waitingDecode: 'Pega, sube o suelta un payload para decodificar…',
    waitingEncode: 'Pega JSON para codificar…',
    sizeComparison: '{input} entrada → {output} salida ({percent}% {direction})',
    smaller: 'más pequeño',
    larger: 'más grande',
    downloadMsgpack: 'Descargar .msgpack',
    error_emptyPayload: 'Pega o sube un payload primero.',
    error_decodeFailed: 'Este payload no decodifica como MessagePack: {detail}',
    error_invalidJson: 'Los datos no son JSON válido: {detail}',
    error_notHexDigit: '"{char}" no es un dígito hexadecimal — se esperaba 0-9 y a-f',
    error_hexOddLength: 'La cadena hex tiene un número impar de dígitos.',
    error_invalidBase64Input: 'Esto no es Base64 válido.',
    error_payloadTooLarge:
      'Este payload pesa {size}, por encima de los {max} que esta herramienta decodifica en el navegador.',
  },
  pt: {
    title: 'MessagePack ↔ JSON',
    modeDecode: 'Decodificar → JSON',
    modeEncode: 'Codificar → MessagePack',
    encodingLabel: 'Codificação',
    hex: 'Hex',
    base64: 'Base64',
    payloadLabel: 'Payload MessagePack',
    payloadPlaceholder: 'Cole hex ou Base64…',
    uploadFile: 'Ou envie um arquivo .msgpack',
    jsonLabel: 'JSON',
    jsonPlaceholder: '{ "id": 42, "name": "Ada" }',
    waitingDecode: 'Cole, envie ou solte um payload para decodificar…',
    waitingEncode: 'Cole JSON para codificar…',
    sizeComparison: '{input} entrada → {output} saída ({percent}% {direction})',
    smaller: 'menor',
    larger: 'maior',
    downloadMsgpack: 'Baixar .msgpack',
    error_emptyPayload: 'Cole ou envie um payload primeiro.',
    error_decodeFailed: 'Este payload não decodifica como MessagePack: {detail}',
    error_invalidJson: 'Os dados não são JSON válido: {detail}',
    error_notHexDigit: '"{char}" não é um dígito hexadecimal — esperado 0-9 e a-f',
    error_hexOddLength: 'A string hex tem um número ímpar de dígitos.',
    error_invalidBase64Input: 'Isso não é Base64 válido.',
    error_payloadTooLarge:
      'Este payload tem {size}, acima dos {max} que esta ferramenta decodifica no navegador.',
  },
};
