import type { LocalizedStrings } from '@anytools/ui';

const EN = {
  title: 'HMAC Generator & Verifier',
  tabGenerate: 'Generate',
  tabVerify: 'Verify',
  messageLabel: 'Message',
  messagePlaceholder: 'Type or paste the message to authenticate…',
  keyLabel: 'Secret key',
  keyPlaceholder: 'Shared secret',
  keyEncodingLabel: 'Key format',
  keyEncodingText: 'Text',
  keyEncodingHex: 'Hex',
  algorithmLabel: 'Algorithm',
  outputEncodingLabel: 'Output format',
  resultLabel: 'HMAC',
  computing: 'Computing…',
  expectedLabel: 'Expected HMAC',
  expectedPlaceholder: 'Paste the HMAC to check against…',
  verifyButton: 'Verify',
  verifying: 'Verifying…',
  match: 'Match ✓',
  noMatch: 'No match ✗',
  generateFailed: 'Could not compute the HMAC.',
  verifyFailed: 'Could not run the verification.',
  error_noSecureContext: 'Web Crypto is unavailable here. Open this page over HTTPS or localhost.',
  error_invalidKeyHex: 'The key is not valid hex — use only 0-9/a-f, an even number of digits.',
  error_invalidExpectedHash: 'The expected HMAC does not match the selected output format.',
};

export const STRINGS: LocalizedStrings<typeof EN> = {
  en: EN,
  vi: {
    title: 'Tạo & xác minh HMAC',
    tabGenerate: 'Tạo',
    tabVerify: 'Xác minh',
    messageLabel: 'Thông điệp',
    messagePlaceholder: 'Nhập hoặc dán thông điệp cần xác thực…',
    keyLabel: 'Khoá bí mật',
    keyPlaceholder: 'Khoá dùng chung',
    keyEncodingLabel: 'Định dạng khoá',
    keyEncodingText: 'Text',
    keyEncodingHex: 'Hex',
    algorithmLabel: 'Thuật toán',
    outputEncodingLabel: 'Định dạng kết quả',
    resultLabel: 'HMAC',
    computing: 'Đang tính…',
    expectedLabel: 'HMAC mong đợi',
    expectedPlaceholder: 'Dán HMAC cần đối chiếu…',
    verifyButton: 'Xác minh',
    verifying: 'Đang xác minh…',
    match: 'Khớp ✓',
    noMatch: 'Không khớp ✗',
    generateFailed: 'Không thể tính HMAC.',
    verifyFailed: 'Không thể chạy xác minh.',
    error_noSecureContext:
      'Web Crypto không khả dụng ở đây. Mở trang này qua HTTPS hoặc localhost.',
    error_invalidKeyHex: 'Khoá không phải hex hợp lệ — chỉ dùng 0-9/a-f, số ký tự chẵn.',
    error_invalidExpectedHash: 'HMAC mong đợi không khớp định dạng kết quả đã chọn.',
  },
  es: {
    title: 'Generador y verificador de HMAC',
    tabGenerate: 'Generar',
    tabVerify: 'Verificar',
    messageLabel: 'Mensaje',
    messagePlaceholder: 'Escribe o pega el mensaje a autenticar…',
    keyLabel: 'Clave secreta',
    keyPlaceholder: 'Secreto compartido',
    keyEncodingLabel: 'Formato de la clave',
    keyEncodingText: 'Texto',
    keyEncodingHex: 'Hex',
    algorithmLabel: 'Algoritmo',
    outputEncodingLabel: 'Formato de salida',
    resultLabel: 'HMAC',
    computing: 'Calculando…',
    expectedLabel: 'HMAC esperado',
    expectedPlaceholder: 'Pega el HMAC contra el que comparar…',
    verifyButton: 'Verificar',
    verifying: 'Verificando…',
    match: 'Coincide ✓',
    noMatch: 'No coincide ✗',
    generateFailed: 'No se pudo calcular el HMAC.',
    verifyFailed: 'No se pudo ejecutar la verificación.',
    error_noSecureContext:
      'Web Crypto no está disponible aquí. Abre esta página por HTTPS o localhost.',
    error_invalidKeyHex: 'La clave no es hex válido — usa solo 0-9/a-f, un número par de dígitos.',
    error_invalidExpectedHash: 'El HMAC esperado no coincide con el formato de salida elegido.',
  },
  pt: {
    title: 'Gerador e verificador de HMAC',
    tabGenerate: 'Gerar',
    tabVerify: 'Verificar',
    messageLabel: 'Mensagem',
    messagePlaceholder: 'Digite ou cole a mensagem a autenticar…',
    keyLabel: 'Chave secreta',
    keyPlaceholder: 'Segredo compartilhado',
    keyEncodingLabel: 'Formato da chave',
    keyEncodingText: 'Texto',
    keyEncodingHex: 'Hex',
    algorithmLabel: 'Algoritmo',
    outputEncodingLabel: 'Formato de saída',
    resultLabel: 'HMAC',
    computing: 'Calculando…',
    expectedLabel: 'HMAC esperado',
    expectedPlaceholder: 'Cole o HMAC para comparar…',
    verifyButton: 'Verificar',
    verifying: 'Verificando…',
    match: 'Confere ✓',
    noMatch: 'Não confere ✗',
    generateFailed: 'Não foi possível calcular o HMAC.',
    verifyFailed: 'Não foi possível executar a verificação.',
    error_noSecureContext:
      'Web Crypto não está disponível aqui. Abra esta página por HTTPS ou localhost.',
    error_invalidKeyHex: 'A chave não é hex válido — use apenas 0-9/a-f, um número par de dígitos.',
    error_invalidExpectedHash: 'O HMAC esperado não corresponde ao formato de saída selecionado.',
  },
};
