import type { LocalizedStrings } from '@anytools/ui';

const EN = {
  title: 'Chmod Calculator',
  who: 'Who',
  read: 'Read',
  write: 'Write',
  execute: 'Execute',
  owner: 'Owner',
  group: 'Group',
  others: 'Others',
  octal: 'Octal',
  symbolic: 'Symbolic',
  octalPermissions: 'Octal permissions',
  symbolicPermissions: 'Symbolic permissions',
};

export const STRINGS: LocalizedStrings<typeof EN> = {
  en: EN,
  vi: {
    title: 'Máy tính chmod',
    who: 'Đối tượng',
    read: 'Đọc',
    write: 'Ghi',
    execute: 'Thực thi',
    owner: 'Chủ sở hữu',
    group: 'Nhóm',
    others: 'Người khác',
    octal: 'Bát phân',
    symbolic: 'Ký hiệu',
    octalPermissions: 'Quyền dạng bát phân',
    symbolicPermissions: 'Quyền dạng ký hiệu',
  },
  es: {
    title: 'Calculadora chmod',
    who: 'Quién',
    read: 'Leer',
    write: 'Escribir',
    execute: 'Ejecutar',
    owner: 'Propietario',
    group: 'Grupo',
    others: 'Otros',
    octal: 'Octal',
    symbolic: 'Simbólico',
    octalPermissions: 'Permisos en octal',
    symbolicPermissions: 'Permisos simbólicos',
  },
  pt: {
    title: 'Calculadora chmod',
    who: 'Quem',
    read: 'Ler',
    write: 'Escrever',
    execute: 'Executar',
    owner: 'Proprietário',
    group: 'Grupo',
    others: 'Outros',
    octal: 'Octal',
    symbolic: 'Simbólico',
    octalPermissions: 'Permissões em octal',
    symbolicPermissions: 'Permissões simbólicas',
  },
};
