import type { LocalizedStrings } from '@anytools/ui';

const EN = {
  title: 'Statistics Calculator',
  description: 'Comma-, space-, or newline-separated numbers.',
  sample: 'Sample (n−1)',
  population: 'Population (n)',
  varianceMode: 'Variance/StdDev mode',
  numbers: 'Numbers',
  count: 'Count (n)',
  sum: 'Sum',
  mean: 'Mean',
  median: 'Median',
  mode: 'Mode',
  noMode: 'no mode (all unique)',
  multiModal: 'multi-modal ({n})',
  stdDev: 'Std Dev',
  variance: 'Variance',
  minMax: 'Min / Max',
  range: 'Range',
  q1q3: 'Q1 / Q3',
  enterNumbers: 'Enter numbers.',
};

export const STRINGS: LocalizedStrings<typeof EN> = {
  en: EN,
  vi: {
    title: 'Tính thống kê',
    description: 'Các số cách nhau bằng dấu phẩy, khoảng trắng hoặc xuống dòng.',
    sample: 'Mẫu (n−1)',
    population: 'Tổng thể (n)',
    varianceMode: 'Chế độ phương sai/độ lệch chuẩn',
    numbers: 'Các số',
    count: 'Số lượng (n)',
    sum: 'Tổng',
    mean: 'Trung bình',
    median: 'Trung vị',
    mode: 'Mốt',
    noMode: 'không có mốt (tất cả khác nhau)',
    multiModal: 'nhiều mốt ({n})',
    stdDev: 'Độ lệch chuẩn',
    variance: 'Phương sai',
    minMax: 'Nhỏ nhất / Lớn nhất',
    range: 'Khoảng biến thiên',
    q1q3: 'Q1 / Q3',
    enterNumbers: 'Nhập các số.',
  },
  es: {
    title: 'Calculadora de estadísticas',
    description: 'Números separados por comas, espacios o saltos de línea.',
    sample: 'Muestra (n−1)',
    population: 'Población (n)',
    varianceMode: 'Modo de varianza/desviación',
    numbers: 'Números',
    count: 'Cantidad (n)',
    sum: 'Suma',
    mean: 'Media',
    median: 'Mediana',
    mode: 'Moda',
    noMode: 'sin moda (todos únicos)',
    multiModal: 'multimodal ({n})',
    stdDev: 'Desv. estándar',
    variance: 'Varianza',
    minMax: 'Mín / Máx',
    range: 'Rango',
    q1q3: 'Q1 / Q3',
    enterNumbers: 'Introduce números.',
  },
  pt: {
    title: 'Calculadora de estatísticas',
    description: 'Números separados por vírgula, espaço ou quebra de linha.',
    sample: 'Amostra (n−1)',
    population: 'População (n)',
    varianceMode: 'Modo de variância/desvio padrão',
    numbers: 'Números',
    count: 'Quantidade (n)',
    sum: 'Soma',
    mean: 'Média',
    median: 'Mediana',
    mode: 'Moda',
    noMode: 'sem moda (todos únicos)',
    multiModal: 'multimodal ({n})',
    stdDev: 'Desvio padrão',
    variance: 'Variância',
    minMax: 'Mín / Máx',
    range: 'Amplitude',
    q1q3: 'Q1 / Q3',
    enterNumbers: 'Digite números.',
  },
};
