import type { LocalizedStrings } from '@anytools/ui';

const EN = {
  title: 'Unzip Archive',
  archiveLabel: 'Archive to open (.zip .7z .rar .tar .tar.gz)',
  passwordLabel: 'Password (only if the archive has one)',
  passwordPlaceholder: 'leave empty for a normal archive',
  working: 'Working…',
  openArchive: 'Open archive',
  readFailed: 'This archive could not be read.',
  extractFailed: 'Could not extract {path}.',
  repackFailed: 'Could not repack the archive.',
  extracting: 'Extracting {done} of {total}…',
  // {kind} archive type, {n} entries, {size} formatted bytes, {engine} reader name
  summary: '{kind} · {n} files · {size} uncompressed · read with {engine}',
  extractAll: 'Extract all to a .zip',
  downloadZip: 'Download .zip',
};

export const STRINGS: LocalizedStrings<typeof EN> = {
  en: EN,
  vi: {
    title: 'Giải nén file',
    archiveLabel: 'File nén cần mở (.zip .7z .rar .tar .tar.gz)',
    passwordLabel: 'Mật khẩu (chỉ khi file nén có đặt)',
    passwordPlaceholder: 'để trống với file nén thông thường',
    working: 'Đang xử lý…',
    openArchive: 'Mở file nén',
    readFailed: 'Không đọc được file nén này.',
    extractFailed: 'Không giải nén được {path}.',
    repackFailed: 'Không đóng gói lại được file nén.',
    extracting: 'Đang giải nén {done}/{total}…',
    summary: '{kind} · {n} tệp · {size} sau giải nén · đọc bằng {engine}',
    extractAll: 'Giải nén tất cả ra .zip',
    downloadZip: 'Tải .zip',
  },
  es: {
    title: 'Descomprimir archivo',
    archiveLabel: 'Archivo comprimido a abrir (.zip .7z .rar .tar .tar.gz)',
    passwordLabel: 'Contraseña (solo si el archivo la tiene)',
    passwordPlaceholder: 'déjalo vacío para un archivo normal',
    working: 'Trabajando…',
    openArchive: 'Abrir archivo',
    readFailed: 'No se pudo leer este archivo comprimido.',
    extractFailed: 'No se pudo extraer {path}.',
    repackFailed: 'No se pudo volver a empaquetar el archivo.',
    extracting: 'Extrayendo {done} de {total}…',
    summary: '{kind} · {n} archivos · {size} sin comprimir · leído con {engine}',
    extractAll: 'Extraer todo a un .zip',
    downloadZip: 'Descargar .zip',
  },
  pt: {
    title: 'Descompactar arquivo',
    archiveLabel: 'Pacote a abrir (.zip .7z .rar .tar .tar.gz)',
    passwordLabel: 'Senha (somente se o pacote tiver uma)',
    passwordPlaceholder: 'deixe em branco para um pacote comum',
    working: 'Trabalhando…',
    openArchive: 'Abrir pacote',
    readFailed: 'Não foi possível ler este pacote.',
    extractFailed: 'Não foi possível extrair {path}.',
    repackFailed: 'Não foi possível reempacotar o arquivo.',
    extracting: 'Extraindo {done} de {total}…',
    summary: '{kind} · {n} arquivos · {size} descompactados · lido com {engine}',
    extractAll: 'Extrair tudo para um .zip',
    downloadZip: 'Baixar .zip',
  },
};
