import type { LocalizedStrings } from '@anytools/ui';

const EN = {
  title: 'STL/OBJ Viewer',
  fileLabel: '.stl or .obj file',
  loading: 'Loading model…',
  wireframe: 'Wireframe',
  colorLabel: 'Material color',
  resetView: 'Reset view',
  screenshot: 'Save PNG',
  statsTriangles: 'Triangles',
  // {x}/{y}/{z} formatted numbers, file's own units (usually millimeters — see FAQ)
  statsSize: 'Size: {x} × {y} × {z}',
  statsVolume: 'Volume ≈ {volume} (assuming the file uses millimeters)',
  unsupportedExtension: 'Only .stl and .obj files are supported.',
  loadFailed: 'Could not load this model.',
  error_emptyMesh: 'This file has no vertices to measure.',
  error_malformedPositions: 'The vertex data in this file is malformed.',
  error_malformedIndices: 'The triangle index data in this file is malformed.',
  // {index} the bad vertex reference, {count} how many vertices actually exist
  error_indexOutOfRange: 'A triangle references vertex {index}, but the file only has {count}.',
};

export const STRINGS: LocalizedStrings<typeof EN> = {
  en: EN,
  vi: {
    title: 'Xem STL/OBJ',
    fileLabel: 'File .stl hoặc .obj',
    loading: 'Đang tải mô hình…',
    wireframe: 'Khung dây',
    colorLabel: 'Màu vật liệu',
    resetView: 'Về góc nhìn gốc',
    screenshot: 'Lưu PNG',
    statsTriangles: 'Số tam giác',
    statsSize: 'Kích thước: {x} × {y} × {z}',
    statsVolume: 'Thể tích ≈ {volume} (giả định file dùng đơn vị mm)',
    unsupportedExtension: 'Chỉ hỗ trợ file .stl và .obj.',
    loadFailed: 'Không thể tải mô hình này.',
    error_emptyMesh: 'File này không có đỉnh nào để đo.',
    error_malformedPositions: 'Dữ liệu đỉnh trong file này bị lỗi định dạng.',
    error_malformedIndices: 'Dữ liệu chỉ mục tam giác trong file này bị lỗi định dạng.',
    error_indexOutOfRange: 'Một tam giác tham chiếu đỉnh {index}, nhưng file chỉ có {count} đỉnh.',
  },
  es: {
    title: 'Visor STL/OBJ',
    fileLabel: 'Archivo .stl o .obj',
    loading: 'Cargando modelo…',
    wireframe: 'Alambre',
    colorLabel: 'Color del material',
    resetView: 'Restablecer vista',
    screenshot: 'Guardar PNG',
    statsTriangles: 'Triángulos',
    statsSize: 'Tamaño: {x} × {y} × {z}',
    statsVolume: 'Volumen ≈ {volume} (asumiendo que el archivo usa milímetros)',
    unsupportedExtension: 'Solo se admiten archivos .stl y .obj.',
    loadFailed: 'No se pudo cargar este modelo.',
    error_emptyMesh: 'Este archivo no tiene vértices que medir.',
    error_malformedPositions: 'Los datos de vértices de este archivo están mal formados.',
    error_malformedIndices: 'Los datos de índice de triángulos de este archivo están mal formados.',
    error_indexOutOfRange:
      'Un triángulo referencia el vértice {index}, pero el archivo solo tiene {count}.',
  },
  pt: {
    title: 'Visualizador STL/OBJ',
    fileLabel: 'Arquivo .stl ou .obj',
    loading: 'Carregando modelo…',
    wireframe: 'Wireframe',
    colorLabel: 'Cor do material',
    resetView: 'Redefinir vista',
    screenshot: 'Salvar PNG',
    statsTriangles: 'Triângulos',
    statsSize: 'Tamanho: {x} × {y} × {z}',
    statsVolume: 'Volume ≈ {volume} (assumindo que o arquivo usa milímetros)',
    unsupportedExtension: 'Somente arquivos .stl e .obj são aceitos.',
    loadFailed: 'Não foi possível carregar este modelo.',
    error_emptyMesh: 'Este arquivo não tem vértices para medir.',
    error_malformedPositions: 'Os dados de vértices deste arquivo estão malformados.',
    error_malformedIndices: 'Os dados de índice de triângulos deste arquivo estão malformados.',
    error_indexOutOfRange:
      'Um triângulo referencia o vértice {index}, mas o arquivo só tem {count}.',
  },
};
