import type { LocalizedStrings } from '@anytools/ui';

const EN = {
  title: 'Rotate Image',
  dropLabel: 'Photos to rotate',
  rotateLeft: 'Rotate left 90°',
  rotateRight: 'Rotate right 90°',
  rotate180: 'Rotate 180°',
  flipHorizontal: 'Flip horizontal',
  flipVertical: 'Flip vertical',
  currentState: 'Current: {rotate}° · {flip}',
  flipNone: 'no flip',
  flipH: 'flipped horizontally',
  flipV: 'flipped vertically',
  flipBoth: 'flipped both ways',
  before: 'Before',
  afterPreview: 'After (live preview)',
  outputFormat: 'Output format',
  formatOriginal: 'Keep original',
  quality: 'Quality ({n}%)',
  qualityLabel: 'Quality',
  rotateOne: 'Rotate image',
  rotateMany: 'Rotate {n} images',
  rotating: 'Rotating…',
  rotatingProgress: 'Rotating… {done}/{total}',
  downloadAllZip: 'Download all {n} as .zip',
  zipFailed: 'Could not build the .zip.',
  scaledOne: 'One photo was decoded at a reduced size — see its card below for the numbers.',
  scaledMany: '{n} photos were decoded at a reduced size — see their cards below for the numbers.',
  scaledFrom: '(scaled down from {w} × {h})',
  failed: 'Rotation failed',
};

export const STRINGS: LocalizedStrings<typeof EN> = {
  en: EN,
  vi: {
    title: 'Xoay Ảnh',
    dropLabel: 'Ảnh cần xoay',
    rotateLeft: 'Xoay trái 90°',
    rotateRight: 'Xoay phải 90°',
    rotate180: 'Xoay 180°',
    flipHorizontal: 'Lật ngang',
    flipVertical: 'Lật dọc',
    currentState: 'Hiện tại: {rotate}° · {flip}',
    flipNone: 'không lật',
    flipH: 'đã lật ngang',
    flipV: 'đã lật dọc',
    flipBoth: 'đã lật cả hai chiều',
    before: 'Trước',
    afterPreview: 'Sau (xem trước trực tiếp)',
    outputFormat: 'Định dạng xuất',
    formatOriginal: 'Giữ định dạng gốc',
    quality: 'Chất lượng ({n}%)',
    qualityLabel: 'Chất lượng',
    rotateOne: 'Xoay ảnh',
    rotateMany: 'Xoay {n} ảnh',
    rotating: 'Đang xoay…',
    rotatingProgress: 'Đang xoay… {done}/{total}',
    downloadAllZip: 'Tải cả {n} ảnh dạng .zip',
    zipFailed: 'Không thể tạo file .zip.',
    scaledOne: 'Một ảnh đã được giải mã ở kích thước thu nhỏ — xem số liệu ở thẻ bên dưới.',
    scaledMany: '{n} ảnh đã được giải mã ở kích thước thu nhỏ — xem số liệu ở các thẻ bên dưới.',
    scaledFrom: '(thu nhỏ từ {w} × {h})',
    failed: 'Xoay ảnh thất bại',
  },
  es: {
    title: 'Rotar Imagen',
    dropLabel: 'Fotos a rotar',
    rotateLeft: 'Rotar izquierda 90°',
    rotateRight: 'Rotar derecha 90°',
    rotate180: 'Rotar 180°',
    flipHorizontal: 'Voltear horizontal',
    flipVertical: 'Voltear vertical',
    currentState: 'Actual: {rotate}° · {flip}',
    flipNone: 'sin voltear',
    flipH: 'volteada en horizontal',
    flipV: 'volteada en vertical',
    flipBoth: 'volteada en ambos sentidos',
    before: 'Antes',
    afterPreview: 'Después (vista previa en vivo)',
    outputFormat: 'Formato de salida',
    formatOriginal: 'Mantener el original',
    quality: 'Calidad ({n}%)',
    qualityLabel: 'Calidad',
    rotateOne: 'Rotar imagen',
    rotateMany: 'Rotar {n} imágenes',
    rotating: 'Rotando…',
    rotatingProgress: 'Rotando… {done}/{total}',
    downloadAllZip: 'Descargar las {n} en .zip',
    zipFailed: 'No se pudo crear el .zip.',
    scaledOne: 'Una foto se decodificó a un tamaño reducido — mira su tarjeta abajo.',
    scaledMany: '{n} fotos se decodificaron a un tamaño reducido — mira sus tarjetas abajo.',
    scaledFrom: '(reducida desde {w} × {h})',
    failed: 'Error al rotar',
  },
  pt: {
    title: 'Girar Imagem',
    dropLabel: 'Fotos para girar',
    rotateLeft: 'Girar à esquerda 90°',
    rotateRight: 'Girar à direita 90°',
    rotate180: 'Girar 180°',
    flipHorizontal: 'Espelhar horizontal',
    flipVertical: 'Espelhar vertical',
    currentState: 'Atual: {rotate}° · {flip}',
    flipNone: 'sem espelhar',
    flipH: 'espelhada na horizontal',
    flipV: 'espelhada na vertical',
    flipBoth: 'espelhada nos dois sentidos',
    before: 'Antes',
    afterPreview: 'Depois (pré-visualização ao vivo)',
    outputFormat: 'Formato de saída',
    formatOriginal: 'Manter o original',
    quality: 'Qualidade ({n}%)',
    qualityLabel: 'Qualidade',
    rotateOne: 'Girar imagem',
    rotateMany: 'Girar {n} imagens',
    rotating: 'Girando…',
    rotatingProgress: 'Girando… {done}/{total}',
    downloadAllZip: 'Baixar as {n} em .zip',
    zipFailed: 'Não foi possível criar o .zip.',
    scaledOne: 'Uma foto foi decodificada em tamanho reduzido — veja o cartão abaixo.',
    scaledMany: '{n} fotos foram decodificadas em tamanho reduzido — veja os cartões abaixo.',
    scaledFrom: '(reduzida a partir de {w} × {h})',
    failed: 'Falha ao girar',
  },
};
