import type { LocalizedStrings } from '@anytools/ui';

const EN = {
  title: 'Color Converter + Contrast Checker',
  description: 'HEX ↔ RGB ↔ HSL plus WCAG 2.1 AA/AAA contrast ratio.',
  foreground: 'Foreground (text)',
  foregroundColor: 'Foreground color',
  foregroundHex: 'Foreground hex',
  background: 'Background',
  backgroundColor: 'Background color',
  backgroundHex: 'Background hex',
  livePreview: 'Live preview',
  sampleLine1: 'The quick brown fox',
  sampleLine2: 'jumps over the lazy dog.',
  wcagTitle: 'WCAG 2.1 Contrast',
  contrastRatio: 'Contrast ratio',
  aaNormal: 'AA normal text (4.5:1)',
  aaLarge: 'AA large text (3:1)',
  aaaNormal: 'AAA normal text (7:1)',
  aaaLarge: 'AAA large text (4.5:1)',
  pass: 'Pass',
  fail: 'Fail',
};

export const STRINGS: LocalizedStrings<typeof EN> = {
  en: EN,
  vi: {
    title: 'Chuyển đổi màu + Kiểm tra tương phản',
    description: 'HEX ↔ RGB ↔ HSL kèm tỷ lệ tương phản WCAG 2.1 AA/AAA.',
    foreground: 'Màu chữ (foreground)',
    foregroundColor: 'Màu chữ',
    foregroundHex: 'Mã hex màu chữ',
    background: 'Màu nền',
    backgroundColor: 'Màu nền',
    backgroundHex: 'Mã hex màu nền',
    livePreview: 'Xem trước trực tiếp',
    sampleLine1: 'Con cáo nâu nhanh nhẹn',
    sampleLine2: 'nhảy qua con chó lười.',
    wcagTitle: 'Tương phản WCAG 2.1',
    contrastRatio: 'Tỷ lệ tương phản',
    aaNormal: 'AA chữ thường (4.5:1)',
    aaLarge: 'AA chữ lớn (3:1)',
    aaaNormal: 'AAA chữ thường (7:1)',
    aaaLarge: 'AAA chữ lớn (4.5:1)',
    pass: 'Đạt',
    fail: 'Không đạt',
  },
  es: {
    title: 'Conversor de color + Verificador de contraste',
    description: 'HEX ↔ RGB ↔ HSL más la relación de contraste WCAG 2.1 AA/AAA.',
    foreground: 'Primer plano (texto)',
    foregroundColor: 'Color de primer plano',
    foregroundHex: 'Hex de primer plano',
    background: 'Fondo',
    backgroundColor: 'Color de fondo',
    backgroundHex: 'Hex de fondo',
    livePreview: 'Vista previa en vivo',
    sampleLine1: 'El veloz murciélago hindú',
    sampleLine2: 'comía feliz cardillo y kiwi.',
    wcagTitle: 'Contraste WCAG 2.1',
    contrastRatio: 'Relación de contraste',
    aaNormal: 'AA texto normal (4.5:1)',
    aaLarge: 'AA texto grande (3:1)',
    aaaNormal: 'AAA texto normal (7:1)',
    aaaLarge: 'AAA texto grande (4.5:1)',
    pass: 'Pasa',
    fail: 'Falla',
  },
  pt: {
    title: 'Conversor de cores + Verificador de contraste',
    description: 'HEX ↔ RGB ↔ HSL mais a taxa de contraste WCAG 2.1 AA/AAA.',
    foreground: 'Primeiro plano (texto)',
    foregroundColor: 'Cor do primeiro plano',
    foregroundHex: 'Hex do primeiro plano',
    background: 'Fundo',
    backgroundColor: 'Cor de fundo',
    backgroundHex: 'Hex do fundo',
    livePreview: 'Pré-visualização ao vivo',
    sampleLine1: 'A rápida raposa marrom',
    sampleLine2: 'salta sobre o cão preguiçoso.',
    wcagTitle: 'Contraste WCAG 2.1',
    contrastRatio: 'Taxa de contraste',
    aaNormal: 'AA texto normal (4.5:1)',
    aaLarge: 'AA texto grande (3:1)',
    aaaNormal: 'AAA texto normal (7:1)',
    aaaLarge: 'AAA texto grande (4.5:1)',
    pass: 'Aprovado',
    fail: 'Reprovado',
  },
};
