import type { LocalizedStrings } from '@anytools/ui';

const EN = {
  title: 'Token Counter',
  description: 'Paste text below to see how many tokens it costs against an OpenAI model.',
  inputLabel: 'Text to count',
  placeholder: 'Paste text here…',
  encodingLabel: 'Encoding',
  encodingCl100k: 'cl100k_base — GPT-4, GPT-3.5',
  encodingO200k: 'o200k_base — GPT-4o, GPT-5 family',
  loadingRanks: 'Loading the token table (first run only)…',
  loadFailed: 'Could not load the token table. Check your connection and try again.',
  tokens: 'Tokens',
  characters: 'Characters',
  words: 'Words',
  usedBy: 'Used by',
  note: 'This is OpenAI’s own tokenizer. Claude and Gemini split text differently, so treat this as an estimate for those models, not an exact count.',
};

export const STRINGS: LocalizedStrings<typeof EN> = {
  en: EN,
  vi: {
    title: 'Đếm Token',
    description: 'Dán văn bản bên dưới để xem nó tốn bao nhiêu token với một model của OpenAI.',
    inputLabel: 'Văn bản cần đếm',
    placeholder: 'Dán văn bản vào đây…',
    encodingLabel: 'Bộ mã hoá',
    encodingCl100k: 'cl100k_base — GPT-4, GPT-3.5',
    encodingO200k: 'o200k_base — dòng GPT-4o, GPT-5',
    loadingRanks: 'Đang tải bảng token (chỉ lần đầu)…',
    loadFailed: 'Không tải được bảng token. Kiểm tra kết nối rồi thử lại.',
    tokens: 'Số token',
    characters: 'Số ký tự',
    words: 'Số từ',
    usedBy: 'Dùng bởi',
    note: 'Đây là bộ tách token riêng của OpenAI. Claude và Gemini tách khác, nên với hai model đó con số này chỉ để ước lượng, không phải số chính xác.',
  },
  es: {
    title: 'Contador de tokens',
    description: 'Pega texto abajo para ver cuántos tokens cuesta en un modelo de OpenAI.',
    inputLabel: 'Texto a contar',
    placeholder: 'Pega el texto aquí…',
    encodingLabel: 'Codificación',
    encodingCl100k: 'cl100k_base — GPT-4, GPT-3.5',
    encodingO200k: 'o200k_base — familia GPT-4o, GPT-5',
    loadingRanks: 'Cargando la tabla de tokens (solo la primera vez)…',
    loadFailed: 'No se pudo cargar la tabla de tokens. Revisa tu conexión e inténtalo de nuevo.',
    tokens: 'Tokens',
    characters: 'Caracteres',
    words: 'Palabras',
    usedBy: 'Usado por',
    note: 'Este es el tokenizador propio de OpenAI. Claude y Gemini dividen el texto de otra forma, así que para esos modelos toma este número como una estimación, no como un conteo exacto.',
  },
  pt: {
    title: 'Contador de tokens',
    description: 'Cole o texto abaixo para ver quantos tokens ele custa num modelo da OpenAI.',
    inputLabel: 'Texto para contar',
    placeholder: 'Cole o texto aqui…',
    encodingLabel: 'Codificação',
    encodingCl100k: 'cl100k_base — GPT-4, GPT-3.5',
    encodingO200k: 'o200k_base — família GPT-4o, GPT-5',
    loadingRanks: 'Carregando a tabela de tokens (só na primeira vez)…',
    loadFailed:
      'Não foi possível carregar a tabela de tokens. Verifique sua conexão e tente de novo.',
    tokens: 'Tokens',
    characters: 'Caracteres',
    words: 'Palavras',
    usedBy: 'Usado por',
    note: 'Este é o tokenizador da própria OpenAI. Claude e Gemini dividem o texto de outro jeito, então para esses modelos trate este número como uma estimativa, não uma contagem exata.',
  },
};
