import type { LocalizedStrings } from '@anytools/ui';

const EN = {
  title: 'Meta Tag Generator',
  pageTitle: 'Page title',
  pageTitlePlaceholder: 'Shown as the headline in search results',
  description: 'Description',
  canonicalUrl: 'Canonical URL',
  previewImageUrl: 'Preview image URL',
  siteName: 'Site name',
  author: 'Author',
  optional: 'Optional',
  twitterHandle: 'X / Twitter handle',
  cardType: 'Card type',
  cardLargeImage: 'Large image',
  cardSummary: 'Summary',
  robots: 'Robots',
  pasteIntoHead: 'Paste into <head>',
  error_titleLong: '{count} characters — search results usually cut off around {limit}.',
  error_descriptionLong: '{count} characters — snippets usually cut off around {limit}.',
  error_imageAbsolute:
    'og:image must be an absolute URL — crawlers fetch it without your page context.',
  error_urlAbsolute: 'og:url must be absolute.',
  error_handleAt: 'Handles start with @.',
  error_largeCardNoImage: 'A large-image card with no image falls back to a plain summary card.',
};

export const STRINGS: LocalizedStrings<typeof EN> = {
  en: EN,
  vi: {
    title: 'Tạo thẻ meta',
    pageTitle: 'Tiêu đề trang',
    pageTitlePlaceholder: 'Hiển thị làm tiêu đề trong kết quả tìm kiếm',
    description: 'Mô tả',
    canonicalUrl: 'URL chuẩn (canonical)',
    previewImageUrl: 'URL ảnh xem trước',
    siteName: 'Tên trang web',
    author: 'Tác giả',
    optional: 'Không bắt buộc',
    twitterHandle: 'Tài khoản X / Twitter',
    cardType: 'Kiểu thẻ',
    cardLargeImage: 'Ảnh lớn',
    cardSummary: 'Tóm tắt',
    robots: 'Robots',
    pasteIntoHead: 'Dán vào <head>',
    error_titleLong: '{count} ký tự — kết quả tìm kiếm thường cắt ở khoảng {limit}.',
    error_descriptionLong: '{count} ký tự — đoạn mô tả thường cắt ở khoảng {limit}.',
    error_imageAbsolute:
      'og:image phải là URL tuyệt đối — trình thu thập tải nó mà không có ngữ cảnh trang của bạn.',
    error_urlAbsolute: 'og:url phải là URL tuyệt đối.',
    error_handleAt: 'Tên tài khoản bắt đầu bằng @.',
    error_largeCardNoImage: 'Thẻ ảnh lớn không có ảnh sẽ rơi về thẻ tóm tắt thường.',
  },
  es: {
    title: 'Generador de meta tags',
    pageTitle: 'Título de la página',
    pageTitlePlaceholder: 'Se muestra como titular en los resultados de búsqueda',
    description: 'Descripción',
    canonicalUrl: 'URL canónica',
    previewImageUrl: 'URL de la imagen de vista previa',
    siteName: 'Nombre del sitio',
    author: 'Autor',
    optional: 'Opcional',
    twitterHandle: 'Usuario de X / Twitter',
    cardType: 'Tipo de tarjeta',
    cardLargeImage: 'Imagen grande',
    cardSummary: 'Resumen',
    robots: 'Robots',
    pasteIntoHead: 'Pegar en <head>',
    error_titleLong:
      '{count} caracteres: los resultados de búsqueda suelen cortarse alrededor de {limit}.',
    error_descriptionLong:
      '{count} caracteres: los fragmentos suelen cortarse alrededor de {limit}.',
    error_imageAbsolute:
      'og:image debe ser una URL absoluta: los rastreadores la obtienen sin el contexto de tu página.',
    error_urlAbsolute: 'og:url debe ser absoluta.',
    error_handleAt: 'Los identificadores empiezan por @.',
    error_largeCardNoImage:
      'Una tarjeta de imagen grande sin imagen se muestra como una tarjeta de resumen simple.',
  },
  pt: {
    title: 'Gerador de meta tags',
    pageTitle: 'Título da página',
    pageTitlePlaceholder: 'Aparece como manchete nos resultados de busca',
    description: 'Descrição',
    canonicalUrl: 'URL canônica',
    previewImageUrl: 'URL da imagem de pré-visualização',
    siteName: 'Nome do site',
    author: 'Autor',
    optional: 'Opcional',
    twitterHandle: 'Usuário do X / Twitter',
    cardType: 'Tipo de card',
    cardLargeImage: 'Imagem grande',
    cardSummary: 'Resumo',
    robots: 'Robots',
    pasteIntoHead: 'Colar no <head>',
    error_titleLong:
      '{count} caracteres — os resultados de busca costumam cortar por volta de {limit}.',
    error_descriptionLong: '{count} caracteres — os trechos costumam cortar por volta de {limit}.',
    error_imageAbsolute:
      'og:image precisa ser uma URL absoluta — os rastreadores a buscam sem o contexto da sua página.',
    error_urlAbsolute: 'og:url precisa ser absoluta.',
    error_handleAt: 'Identificadores começam com @.',
    error_largeCardNoImage:
      'Um cartão de imagem grande sem imagem vira um cartão de resumo simples.',
  },
};
