import type { LocalizedStrings } from '@anytools/ui';

const EN = {
  title: 'Meta Tag Generator',
  pageTitle: 'Page title',
  pageTitlePlaceholder: 'Shown as the headline in search results',
  description: 'Description',
  canonicalUrl: 'Canonical URL',
  previewImageUrl: 'Preview image URL',
  siteName: 'Site name',
  author: 'Author',
  optional: 'Optional',
  twitterHandle: 'X / Twitter handle',
  cardType: 'Card type',
  cardLargeImage: 'Large image',
  cardSummary: 'Summary',
  robots: 'Robots',
  pasteIntoHead: 'Paste into <head>',
};

export const STRINGS: LocalizedStrings<typeof EN> = {
  en: EN,
  vi: {
    title: 'Tạo thẻ meta',
    pageTitle: 'Tiêu đề trang',
    pageTitlePlaceholder: 'Hiển thị làm tiêu đề trong kết quả tìm kiếm',
    description: 'Mô tả',
    canonicalUrl: 'URL chuẩn (canonical)',
    previewImageUrl: 'URL ảnh xem trước',
    siteName: 'Tên trang web',
    author: 'Tác giả',
    optional: 'Không bắt buộc',
    twitterHandle: 'Tài khoản X / Twitter',
    cardType: 'Kiểu thẻ',
    cardLargeImage: 'Ảnh lớn',
    cardSummary: 'Tóm tắt',
    robots: 'Robots',
    pasteIntoHead: 'Dán vào <head>',
  },
  es: {
    title: 'Generador de meta tags',
    pageTitle: 'Título de la página',
    pageTitlePlaceholder: 'Se muestra como titular en los resultados de búsqueda',
    description: 'Descripción',
    canonicalUrl: 'URL canónica',
    previewImageUrl: 'URL de la imagen de vista previa',
    siteName: 'Nombre del sitio',
    author: 'Autor',
    optional: 'Opcional',
    twitterHandle: 'Usuario de X / Twitter',
    cardType: 'Tipo de tarjeta',
    cardLargeImage: 'Imagen grande',
    cardSummary: 'Resumen',
    robots: 'Robots',
    pasteIntoHead: 'Pegar en <head>',
  },
  pt: {
    title: 'Gerador de meta tags',
    pageTitle: 'Título da página',
    pageTitlePlaceholder: 'Aparece como manchete nos resultados de busca',
    description: 'Descrição',
    canonicalUrl: 'URL canônica',
    previewImageUrl: 'URL da imagem de pré-visualização',
    siteName: 'Nome do site',
    author: 'Autor',
    optional: 'Opcional',
    twitterHandle: 'Usuário do X / Twitter',
    cardType: 'Tipo de card',
    cardLargeImage: 'Imagem grande',
    cardSummary: 'Resumo',
    robots: 'Robots',
    pasteIntoHead: 'Colar no <head>',
  },
};
