import type { LocalizedStrings } from '@anytools/ui';

const EN = {
  title: 'Image Format Converter',
  sourceImage: 'Source image (PNG, JPEG, WebP, AVIF, GIF) — max 10 MB',
  targetFormat: 'Target format',
  quality: 'Quality: {p}%',
  converting: 'Converting…',
  larger: 'larger',
  smaller: 'smaller',
  convertedPreview: 'Converted preview',
  downloadFile: 'Download {name}',
  // {size} in MB with one decimal, {max} in MB; {format} is png / jpeg / webp.
  error_tooLarge: 'File too large: {size} MB (max {max} MB)',
  error_noCanvas: 'Canvas 2D context not available',
  error_noEncoder: 'Encoder for {format} not supported in this browser',
  error_readFailed: 'Failed to read file',
  error_decodeFailed: 'Failed to decode image (unsupported format or corrupt file)',
};

export const STRINGS: LocalizedStrings<typeof EN> = {
  en: EN,
  vi: {
    title: 'Chuyển đổi định dạng ảnh',
    sourceImage: 'Ảnh nguồn (PNG, JPEG, WebP, AVIF, GIF) — tối đa 10 MB',
    targetFormat: 'Định dạng đích',
    quality: 'Chất lượng: {p}%',
    converting: 'Đang chuyển đổi…',
    larger: 'lớn hơn',
    smaller: 'nhỏ hơn',
    convertedPreview: 'Xem trước ảnh đã chuyển',
    downloadFile: 'Tải {name}',
    error_tooLarge: 'Tệp quá lớn: {size} MB (tối đa {max} MB)',
    error_noCanvas: 'Không có canvas 2D context',
    error_noEncoder: 'Trình duyệt này không hỗ trợ mã hoá {format}',
    error_readFailed: 'Không đọc được tệp',
    error_decodeFailed: 'Không giải mã được ảnh (định dạng không hỗ trợ hoặc tệp hỏng)',
  },
  es: {
    title: 'Conversor de formato de imagen',
    sourceImage: 'Imagen de origen (PNG, JPEG, WebP, AVIF, GIF) — máx. 10 MB',
    targetFormat: 'Formato de destino',
    quality: 'Calidad: {p}%',
    converting: 'Convirtiendo…',
    larger: 'más grande',
    smaller: 'más pequeño',
    convertedPreview: 'Vista previa convertida',
    downloadFile: 'Descargar {name}',
    error_tooLarge: 'Archivo demasiado grande: {size} MB (máx. {max} MB)',
    error_noCanvas: 'Contexto 2D de canvas no disponible',
    error_noEncoder: 'Este navegador no admite el codificador de {format}',
    error_readFailed: 'No se pudo leer el archivo',
    error_decodeFailed: 'No se pudo decodificar la imagen (formato no admitido o archivo dañado)',
  },
  pt: {
    title: 'Conversor de formato de imagem',
    sourceImage: 'Imagem de origem (PNG, JPEG, WebP, AVIF, GIF) — máx. 10 MB',
    targetFormat: 'Formato de destino',
    quality: 'Qualidade: {p}%',
    converting: 'Convertendo…',
    larger: 'maior',
    smaller: 'menor',
    convertedPreview: 'Pré-visualização convertida',
    downloadFile: 'Baixar {name}',
    error_tooLarge: 'Arquivo muito grande: {size} MB (máx. {max} MB)',
    error_noCanvas: 'Contexto 2D do canvas não disponível',
    error_noEncoder: 'Este navegador não suporta o codificador de {format}',
    error_readFailed: 'Não foi possível ler o arquivo',
    error_decodeFailed:
      'Não foi possível decodificar a imagem (formato não suportado ou arquivo corrompido)',
  },
};
