import type { LocalizedStrings } from '@anytools/ui';

const EN = {
  title: 'Create ZIP',
  filesLabel: 'Files to put in the archive',
  compressionLevel: 'Compression level',
  levelStore: 'store, no compression',
  folderLabel: 'Folder inside the zip (optional)',
  folderPlaceholder: 'e.g. invoices',
  zipping: 'Zipping…',
  createZip: 'Create .zip',
  createZipFrom: 'Create .zip from {n} files',
  buildFailed: 'Could not build the archive.',
  // {n} files, {in} / {out} formatted sizes
  summary: '{n} files · {in} in, {out} out',
  smaller: '{p}% smaller',
  downloadZip: 'Download .zip',
};

export const STRINGS: LocalizedStrings<typeof EN> = {
  en: EN,
  vi: {
    title: 'Tạo file ZIP',
    filesLabel: 'Các tệp cần đưa vào file nén',
    compressionLevel: 'Mức nén',
    levelStore: 'chỉ lưu, không nén',
    folderLabel: 'Thư mục bên trong file zip (tuỳ chọn)',
    folderPlaceholder: 'vd. hoa-don',
    zipping: 'Đang nén…',
    createZip: 'Tạo .zip',
    createZipFrom: 'Tạo .zip từ {n} tệp',
    buildFailed: 'Không thể tạo file nén.',
    summary: '{n} tệp · vào {in}, ra {out}',
    smaller: 'nhỏ hơn {p}%',
    downloadZip: 'Tải .zip',
  },
  es: {
    title: 'Crear ZIP',
    filesLabel: 'Archivos para incluir en el archivo comprimido',
    compressionLevel: 'Nivel de compresión',
    levelStore: 'almacenar, sin compresión',
    folderLabel: 'Carpeta dentro del zip (opcional)',
    folderPlaceholder: 'p. ej. facturas',
    zipping: 'Comprimiendo…',
    createZip: 'Crear .zip',
    createZipFrom: 'Crear .zip con {n} archivos',
    buildFailed: 'No se pudo crear el archivo comprimido.',
    summary: '{n} archivos · {in} de entrada, {out} de salida',
    smaller: '{p}% más pequeño',
    downloadZip: 'Descargar .zip',
  },
  pt: {
    title: 'Criar ZIP',
    filesLabel: 'Arquivos para colocar no pacote',
    compressionLevel: 'Nível de compressão',
    levelStore: 'armazenar, sem compressão',
    folderLabel: 'Pasta dentro do zip (opcional)',
    folderPlaceholder: 'ex.: faturas',
    zipping: 'Compactando…',
    createZip: 'Criar .zip',
    createZipFrom: 'Criar .zip com {n} arquivos',
    buildFailed: 'Não foi possível criar o pacote.',
    summary: '{n} arquivos · {in} de entrada, {out} de saída',
    smaller: '{p}% menor',
    downloadZip: 'Baixar .zip',
  },
};
