import type { LocalizedStrings } from '@anytools/ui';

const EN = {
  title: 'WCAG Contrast Checker',
  textColor: 'Text color',
  backgroundColor: 'Background color',
  picker: '{label} picker',
  hex: '{label} hex',
  swapColors: 'Swap colors',
  largeText: 'Large text 24px',
  normalText: 'Normal text — the quick brown fox jumps over the lazy dog.',
  aa: 'AA',
  aaLarge: 'AA large',
  aaa: 'AAA',
  aaaLarge: 'AAA large',
  closestPassing: 'Closest AA-passing text color:',
  sameHue: 'Same hue direction, nudged until 4.5:1.',
  enterHex: 'Enter valid hex colors (#rgb or #rrggbb) to see the ratio.',
};

export const STRINGS: LocalizedStrings<typeof EN> = {
  en: EN,
  vi: {
    title: 'Kiểm tra tương phản WCAG',
    textColor: 'Màu chữ',
    backgroundColor: 'Màu nền',
    picker: 'Bộ chọn {label}',
    hex: 'Mã hex {label}',
    swapColors: 'Hoán đổi màu',
    largeText: 'Chữ lớn 24px',
    normalText: 'Chữ thường — con cáo nâu nhanh nhẹn nhảy qua con chó lười.',
    aa: 'AA',
    aaLarge: 'AA chữ lớn',
    aaa: 'AAA',
    aaaLarge: 'AAA chữ lớn',
    closestPassing: 'Màu chữ gần nhất đạt AA:',
    sameHue: 'Cùng hướng sắc độ, điều chỉnh dần đến 4.5:1.',
    enterHex: 'Nhập mã màu hex hợp lệ (#rgb hoặc #rrggbb) để xem tỷ lệ.',
  },
  es: {
    title: 'Verificador de contraste WCAG',
    textColor: 'Color del texto',
    backgroundColor: 'Color de fondo',
    picker: 'Selector de {label}',
    hex: 'Hex de {label}',
    swapColors: 'Intercambiar colores',
    largeText: 'Texto grande 24px',
    normalText: 'Texto normal: el veloz murciélago hindú comía feliz cardillo y kiwi.',
    aa: 'AA',
    aaLarge: 'AA grande',
    aaa: 'AAA',
    aaaLarge: 'AAA grande',
    closestPassing: 'Color de texto más cercano que pasa AA:',
    sameHue: 'Misma dirección de tono, ajustado hasta 4.5:1.',
    enterHex: 'Introduce colores hex válidos (#rgb o #rrggbb) para ver la relación.',
  },
  pt: {
    title: 'Verificador de contraste WCAG',
    textColor: 'Cor do texto',
    backgroundColor: 'Cor de fundo',
    picker: 'Seletor de {label}',
    hex: 'Hex de {label}',
    swapColors: 'Trocar cores',
    largeText: 'Texto grande 24px',
    normalText: 'Texto normal: a rápida raposa marrom salta sobre o cão preguiçoso.',
    aa: 'AA',
    aaLarge: 'AA grande',
    aaa: 'AAA',
    aaaLarge: 'AAA grande',
    closestPassing: 'Cor de texto mais próxima que passa no AA:',
    sameHue: 'Mesma direção de matiz, ajustada até 4.5:1.',
    enterHex: 'Digite cores hex válidas (#rgb ou #rrggbb) para ver a taxa.',
  },
};
