import type { LocalizedStrings } from '@anytools/ui';

const EN = {
  title: 'UUID Generator',
  v7: 'v7 (recommended)',
  v4: 'v4 (random)',
  v1: 'v1 (timestamp + MAC)',
  v7Note: 'Sortable by time, recommended for new database keys.',
  v4Note: 'Fully random. Universally supported. Default for most libraries.',
  v1Note: 'Includes timestamp + node ID. Legacy; prefer v7.',
  count: 'Count (1–100)',
  showDashes: 'Show dashes',
  validateTitle: 'Validate a UUID',
  validatePlaceholder: 'Paste a UUID to detect version',
  // {v} is the variant name reported by the logic layer.
  variant: 'Variant: {v}',
  invalidUuid: 'Invalid UUID',
};

export const STRINGS: LocalizedStrings<typeof EN> = {
  en: EN,
  vi: {
    title: 'Tạo UUID',
    v7: 'v7 (khuyên dùng)',
    v4: 'v4 (ngẫu nhiên)',
    v1: 'v1 (thời gian + MAC)',
    v7Note: 'Sắp xếp được theo thời gian, khuyên dùng cho khóa cơ sở dữ liệu mới.',
    v4Note: 'Hoàn toàn ngẫu nhiên. Được hỗ trợ rộng rãi. Mặc định của hầu hết thư viện.',
    v1Note: 'Chứa dấu thời gian + ID nút. Kiểu cũ; nên dùng v7.',
    count: 'Số lượng (1–100)',
    showDashes: 'Hiện dấu gạch ngang',
    validateTitle: 'Kiểm tra một UUID',
    validatePlaceholder: 'Dán UUID để nhận diện phiên bản',
    variant: 'Biến thể: {v}',
    invalidUuid: 'UUID không hợp lệ',
  },
  es: {
    title: 'Generador de UUID',
    v7: 'v7 (recomendado)',
    v4: 'v4 (aleatorio)',
    v1: 'v1 (marca de tiempo + MAC)',
    v7Note: 'Ordenable por tiempo, recomendado para nuevas claves de base de datos.',
    v4Note: 'Totalmente aleatorio. Soporte universal. Predeterminado en la mayoría de bibliotecas.',
    v1Note: 'Incluye marca de tiempo + ID de nodo. Heredado; prefiere v7.',
    count: 'Cantidad (1–100)',
    showDashes: 'Mostrar guiones',
    validateTitle: 'Validar un UUID',
    validatePlaceholder: 'Pega un UUID para detectar la versión',
    variant: 'Variante: {v}',
    invalidUuid: 'UUID no válido',
  },
  pt: {
    title: 'Gerador de UUID',
    v7: 'v7 (recomendado)',
    v4: 'v4 (aleatório)',
    v1: 'v1 (timestamp + MAC)',
    v7Note: 'Ordenável por tempo, recomendado para novas chaves de banco de dados.',
    v4Note: 'Totalmente aleatório. Suporte universal. Padrão na maioria das bibliotecas.',
    v1Note: 'Inclui timestamp + ID do nó. Legado; prefira v7.',
    count: 'Quantidade (1–100)',
    showDashes: 'Mostrar hífens',
    validateTitle: 'Validar um UUID',
    validatePlaceholder: 'Cole um UUID para detectar a versão',
    variant: 'Variante: {v}',
    invalidUuid: 'UUID inválido',
  },
};
