import type { LocalizedStrings } from '@anytools/ui';

const EN = {
  title: 'Scientific Calculator',
  description:
    'Functions: sin, cos, tan, asin, acos, atan, log (base 10), ln, sqrt, exp, abs, !, ^. Constants: pi, e.',
  placeholder: 'e.g. sin(pi/4) + sqrt(16)',
  expression: 'Expression',
  backspace: 'Backspace',
  error: 'Error',
  syntaxError: 'Syntax error',
  error_invalidNumber: 'Invalid number at {pos}',
  error_unexpectedChar: 'Unexpected character "{char}" at {pos}',
  error_unexpectedEnd: 'Unexpected end of input',
  error_expectedToken: 'Expected "{token}"',
  error_expectedClose: 'Expected ")"',
  error_unknownIdentifier: 'Unknown identifier "{name}"',
  error_unknownFunction: 'Unknown function "{name}"',
  error_takesOneArg: '{name}() takes 1 argument',
  error_takesTwoArgs: '{name}() takes 2 arguments',
  error_unexpectedToken: 'Unexpected token',
};

export const STRINGS: LocalizedStrings<typeof EN> = {
  en: EN,
  vi: {
    title: 'Máy tính khoa học',
    description:
      'Hàm: sin, cos, tan, asin, acos, atan, log (cơ số 10), ln, sqrt, exp, abs, !, ^. Hằng số: pi, e.',
    placeholder: 'vd: sin(pi/4) + sqrt(16)',
    expression: 'Biểu thức',
    backspace: 'Xóa lùi',
    error: 'Lỗi',
    syntaxError: 'Lỗi cú pháp',
    error_invalidNumber: 'Số không hợp lệ tại vị trí {pos}',
    error_unexpectedChar: 'Ký tự không mong đợi "{char}" tại vị trí {pos}',
    error_unexpectedEnd: 'Biểu thức kết thúc đột ngột',
    error_expectedToken: 'Cần "{token}"',
    error_expectedClose: 'Cần ")"',
    error_unknownIdentifier: 'Định danh không xác định "{name}"',
    error_unknownFunction: 'Hàm không xác định "{name}"',
    error_takesOneArg: '{name}() nhận 1 đối số',
    error_takesTwoArgs: '{name}() nhận 2 đối số',
    error_unexpectedToken: 'Token không mong đợi',
  },
  es: {
    title: 'Calculadora científica',
    description:
      'Funciones: sin, cos, tan, asin, acos, atan, log (base 10), ln, sqrt, exp, abs, !, ^. Constantes: pi, e.',
    placeholder: 'p. ej. sin(pi/4) + sqrt(16)',
    expression: 'Expresión',
    backspace: 'Retroceso',
    error: 'Error',
    syntaxError: 'Error de sintaxis',
    error_invalidNumber: 'Número no válido en la posición {pos}',
    error_unexpectedChar: 'Carácter inesperado "{char}" en la posición {pos}',
    error_unexpectedEnd: 'Fin de entrada inesperado',
    error_expectedToken: 'Se esperaba "{token}"',
    error_expectedClose: 'Se esperaba ")"',
    error_unknownIdentifier: 'Identificador desconocido "{name}"',
    error_unknownFunction: 'Función desconocida "{name}"',
    error_takesOneArg: '{name}() recibe 1 argumento',
    error_takesTwoArgs: '{name}() recibe 2 argumentos',
    error_unexpectedToken: 'Token inesperado',
  },
  pt: {
    title: 'Calculadora científica',
    description:
      'Funções: sin, cos, tan, asin, acos, atan, log (base 10), ln, sqrt, exp, abs, !, ^. Constantes: pi, e.',
    placeholder: 'ex.: sin(pi/4) + sqrt(16)',
    expression: 'Expressão',
    backspace: 'Apagar',
    error: 'Erro',
    syntaxError: 'Erro de sintaxe',
    error_invalidNumber: 'Número inválido na posição {pos}',
    error_unexpectedChar: 'Caractere inesperado "{char}" na posição {pos}',
    error_unexpectedEnd: 'Fim de entrada inesperado',
    error_expectedToken: 'Esperado "{token}"',
    error_expectedClose: 'Esperado ")"',
    error_unknownIdentifier: 'Identificador desconhecido "{name}"',
    error_unknownFunction: 'Função desconhecida "{name}"',
    error_takesOneArg: '{name}() recebe 1 argumento',
    error_takesTwoArgs: '{name}() recebe 2 argumentos',
    error_unexpectedToken: 'Token inesperado',
  },
};
