import type { LocalizedStrings } from '@anytools/ui';

const EN = {
  title: 'JSON Diff',
  original: 'Original',
  modified: 'Modified',
  originalJson: 'Original JSON',
  modifiedJson: 'Modified JSON',
  invalid: '{side} JSON is invalid: {error}',
  identical: 'Structurally identical — key order and whitespace ignored.',
  added: 'added',
  removed: 'removed',
  changed: 'changed',
  typeChanged: 'type-changed',
  unsafeWarning: 'Integers above 2^53 cannot be compared exactly: {list}',
};

export const STRINGS: LocalizedStrings<typeof EN> = {
  en: EN,
  vi: {
    original: 'Bản gốc',
    modified: 'Bản sửa',
    originalJson: 'JSON gốc',
    modifiedJson: 'JSON đã sửa',
    invalid: 'JSON {side} không hợp lệ: {error}',
    identical: 'Giống nhau về cấu trúc — bỏ qua thứ tự khóa và khoảng trắng.',
    added: 'thêm',
    removed: 'xóa',
    changed: 'đổi',
    typeChanged: 'đổi kiểu',
    unsafeWarning: 'Số nguyên lớn hơn 2^53 không so sánh chính xác được: {list}',
  },
  es: {
    original: 'Original',
    modified: 'Modificado',
    originalJson: 'JSON original',
    modifiedJson: 'JSON modificado',
    invalid: 'El JSON {side} no es válido: {error}',
    identical: 'Estructuralmente idénticos: se ignoran el orden de claves y los espacios.',
    added: 'añadido',
    removed: 'eliminado',
    changed: 'cambiado',
    typeChanged: 'tipo cambiado',
    unsafeWarning: 'Los enteros mayores que 2^53 no se pueden comparar con exactitud: {list}',
  },
  pt: {
    original: 'Original',
    modified: 'Modificado',
    originalJson: 'JSON original',
    modifiedJson: 'JSON modificado',
    invalid: 'O JSON {side} é inválido: {error}',
    identical: 'Estruturalmente idênticos — ordem das chaves e espaços ignorados.',
    added: 'adicionado',
    removed: 'removido',
    changed: 'alterado',
    typeChanged: 'tipo alterado',
    unsafeWarning: 'Inteiros acima de 2^53 não podem ser comparados com exatidão: {list}',
  },
};
