import type { LocalizedStrings } from '@anytools/ui';

const EN = {
  title: 'Retirement Calculator',
  description: 'Project balance at retirement + safe-withdrawal annual income.',
  currentSavings: 'Current savings',
  monthlyContribution: 'Monthly contribution',
  currentAge: 'Current age',
  retirementAge: 'Retirement age',
  annualReturn: 'Annual return rate',
  row_years: 'Years to retire',
  yearsValue: '{n} yrs',
  row_totalContributed: 'Total contributed',
  row_interestEarned: 'Interest earned',
  row_balance: 'Balance at retirement',
  row_safe: 'Safe withdrawal (4% rule)',
  perYear: '{amount}/yr',
  row_perMonth: '… per month',
  disclaimer:
    'Estimation only. Real returns vary with market, inflation, taxes, and fees. The 4% rule assumes a balanced portfolio and is a guideline, not a guarantee.',
};

export const STRINGS: LocalizedStrings<typeof EN> = {
  en: EN,
  vi: {
    title: 'Máy tính hưu trí',
    description: 'Dự tính số dư khi nghỉ hưu + thu nhập năm theo mức rút an toàn.',
    currentSavings: 'Tiết kiệm hiện có',
    monthlyContribution: 'Đóng góp hằng tháng',
    currentAge: 'Tuổi hiện tại',
    retirementAge: 'Tuổi nghỉ hưu',
    annualReturn: 'Tỷ suất sinh lời năm',
    row_years: 'Số năm tới khi nghỉ hưu',
    yearsValue: '{n} năm',
    row_totalContributed: 'Tổng tiền đã góp',
    row_interestEarned: 'Tiền lãi nhận được',
    row_balance: 'Số dư khi nghỉ hưu',
    row_safe: 'Rút an toàn (quy tắc 4%)',
    perYear: '{amount}/năm',
    row_perMonth: '… mỗi tháng',
    disclaimer:
      'Chỉ mang tính ước lượng. Lợi nhuận thực tế phụ thuộc thị trường, lạm phát, thuế và phí. Quy tắc 4% giả định danh mục cân bằng và chỉ là hướng dẫn, không phải bảo đảm.',
  },
  es: {
    title: 'Calculadora de jubilación',
    description: 'Proyecta el saldo al jubilarte + ingreso anual con retiro seguro.',
    currentSavings: 'Ahorros actuales',
    monthlyContribution: 'Aportación mensual',
    currentAge: 'Edad actual',
    retirementAge: 'Edad de jubilación',
    annualReturn: 'Rentabilidad anual',
    row_years: 'Años hasta la jubilación',
    yearsValue: '{n} años',
    row_totalContributed: 'Total aportado',
    row_interestEarned: 'Intereses ganados',
    row_balance: 'Saldo al jubilarte',
    row_safe: 'Retiro seguro (regla del 4 %)',
    perYear: '{amount}/año',
    row_perMonth: '… al mes',
    disclaimer:
      'Solo estimación. La rentabilidad real varía con el mercado, la inflación, los impuestos y las comisiones. La regla del 4 % supone una cartera equilibrada y es una orientación, no una garantía.',
  },
  pt: {
    title: 'Calculadora de aposentadoria',
    description: 'Projeta o saldo na aposentadoria + renda anual com retirada segura.',
    currentSavings: 'Poupança atual',
    monthlyContribution: 'Aporte mensal',
    currentAge: 'Idade atual',
    retirementAge: 'Idade de aposentadoria',
    annualReturn: 'Taxa de retorno anual',
    row_years: 'Anos até se aposentar',
    yearsValue: '{n} anos',
    row_totalContributed: 'Total aportado',
    row_interestEarned: 'Juros ganhos',
    row_balance: 'Saldo na aposentadoria',
    row_safe: 'Retirada segura (regra dos 4%)',
    perYear: '{amount}/ano',
    row_perMonth: '… por mês',
    disclaimer:
      'Apenas estimativa. Os retornos reais variam com o mercado, a inflação, impostos e taxas. A regra dos 4% pressupõe uma carteira equilibrada e é uma orientação, não uma garantia.',
  },
};
